// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` to refresh. Editing this
// file by hand is undone by the next run, and a stale index is a test asking
// the ORM about a table nothing mapped.
//
// The entity index — every module **this host installed**, keyed by its module
// id, with the `entities` array that module published on its own `./backend`
// (`specs/109-backend-test-kit/` T065).
//
// ## What it is for
//
// A server-bound test writes rows, and a row needs the entity class **the ORM
// registered**. A module package publishes one `entities` array and no entity
// class by name (D-168), so a test picks the class out of the array:
//
//     import { entityNamedIn } from '@endora-commerce/test-kit/support';
//     import type { Widget as WidgetRow } from '@endora-commerce/mod-widgets/test-support';
//     import { installedModuleEntities } from './entities.generated.js';
//
//     const Widget = entityNamedIn<WidgetRow>(installedModuleEntities, 'widgets', 'Widget');
//
// The **class** comes off the array, which is the one copy the ORM discovered;
// the **row type** comes off that module's `./test-support`, `export type` only,
// so nothing is evaluated twice (R10 property 3).
//
// ## Why it is generated and cannot be a package
//
// *Which modules one deployment installed* is the single fact a package that may
// name no module is forbidden to know (109 R2.2, FR-001). The kit therefore
// carries the lookup and the index's type and never a member of it, and this
// file — one per host, rendered from that host's own install — carries the
// population.
//
// **Resolution is by class name, never by position.** A tuple index compiles for
// any ordering, so re-ordering the array inside a module would silently re-point
// every caller at another table.

import { entities as entities0 } from '@endora-commerce/mod-i18n/backend';
import { entities as entities1 } from '@endora-commerce/mod-addresses/backend';
import { entities as entities2 } from '@endora-commerce/mod-admin-actions/backend';
import { entities as entities3 } from '@endora-commerce/mod-admin-notifications/backend';
import { entities as entities4 } from '@endora-commerce/mod-admin-roles/backend';
import { entities as entities5 } from '@endora-commerce/mod-admin-users/backend';
import { entities as entities6 } from '@endora-commerce/mod-analytics/backend';
import { entities as entities7 } from '@endora-commerce/mod-api-keys/backend';
import { entities as entities8 } from '@endora-commerce/mod-assets-library/backend';
import { entities as entities9 } from '@endora-commerce/mod-audit-logs/backend';
import { entities as entities10 } from '@endora-commerce/mod-auth/backend';
import { entities as entities11 } from '@endora-commerce/mod-blog/backend';
import { entities as entities12 } from '@endora-commerce/mod-carts/backend';
import { entities as entities13 } from '@endora-commerce/mod-catalog/backend';
import { entities as entities14 } from '@endora-commerce/mod-cms/backend';
import { entities as entities15 } from '@endora-commerce/mod-comarch-xl/backend';
import { entities as entities16 } from '@endora-commerce/mod-comparisons/backend';
import { entities as entities17 } from '@endora-commerce/mod-credentials/backend';
import { entities as entities18 } from '@endora-commerce/mod-credit-limits/backend';
import { entities as entities19 } from '@endora-commerce/mod-currencies/backend';
import { entities as entities20 } from '@endora-commerce/mod-custom-fields/backend';
import { entities as entities21 } from '@endora-commerce/mod-customer-accounts/backend';
import { entities as entities22 } from '@endora-commerce/mod-customers/backend';
import { entities as entities23 } from '@endora-commerce/mod-delivery-methods/backend';
import { entities as entities24 } from '@endora-commerce/mod-dictionaries/backend';
import { entities as entities25 } from '@endora-commerce/mod-email/backend';
import { entities as entities26 } from '@endora-commerce/mod-erp-connector/backend';
import { entities as entities27 } from '@endora-commerce/mod-google-analytics/backend';
import { entities as entities28 } from '@endora-commerce/mod-google-tag-manager/backend';
import { entities as entities29 } from '@endora-commerce/mod-import-export/backend';
import { entities as entities30 } from '@endora-commerce/mod-infakt/backend';
import { entities as entities31 } from '@endora-commerce/mod-inventory/backend';
import { entities as entities32 } from '@endora-commerce/mod-invoice-ledger/backend';
import { entities as entities33 } from '@endora-commerce/mod-invoices/backend';
import { entities as entities34 } from '@endora-commerce/mod-ksef/backend';
import { entities as entities35 } from '@endora-commerce/mod-languages/backend';
import { entities as entities36 } from '@endora-commerce/mod-linkedin-ads/backend';
import { entities as entities37 } from '@endora-commerce/mod-megamenu/backend';
import { entities as entities38 } from '@endora-commerce/mod-meta-ads/backend';
import { entities as entities39 } from '@endora-commerce/mod-mfa/backend';
import { entities as entities40 } from '@endora-commerce/mod-newsletter/backend';
import { entities as entities41 } from '@endora-commerce/mod-orders/backend';
import { entities as entities42 } from '@endora-commerce/mod-organizations/backend';
import { entities as entities43 } from '@endora-commerce/mod-payment-methods/backend';
import { entities as entities44 } from '@endora-commerce/mod-payments/backend';
import { entities as entities45 } from '@endora-commerce/mod-pim-connector/backend';
import { entities as entities46 } from '@endora-commerce/mod-pim-ergonode/backend';
import { entities as entities47 } from '@endora-commerce/mod-pim-pimcore/backend';
import { entities as entities48 } from '@endora-commerce/mod-price-lists/backend';
import { entities as entities49 } from '@endora-commerce/mod-product-feeds/backend';
import { entities as entities50 } from '@endora-commerce/mod-promotions/backend';
import { entities as entities51 } from '@endora-commerce/mod-prompt-actions/backend';
import { entities as entities52 } from '@endora-commerce/mod-pwa/backend';
import { entities as entities53 } from '@endora-commerce/mod-quick-order/backend';
import { entities as entities54 } from '@endora-commerce/mod-quote-requests/backend';
import { entities as entities55 } from '@endora-commerce/mod-returns/backend';
import { entities as entities56 } from '@endora-commerce/mod-sales-channels/backend';
import { entities as entities57 } from '@endora-commerce/mod-search/backend';
import { entities as entities58 } from '@endora-commerce/mod-seo/backend';
import { entities as entities59 } from '@endora-commerce/mod-settings/backend';
import { entities as entities60 } from '@endora-commerce/mod-shipments/backend';
import { entities as entities61 } from '@endora-commerce/mod-shopping-lists/backend';
import { entities as entities62 } from '@endora-commerce/mod-taxes/backend';
import { entities as entities63 } from '@endora-commerce/mod-transactional-emails/backend';
import { entities as entities64 } from '@endora-commerce/mod-webhooks/backend';

/**
 * What a module package publishes in its `entities` array.
 *
 * Declared here rather than imported from the kit, so this file has no
 * dependency of its own — an instance that runs no test never installs the kit,
 * and a type-only import of it would be unresolvable the first time such a client
 * compiled this file. It is structurally `InstalledEntityIndex`, which is what
 * the consumer's argument position checks it against.
 */
type PublishedEntityClass = abstract new (...args: never[]) => object;

/**
 * Every installed module's published entity classes, keyed by module id.
 *
 * **Annotated, not inferred**, and that is TS2742 rather than a preference: the
 * inferred type is a tuple of classes declared inside packages whose paths a
 * consumer cannot name, so `tsc` refuses it once per entity class in the whole
 * install. Nothing a caller uses is lost — `entityNamedIn` takes the module id as
 * a string.
 *
 * A module with an empty array is a module that owns no table, which is a legal
 * state with a loud answer: asking for a class of it names every class it does
 * declare, `(empty)` included. A module that is **absent** is a different
 * answer — `ModuleNotInstalledError`, naming the ids that are here.
 */
export const installedModuleEntities: Readonly<
  Record<string, readonly PublishedEntityClass[]>
> = {
  _i18n: entities0,
  addresses: entities1,
  admin_actions: entities2,
  admin_notifications: entities3,
  admin_roles: entities4,
  admin_users: entities5,
  analytics: entities6,
  api_keys: entities7,
  assets_library: entities8,
  audit_logs: entities9,
  auth: entities10,
  blog: entities11,
  carts: entities12,
  catalog: entities13,
  cms: entities14,
  comarch_xl: entities15,
  comparisons: entities16,
  credentials: entities17,
  credit_limits: entities18,
  currencies: entities19,
  custom_fields: entities20,
  customer_accounts: entities21,
  customers: entities22,
  delivery_methods: entities23,
  dictionaries: entities24,
  email: entities25,
  erp_connector: entities26,
  google_analytics: entities27,
  google_tag_manager: entities28,
  import_export: entities29,
  infakt: entities30,
  inventory: entities31,
  invoice_ledger: entities32,
  invoices: entities33,
  ksef: entities34,
  languages: entities35,
  linkedin_ads: entities36,
  megamenu: entities37,
  meta_ads: entities38,
  mfa: entities39,
  newsletter: entities40,
  orders: entities41,
  organizations: entities42,
  payment_methods: entities43,
  payments: entities44,
  pim_connector: entities45,
  pim_ergonode: entities46,
  pim_pimcore: entities47,
  price_lists: entities48,
  product_feeds: entities49,
  promotions: entities50,
  prompt_actions: entities51,
  pwa: entities52,
  quick_order: entities53,
  quote_requests: entities54,
  returns: entities55,
  sales_channels: entities56,
  search: entities57,
  seo: entities58,
  settings: entities59,
  shipments: entities60,
  shopping_lists: entities61,
  taxes: entities62,
  transactional_emails: entities63,
  webhooks: entities64,
};
