/**
 * The divergence report, rendered for a client's instance
 * (`specs/107-override-report-and-ladder/contracts/divergence-report.md`;
 * `specs/110-instance-repository/contracts/instance-tree.md` §2.2, §2.6).
 *
 * ## Why an instance renders one at all
 *
 * `endora new instance` writes `apps/<deployment>/divergence.ts` and
 * `apps/<deployment>/modules/.gitkeep`, so the tree a client customises in
 * exists from the first minute — and until T138a nothing could describe it. The
 * renderer was `backend/scripts/generate-divergence.ts`, over this repository's
 * module layout, its platform sources and a port→owner map built from module
 * **sources**, none of which an instance has. D-30 asks that *"every override is
 * visible in a generated artefact"*, and for every tree but this one that was
 * a sentence with no implementation behind it.
 *
 * ## The population is the parameter; the derivation is one program (R3.5)
 *
 * Nine kinds, each from one seam of `ModuleContext`, over the deployment's own
 * overlay tree. **That population is identical in the two hosts** — an overlay
 * module is a client's own source in either tree — so every kind an instance
 * records is the kind this repository records, derived by the same
 * `deriveDivergence`.
 *
 * ## What is genuinely narrower, and where the artefact says so
 *
 * Attribution, in one place. This repository's owner map has three sources —
 * module sources, a composition root's bridging table, and installed packages —
 * and an instance has the third alone: every module is an installed package and
 * `composeApp` is the platform's, so a name the platform registers on a module's
 * behalf is reported as a composition root's rather than as that module's. That
 * is true of the instance and is simply less specific than ours, and it is
 * written into the report's own `boundary.notRecorded`
 * (`lib/divergence-artefacts.ts`' `INSTANCE_BOUNDARY_NOTES`) rather than left for
 * a client to discover by reading a report with a silent hole in it.
 *
 * Two differences in the artefact **set** rather than in what a report records,
 * both of them deliberate:
 *
 *  - **markdown and JSON, never a typed TS module.** The `.ts` rendering's two
 *    readers here are a program and `overlay:check`'s byte-comparison; an
 *    instance has no check estate (`instance-tree.md` §2.5) and the emitted
 *    module imports `DivergenceReport` by a **relative** path, which
 *    `backend/src/overlay/types.ts` carries and an instance has no equivalent
 *    of. A bare specifier there would be the one generated artefact whose import
 *    depends on the client's dependency graph, which is the state that file's own
 *    header exists to refuse. JSON is the machine shape with no import at all.
 *  - **no bare-core rendering.** This repository renders one because `DEPLOYMENT`
 *    is legitimately unset here; an instance is scaffolded with exactly one
 *    deployment and every build composes it, so a bare-core report would describe
 *    a build the client never makes.
 *
 * ## It is committed, unlike the other three artefacts this command writes
 *
 * §1 of the report contract is the predicate: *an artefact is committed when its
 * content is a fact about the tree, and resolved at runtime when it is a fact
 * about the process*. A deployment's overlay modules and what they decorate are
 * facts about the client's own tree, visible in the merge request that creates
 * them — which is the whole reason the report is worth having. So this pair is
 * not `.gitignore`d and the header does not tell a reader not to commit it.
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

import {
  instanceComposition,
  INSTANCE_BOUNDARY_NOTES,
  overlaySourcesUnder,
  readDivergenceDeclaration,
  renderDivergenceArtefacts,
  unreadableCompositionReason,
  EMPTY_DECLARATION,
  type DivergenceRendering,
} from '../lib/divergence-artefacts.js';
import {
  scanInstalledPlatformPackage,
  type ModulePackage,
} from '../lib/module-packages.js';

/** Raised when this half has an input it could not read — the caller's exit 2. */
export class DivergenceHostError extends Error {
  override readonly name = 'DivergenceHostError';
}

/** The "do not edit" header an instance's rendered report carries. */
export const INSTANCE_DIVERGENCE_MARKDOWN_HEADER = [
  '<!-- AUTO-GENERATED by `endora generate` — DO NOT EDIT. -->',
  '<!-- It is derived from this deployment’s own `modules/` tree and its `divergence.ts`, -->',
  '<!-- so it is a fact about your repository: commit it, and read the diff. -->',
];

/** Sorted directory names directly under a root; `[]` when there is none. */
function directoriesUnder(root: string): readonly string[] {
  if (!existsSync(root)) return [];
  try {
    return readdirSync(root, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
      .map((entry) => entry.name)
      .sort();
  } catch {
    return [];
  }
}

/** Every deployment in an instance — one directory under `<root>/apps/`. */
export function instanceDeployments(root: string): readonly string[] {
  return directoriesUnder(join(root, 'apps'));
}

/**
 * The deployment's declaration file on disk, or `null`.
 *
 * `.ts` before `.js`, which is the opposite of the platform's own resolution
 * order and is right for this reader: the platform resolves what it is about to
 * **execute**, where a stray source beside a build is the wrong answer, and this
 * reads what the client **wrote**.
 */
function declarationPathFor(root: string, deployment: string): string | null {
  for (const extension of ['ts', 'mts', 'cts', 'js', 'mjs', 'cjs']) {
    const candidate = join(root, 'apps', deployment, `divergence.${extension}`);
    try {
      if (statSync(candidate).isFile()) return candidate;
    } catch {
      continue;
    }
  }
  return null;
}

/** One deployment's rendered pair, and what the run could not read producing it. */
export interface InstanceDivergence {
  readonly deployment: string;
  readonly renderings: readonly DivergenceRendering[];
  readonly overlayModules: readonly string[];
  readonly entries: number;
  /** Findings the derivation raised — `check:divergence`'s subject, printed here. */
  readonly findings: ReadonlyArray<{ readonly kind: string; readonly where: string; readonly detail: string }>;
  /** Declaration fields this run could not resolve to literals, each named. */
  readonly unresolvedDeclaration: readonly string[];
}

/**
 * Render one report per deployment this instance holds.
 *
 * A tree with no `apps/` directory at all is the empty list rather than a
 * refusal: an instance scaffolded and not yet customised is a supported state,
 * and the caller names it as an omission the way it names an absent admin
 * member.
 */
export function renderInstanceDivergence(input: {
  readonly root: string;
  readonly packages: readonly ModulePackage[];
}): readonly InstanceDivergence[] {
  const deployments = instanceDeployments(input.root);
  if (deployments.length === 0) return [];

  const platform = scanInstalledPlatformPackage(input.root);
  if (platform === null) {
    throw new DivergenceHostError(
      `no installed package in ${join(input.root, 'node_modules')} declares ` +
        '`endora.type: "platform"`, so the composition this deployment diverges *from* cannot ' +
        'be read: no container name has an owner, no endpoint has a route, and ' +
        "`ModuleContext`'s own members — the list every seam is classified against — are " +
        'unknown. A report derived from that would record every decoration as owned by nobody ' +
        'and classify no seam at all. Run `pnpm install` first.',
    );
  }

  const scan = instanceComposition({ packages: input.packages, platform });
  const unreadable = unreadableCompositionReason(scan);
  if (unreadable !== null) throw new DivergenceHostError(unreadable);
  if (scan.environment.seams.length === 0) {
    throw new DivergenceHostError(
      `${platform.name} publishes no file declaring the \`ModuleContext\` interface beside its ` +
        '`./kernel` entry point, so there is nothing to classify this deployment’s seams ' +
        'against. Every seam would be recorded with no rung and the `unclassified-seam` ' +
        'finding could never fire, which is a finding about this run dressed as a clean tree.',
    );
  }

  return deployments.map((deployment) => {
    const overlayRoot = join(input.root, 'apps', deployment, 'modules');
    const overlayModules = directoriesUnder(overlayRoot);
    const sources = overlaySourcesUnder(overlayRoot, overlayModules, input.root);

    const declarationPath = declarationPathFor(input.root, deployment);
    const reading =
      declarationPath === null
        ? { declaration: EMPTY_DECLARATION, unresolved: [] as readonly string[] }
        : readDivergenceDeclaration(readFileSync(declarationPath, 'utf8'), declarationPath);

    const base = join(input.root, 'apps', deployment, 'divergence.generated');
    const { result, renderings } = renderDivergenceArtefacts(
      {
        deployment,
        overlayRoot: relative(input.root, overlayRoot).split(sep).join('/'),
        overlayModules,
        sources,
        routes: scan.environment.routes,
        owners: scan.environment.owners,
        rootSupplied: scan.environment.rootSupplied,
        declaration: reading.declaration,
        seams: scan.environment.seams,
        hostNotRecorded: INSTANCE_BOUNDARY_NOTES,
      },
      [
        {
          rendering: 'markdown',
          outputPath: `${base}.md`,
          header: INSTANCE_DIVERGENCE_MARKDOWN_HEADER,
          label: `the divergence report for \`${deployment}\``,
        },
        {
          rendering: 'json',
          outputPath: `${base}.json`,
          label: `the divergence report for \`${deployment}\`, as data`,
        },
      ],
    );

    return {
      deployment,
      renderings,
      overlayModules,
      entries: result.report.entries.length,
      findings: result.findings.map((finding) => ({
        kind: finding.kind,
        where: finding.where,
        detail: finding.detail,
      })),
      unresolvedDeclaration: reading.unresolved,
    };
  });
}
