// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// The admin contribution registry — every module package's `./admin` layer,
// named by the bare specifier its own `exports` map declares (feature 091,
// `contracts/admin-registry.md`).
//
// It exists because `admin/src/App.tsx` and `admin/src/components/AppShell.tsx`
// were the last two registries a module author had to hand-edit. Measured over
// the twelve most recently added modules, 11 of 12 edited each of them, while
// every backend registration point they also used to edit — the composition,
// the two `db/` registries, the manifest index, the permission inventory — had
// already been converted to a generator or a derivation. This is that remedy,
// applied to the two that were left.
//
// **Enumerable without being executed.** Every route and zone component in a
// contribution is a `() => import('…')` factory, so importing this file costs
// the declarations and none of the screens: Vite splits one chunk per module
// and an operator downloads only what their role can reach.
//
// **The registry answers "what could be here", never "what is here now".**
// Presence and permission are applied at render by `isSurfaceVisible`, the one
// predicate the sidebar, the palette and the dashboard already share — an
// operator's activation flip must take effect without a rebuild (Principle XVII
// item 5), and a registry that filtered would make it a restart.
//
// **Bare core under every value of `DEPLOYMENT`** (D-104), like the manifest
// index: a deployment's overlay modules are discovered at runtime and
// contribute to no committed artefact.

import type { AdminContributions } from '@endora-commerce/admin-kit/contributions';

import { contributions as contributions0 } from '@endora-commerce/mod-admin-roles/admin';
import { contributions as contributions1 } from '@endora-commerce/mod-admin-users/admin';
import { contributions as contributions2 } from '@endora-commerce/mod-analytics/admin';
import { contributions as contributions3 } from '@endora-commerce/mod-audit-logs/admin';
import { contributions as contributions4 } from '@endora-commerce/mod-carts/admin';
import { contributions as contributions5 } from '@endora-commerce/mod-google-analytics/admin';
import { contributions as contributions6 } from '@endora-commerce/mod-import-export/admin';
import { contributions as contributions7 } from '@endora-commerce/mod-linkedin-ads/admin';
import { contributions as contributions8 } from '@endora-commerce/mod-meta-ads/admin';
import { contributions as contributions9 } from '@endora-commerce/mod-mfa/admin';

/** One module's contribution set, keyed by the module id that shipped it. */
export interface AdminRegistryEntry {
  readonly moduleId: string;
  readonly contributions: AdminContributions;
}

export const MODULE_ADMIN_CONTRIBUTIONS: readonly AdminRegistryEntry[] = [
  { moduleId: 'admin_roles', contributions: contributions0 },
  { moduleId: 'admin_users', contributions: contributions1 },
  { moduleId: 'analytics', contributions: contributions2 },
  { moduleId: 'audit_logs', contributions: contributions3 },
  { moduleId: 'carts', contributions: contributions4 },
  { moduleId: 'google_analytics', contributions: contributions5 },
  { moduleId: 'import_export', contributions: contributions6 },
  { moduleId: 'linkedin_ads', contributions: contributions7 },
  { moduleId: 'meta_ads', contributions: contributions8 },
  { moduleId: 'mfa', contributions: contributions9 },
];
