/**
 * CI check — no source file in this repository carries a raw NUL byte (issue #190).
 *
 * ## Why a byte deserves its own check
 *
 * The artefact that would reveal this defect **is the diff itself**. Git's
 * content filter classifies a blob as binary when it finds a NUL in it, and from
 * that moment every diff of the file reads `Binary files a/… and b/… differ`.
 * The file stops being reviewable: `git diff`, `git blame -L`, the MR widget and
 * every review UI show nothing at all. So the one thing that would have caught
 * the byte during review is the thing the byte switches off.
 *
 * That is not hypothetical. Six files in this tree spelled a NUL separator as a
 * raw byte inside a template literal — `media-ingestor.ts` (issue #182) plus the
 * five issue #190 names — and each survived every review of every commit that
 * touched it, because none of those commits could be read.
 *
 * The separator itself is correct in all six: NUL is the one byte the joined
 * fields cannot contain, which is exactly what a join separator has to be. The
 * defect is never the byte's *value*, only how the **source** spells it. Write
 * `\0` (or `\x00`) and the compiled string is identical to the last bit while
 * the source stays text.
 *
 * ## Anywhere in the file, not just where git looks
 *
 * Git only reads the **first 8000 bytes** when it decides binary-or-not. The NUL
 * in `admin_actions/services/admin-actions-service.ts` sat at byte 8032, so git
 * kept diffing that file as text and only `file(1)` disagreed — the byte was
 * still there, still one edit away from crossing the window, and still invisible
 * to every tool that does not share git's heuristic. A rule that copied git's
 * window would have declared that file clean. This check reads the whole file.
 *
 * ## Only NUL
 *
 * The other C0 control characters are not in scope, deliberately. A raw `\x1f`
 * is unpleasant but it does not change how any tool classifies the file: the
 * diff still renders, review still works, and the ratchet this check installs
 * would be claiming more than the failure it was written for. NUL is the byte
 * with the tooling consequence, so NUL is the byte with the rule.
 *
 * ## The population, and how it fails
 *
 * Every file under the repository root **except** the two exclusions declared
 * below, each with its reason:
 *
 *   - `SKIPPED_DIRECTORIES` — trees that are not this repository's source.
 *   - `BINARY_EXTENSIONS` and `BINARY_FILENAMES` — file types whose content is
 *     bytes by definition. A PNG is not a source file with a NUL problem; it is
 *     not a source file.
 *
 * The exclusion is a **deny-list on purpose**. An allow-list of known-text
 * extensions fails open: the next `.sql`, `.toml` or extension-less script to
 * arrive would be silently unscanned, and nothing would report it. With a
 * deny-list a new file type is scanned by default, and a genuinely binary one
 * announces itself by failing this check once — at which point it is added here
 * with a reason rather than to a silent skip.
 *
 * A text file that genuinely must keep a NUL — a fixture whose whole point is a
 * real NUL arriving in real data — goes in `NUL_BYTES_ALLOWED` with a reason.
 * That ledger is **two-way**: an unledgered NUL fails the build, and a ledger
 * entry naming a file that no longer has one fails it too. It is empty; the five
 * issue #190 files were all repaired rather than ledgered, because in every one
 * of them the escape produces the same string at runtime and loses nothing.
 *
 * Usage: `tsx scripts/check-nul-bytes.ts [--list]`
 * Exit 0 = no unledgered NUL byte; exit 1 = at least one, or a stale ledger
 * entry; exit 2 = nothing was read, so a pass would be vacuous.
 */
/* eslint-disable no-console -- CLI check: stdout/stderr is the interface. */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..');

/**
 * Directory names pruned wherever they occur, and why each is not source.
 *
 * Declared rather than hard-coded into the walk so that the reason travels with
 * the exclusion: a directory skipped here is a directory this check makes no
 * claim about, and the next reader gets to see which claim was dropped.
 */
export const SKIPPED_DIRECTORIES: Readonly<Record<string, string>> = {
  '.git': "Git's own object store — every pack file is binary by construction.",
  node_modules: "Installed dependencies: third-party bytes, not this repository's source.",
  dist: 'Build output, reproduced from source by the build.',
  build: 'Build output, reproduced from source by the build.',
  '.next': "Next.js build output, reproduced from the storefront's source.",
  coverage: 'Coverage report output, regenerated by every run.',
  '.pnpm-store': "pnpm's content-addressed package store.",
  'test-results': 'Playwright run output, regenerated by every run.',
  'playwright-report': 'Playwright report output, regenerated by every run.',
};

/**
 * Extensions whose content is bytes by definition, and why.
 *
 * A file here is out of the population entirely — not exempted from the rule but
 * outside it, because "a source file must not contain a NUL" says nothing about
 * a PNG. Adding an entry is cheap and visible; the cost of getting it wrong is
 * one file that stops being checked, which is why each carries a reason.
 */
export const BINARY_EXTENSIONS: Readonly<Record<string, string>> = {
  '.png': 'Raster image — app icons and the Playwright visual snapshots.',
  '.jpg': 'Raster image.',
  '.jpeg': 'Raster image.',
  '.gif': 'Raster image.',
  '.webp': 'Raster image.',
  '.avif': 'Raster image.',
  '.ico': 'Icon bundle — a container of raster images.',
  '.pdf': 'Portable Document Format — a compressed byte container.',
  '.zip': 'Archive — a compressed byte container.',
  '.gz': 'Compressed stream.',
  '.woff': 'Web font — a compressed font container.',
  '.woff2': 'Web font — a compressed font container.',
  '.ttf': 'Font — glyph outlines in a binary table format.',
  '.otf': 'Font — glyph outlines in a binary table format.',
  '.eot': 'Font — glyph outlines in a binary table format.',
  '.mp4': 'Video — an encoded media container.',
  '.webm': 'Video — an encoded media container.',
  '.wasm': 'WebAssembly module — a binary instruction format.',
};

/**
 * Exact file names that are binary, for the files that carry no extension.
 *
 * Separate from `BINARY_EXTENSIONS` because a leading dot is a dotfile marker,
 * not an extension: `.gitignore` is text and must stay in the population, so a
 * dot-named file cannot be classified by the same rule. Matched on the basename
 * anywhere in the tree.
 */
export const BINARY_FILENAMES: Readonly<Record<string, string>> = {
  '.thumbnail':
    'Design-tool project thumbnail — a WebP bitmap the tool writes without an extension.',
};

/**
 * Text files allowed to keep a raw NUL, with the reason it is right.
 *
 * **Two-way**, in the idiom of `BARE_SUBSCRIPTIONS_TO_DRAIN`: an unledgered NUL
 * fails the build, and an entry that no longer describes one fails it too.
 *
 * It is empty, and it should stay hard to add to. The obvious candidate — a
 * hostile-input fixture — is not one: a fixture builds a JavaScript string, and
 * `'\x00'` and a raw NUL byte produce the same string with the same code point,
 * so escaping costs the fixture nothing and buys back the diff. An entry here
 * has to name something the *file's bytes* do, not something its values do.
 */
export const NUL_BYTES_ALLOWED: Readonly<Record<string, string>> = {};

/** A file handed to the analysis: repo-relative POSIX path plus its raw bytes. */
export interface ScannedFile {
  readonly path: string;
  readonly bytes: Uint8Array;
}

export interface NulByteFinding {
  /** Repo-relative path, POSIX separators — also the ledger key. */
  readonly path: string;
  /** Byte offset of the first NUL. */
  readonly byteOffset: number;
  /** 1-based line, counting `\n`. */
  readonly line: number;
  /** 1-based **byte** column within that line. */
  readonly column: number;
  /** Total NUL bytes in the file, so a repair that fixes one of six is visible. */
  readonly count: number;
  /** True when git's own 8000-byte window would have missed it. */
  readonly beyondGitBinaryWindow: boolean;
}

/** How many bytes of a blob git reads before deciding binary-or-text. */
export const GIT_BINARY_WINDOW = 8000;

const NUL = 0;

/** The extension of a path, lower-cased, including the dot; `''` when there is none. */
export function extensionOf(path: string): string {
  const base = path.slice(path.lastIndexOf('/') + 1);
  const dot = base.lastIndexOf('.');
  // A leading dot is a dotfile (`.gitignore`), not an extension.
  if (dot <= 0) return '';
  return base.slice(dot).toLowerCase();
}

/**
 * Whether a path is in the population.
 *
 * Path-based rather than walk-based so the two exclusions are provable from a
 * synthetic path: the pruning a real run does for speed and the exclusion the
 * rule makes are then the same decision, taken in one place.
 */
export function isScannablePath(path: string): boolean {
  const segments = path.split('/');
  if (segments.slice(0, -1).some((segment) => SKIPPED_DIRECTORIES[segment] !== undefined)) {
    return false;
  }
  const basename = segments[segments.length - 1] ?? '';
  if (BINARY_FILENAMES[basename] !== undefined) return false;
  return BINARY_EXTENSIONS[extensionOf(path)] === undefined;
}

/** Every NUL-carrying file among the scannable ones, first occurrence located. */
export function findNulBytes(files: Iterable<ScannedFile>): NulByteFinding[] {
  const found: NulByteFinding[] = [];

  for (const file of files) {
    if (!isScannablePath(file.path)) continue;
    const { bytes } = file;

    let count = 0;
    let first = -1;
    for (let i = 0; i < bytes.length; i += 1) {
      if (bytes[i] === NUL) {
        if (first === -1) first = i;
        count += 1;
      }
    }
    if (first === -1) continue;

    let line = 1;
    let lineStart = 0;
    for (let i = 0; i < first; i += 1) {
      if (bytes[i] === 0x0a) {
        line += 1;
        lineStart = i + 1;
      }
    }

    found.push({
      path: file.path,
      byteOffset: first,
      line,
      column: first - lineStart + 1,
      count,
      beyondGitBinaryWindow: first >= GIT_BINARY_WINDOW,
    });
  }

  found.sort((a, b) => a.path.localeCompare(b.path));
  return found;
}

export interface CheckResult {
  /** Files the analysis actually inspected — the vacuous-pass guard reads this. */
  readonly scanned: number;
  readonly total: number;
  readonly violations: readonly NulByteFinding[];
  readonly ledgered: readonly NulByteFinding[];
  /** Ledger keys that no longer describe a NUL-carrying file. */
  readonly stale: readonly string[];
}

export function checkNulBytes(
  files: Iterable<ScannedFile>,
  ledger: Readonly<Record<string, string>> = NUL_BYTES_ALLOWED,
): CheckResult {
  const scannable = [...files].filter((file) => isScannablePath(file.path));
  const all = findNulBytes(scannable);
  const paths = new Set(all.map((finding) => finding.path));
  return {
    scanned: scannable.length,
    total: all.length,
    violations: all.filter((finding) => ledger[finding.path] === undefined),
    ledgered: all.filter((finding) => ledger[finding.path] !== undefined),
    stale: Object.keys(ledger).filter((path) => !paths.has(path)),
  };
}

function walk(dir: string, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    if (SKIPPED_DIRECTORIES[name] !== undefined) continue;
    const full = join(dir, name);
    // A dangling symlink must not abort the walk, hence `throwIfNoEntry`.
    const stat = statSync(full, { throwIfNoEntry: false });
    if (stat === undefined) continue;
    if (stat.isDirectory()) walk(full, out);
    else if (stat.isFile()) out.push(full);
  }
  return out;
}

function main(): void {
  const listMode = process.argv.includes('--list');

  const files: ScannedFile[] = [];
  for (const full of walk(REPO_ROOT)) {
    const path = relative(REPO_ROOT, full).split('\\').join('/');
    if (!isScannablePath(path)) continue;
    files.push({ path, bytes: readFileSync(full) });
  }

  const result = checkNulBytes(files);
  if (result.scanned === 0) {
    console.error(
      '[nul-bytes] no scannable file under the repository root — refusing to report a vacuous pass',
    );
    process.exit(2);
  }

  if (listMode) {
    for (const finding of findNulBytes(files)) {
      const tag = NUL_BYTES_ALLOWED[finding.path] !== undefined ? 'LEDGERED' : 'RAW NUL ';
      console.log(`${tag} ${finding.path}:${finding.line}:${finding.column} (x${finding.count})`);
    }
    console.log('');
  }

  console.log(
    `[nul-bytes] scanned=${result.scanned} files-with-a-raw-NUL=${result.total} ` +
      `violations=${result.violations.length} ledgered=${result.ledgered.length} ` +
      `ledger-size=${Object.keys(NUL_BYTES_ALLOWED).length} stale=${result.stale.length}`,
  );

  if (result.violations.length > 0) {
    console.error(
      '\nA source file carries a raw NUL byte (issue #190).\n' +
        'Git classifies such a file as binary, so every diff of it reads "Binary files\n' +
        'differ" and the file stops being reviewable — which is how five of these\n' +
        'survived every review of every commit that touched them.\n' +
        'Spell the byte as an escape: `\\0` in a string or template literal produces\n' +
        'exactly the same byte at runtime, so no hash and no key changes.\n',
    );
    for (const finding of result.violations) {
      const window = finding.beyondGitBinaryWindow
        ? ` — past git's ${GIT_BINARY_WINDOW}-byte window, so git itself still calls it text`
        : '';
      console.error(
        `  - ${finding.path}:${finding.line}:${finding.column}  ${finding.count} NUL byte(s)${window}`,
      );
    }
  }
  if (result.stale.length > 0) {
    console.error('\nStale ledger entries (the file no longer carries a NUL — delete them):');
    for (const path of result.stale) console.error(`  - ${path}`);
  }

  process.exit(result.violations.length > 0 || result.stale.length > 0 ? 1 : 0);
}

// CLI only — importing this module (the unit self-test does) must not scan.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
