#!/usr/bin/env tsx
import {
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
  existsSync,
} from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Generates `backend/src/modules/_lifecycle/manifest-index.generated.ts`
 * — a static enumeration of every module's `manifest.ts` import.
 *
 * Why? `registered-manifests.ts` is hand-maintained today. As new
 * modules opt into the lifecycle the team has to remember to add their
 * manifest entry there, which is exactly the kind of edit that gets
 * forgotten. This generator walks `backend/src/modules/<id>/manifest.ts`
 * and emits an index file so the registry list stays in sync with the
 * file system. Downstream code can import the generated index instead
 * of editing the hand-maintained file.
 *
 * Usage:
 *   pnpm --filter backend exec tsx scripts/generate-manifest-index.ts
 *
 * Run as part of the build via the `build` script in `backend/package.json`.
 *
 * The generated file is committed to git so consumers (composition.ts,
 * CLI scripts) get deterministic imports — no runtime filesystem walk.
 */

const here = dirname(fileURLToPath(import.meta.url));
const modulesRoot = resolve(here, '../src/modules');
const outputPath = resolve(
  here,
  '../src/modules/_lifecycle/manifest-index.generated.ts',
);

interface DiscoveredModule {
  id: string;
  importPath: string;
}

/**
 * Predicate: does this manifest file expose the new lifecycle-shape
 * `manifest` export? Pass A retrofit upgraded 9 existing manifests to
 * this shape; Pass B (out of scope for feature 018) covers the rest.
 * Modules whose manifest.ts is settings-only or auth/role-only style
 * are skipped — they are still loaded by the boot-time settings
 * reconciler through the legacy named exports.
 */
function exposesLifecycleManifest(filePath: string): boolean {
  const src = readFileSync(filePath, 'utf8');
  return /export\s+const\s+manifest\s*=\s*defineModuleManifest\(/.test(src);
}

function discover(): DiscoveredModule[] {
  const out: DiscoveredModule[] = [];
  for (const entry of readdirSync(modulesRoot).sort()) {
    const dir = join(modulesRoot, entry);
    if (!statSync(dir).isDirectory()) continue;
    const manifestPath = join(dir, 'manifest.ts');
    if (!existsSync(manifestPath)) continue;
    if (!exposesLifecycleManifest(manifestPath)) continue;
    out.push({
      id: entry,
      // Relative import path from manifest-index.generated.ts to the
      // module's manifest.ts. The generated file lives in
      // `_lifecycle/` so the import is one folder up + the module
      // folder + `manifest.js` (compiled extension).
      importPath: `../${entry}/manifest.js`,
    });
  }
  return out;
}

function emit(mods: DiscoveredModule[]): string {
  const importLines = mods
    .map(
      (m, i) =>
        `import { manifest as manifest_${i} } from '${m.importPath}';`,
    )
    .join('\n');

  const entries = mods
    .map((m, i) => `  { id: '${m.id}', manifest: manifest_${i} },`)
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-manifest-index.ts — DO NOT EDIT.
// Run \`pnpm --filter backend exec tsx scripts/generate-manifest-index.ts\`
// (or rebuild the backend) to refresh.

import type { ModuleManifest } from '@b2b/contracts';

${importLines}

export interface DiscoveredManifestEntry {
  id: string;
  manifest: ModuleManifest;
}

export const DISCOVERED_MANIFESTS: ReadonlyArray<DiscoveredManifestEntry> = [
${entries}
];
`;
}

function main(): void {
  const mods = discover();
  const content = emit(mods);
  writeFileSync(outputPath, content, 'utf8');
  process.stdout.write(
    `[manifest-index] wrote ${mods.length} entries to ${outputPath}\n`,
  );
  for (const m of mods) {
    process.stdout.write(`  · ${m.id}\n`);
  }
}

main();
