#!/usr/bin/env tsx
import {
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
  existsSync,
} from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/**
 * Generates `backend/src/modules/_lifecycle/manifest-index.generated.ts`
 * — a static enumeration of every module's `manifest.ts` import.
 *
 * Why? `registered-manifests.ts` is hand-maintained today. As new
 * modules opt into the lifecycle the team has to remember to add their
 * manifest entry there, which is exactly the kind of edit that gets
 * forgotten. This generator walks `backend/src/modules/<id>/manifest.ts`
 * and emits an index file so the registry list stays in sync with the
 * file system. Downstream code can import the generated index instead
 * of editing the hand-maintained file.
 *
 * Usage:
 *   pnpm --filter backend exec tsx scripts/generate-manifest-index.ts
 *
 * Run as part of the build via the `build` script in `backend/package.json`.
 *
 * The generated file is committed to git so consumers (composition.ts,
 * CLI scripts) get deterministic imports — no runtime filesystem walk.
 */

const here = dirname(fileURLToPath(import.meta.url));
const modulesRoot = resolve(here, '../src/modules');
const outputPath = resolve(
  here,
  '../src/modules/_lifecycle/manifest-index.generated.ts',
);

interface DiscoveredModule {
  id: string;
  importPath: string;
}

/**
 * Predicate: does this manifest file expose the new lifecycle-shape
 * `manifest` export? Pass A retrofit upgraded 9 existing manifests to
 * this shape; Pass B (out of scope for feature 018) covers the rest.
 * Modules whose manifest.ts is settings-only or auth/role-only style
 * are skipped — they are still loaded by the boot-time settings
 * reconciler through the legacy named exports.
 */
function exposesLifecycleManifest(filePath: string): boolean {
  const src = readFileSync(filePath, 'utf8');
  return /export\s+const\s+manifest\s*=\s*defineModuleManifest\(/.test(src);
}

function discover(): DiscoveredModule[] {
  const byId = new Map<string, DiscoveredModule>();
  // 1) Core modules (unchanged behaviour).
  for (const entry of readdirSync(modulesRoot).sort()) {
    const dir = join(modulesRoot, entry);
    if (!statSync(dir).isDirectory()) continue;
    const manifestPath = join(dir, 'manifest.ts');
    if (!existsSync(manifestPath)) continue;
    if (!exposesLifecycleManifest(manifestPath)) continue;
    byId.set(entry, {
      id: entry,
      // Relative import path from manifest-index.generated.ts to the
      // module's manifest.ts. The generated file lives in `_lifecycle/`
      // so the import is one folder up + the module folder + `manifest.js`.
      importPath: `../${entry}/manifest.js`,
    });
  }
  // 2) Overlay modules for the active deployment (feature 057). An overlay
  // module with a NEW id is added; an overlay manifest for an existing core id
  // SHADOWS core. When DEPLOYMENT is unset / has no overlay dir, this is a
  // no-op and the generated index is byte-identical to bare core (FR-008).
  const deployment = process.env['DEPLOYMENT']?.trim();
  if (deployment) {
    const overlayRoot = resolve(here, '../src/apps', deployment, 'modules');
    if (existsSync(overlayRoot)) {
      for (const entry of readdirSync(overlayRoot).sort()) {
        const dir = join(overlayRoot, entry);
        if (!statSync(dir).isDirectory()) continue;
        const manifestPath = join(dir, 'manifest.ts');
        if (!existsSync(manifestPath)) continue;
        if (!exposesLifecycleManifest(manifestPath)) continue;
        byId.set(entry, {
          id: entry,
          // From `_lifecycle/` up to `src/` then into the overlay tree.
          importPath: `../../apps/${deployment}/modules/${entry}/manifest.js`,
        });
      }
    }
  }
  return [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));
}

function emit(mods: DiscoveredModule[]): string {
  const importLines = mods
    .map(
      (m, i) =>
        `import { manifest as manifest_${i} } from '${m.importPath}';`,
    )
    .join('\n');

  const entries = mods
    .map((m, i) => `  { id: '${m.id}', manifest: manifest_${i} },`)
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-manifest-index.ts — DO NOT EDIT.
// Run \`pnpm --filter backend exec tsx scripts/generate-manifest-index.ts\`
// (or rebuild the backend) to refresh.

import type { ModuleManifest } from '@b2b/contracts';

${importLines}

export interface DiscoveredManifestEntry {
  id: string;
  manifest: ModuleManifest;
}

export const DISCOVERED_MANIFESTS: ReadonlyArray<DiscoveredManifestEntry> = [
${entries}
];
`;
}

/** Pure render — the target path + expected file content. Used by the generator
 * and by the git-free determinism check (`check-overlay-determinism.ts`). */
export function renderManifestIndex(): { outputPath: string; content: string } {
  return { outputPath, content: emit(discover()) };
}

function main(): void {
  const { outputPath: out, content } = renderManifestIndex();
  writeFileSync(out, content, 'utf8');
  const count = (content.match(/^\s*\{ id:/gm) ?? []).length;
  process.stdout.write(`[manifest-index] wrote ${count} entries to ${out}\n`);
}

// Only write when executed directly (not when imported by the determinism check).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
