import { z } from 'zod';

/**
 * Central catalog of API error codes — see specs/001-b2b-platform-foundation/contracts/README.md.
 *
 * Every non-2xx response SHOULD use one of these codes. The list grows as modules are added;
 * new codes MUST be screaming-snake-case and documented in the relevant contract file.
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL: 'INTERNAL',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',

  // Catalog
  FILTER_NOT_ALLOWED: 'FILTER_NOT_ALLOWED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  SKU_ALREADY_EXISTS: 'SKU_ALREADY_EXISTS',
  VARIANT_COMBINATION_EXISTS: 'VARIANT_COMBINATION_EXISTS',
  VARIANT_AXIS_MISSING: 'VARIANT_AXIS_MISSING',
  ATTRIBUTE_VALUE_REJECTED: 'ATTRIBUTE_VALUE_REJECTED',
  FIELD_IMMUTABLE: 'FIELD_IMMUTABLE',

  // Quote Requests (RFQ)
  RFQ_NOT_DRAFT: 'RFQ_NOT_DRAFT',
  RFQ_EMPTY: 'RFQ_EMPTY',
  RFQ_NOT_QUOTED: 'RFQ_NOT_QUOTED',
  RFQ_NOT_ACCEPTED: 'RFQ_NOT_ACCEPTED',
  RFQ_NOT_NEW: 'RFQ_NOT_NEW',
  RFQ_ALREADY_CLAIMED: 'RFQ_ALREADY_CLAIMED',
  RFQ_EXPIRED: 'RFQ_EXPIRED',
  QUOTE_INCOMPLETE: 'QUOTE_INCOMPLETE',
  QUOTE_VALIDITY_ENDED: 'QUOTE_VALIDITY_ENDED',

  // Organizations / customer accounts
  ORGANIZATION_TAX_ID_EXISTS: 'ORGANIZATION_TAX_ID_EXISTS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_ALREADY_IN_ORGANIZATION: 'EMAIL_ALREADY_IN_ORGANIZATION',
  EMAIL_BELONGS_TO_ANOTHER_ORGANIZATION: 'EMAIL_BELONGS_TO_ANOTHER_ORGANIZATION',
  TERMS_VERSION_STALE: 'TERMS_VERSION_STALE',
  TOKEN_INVALID_OR_EXPIRED: 'TOKEN_INVALID_OR_EXPIRED',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_REQUIRED_BY_ROLE: 'TWO_FACTOR_REQUIRED_BY_ROLE',
  CANNOT_REMOVE_LAST_ADMIN: 'CANNOT_REMOVE_LAST_ADMIN',
  CANNOT_DEMOTE_LAST_ADMIN: 'CANNOT_DEMOTE_LAST_ADMIN',
  ADDRESS_IN_USE: 'ADDRESS_IN_USE',
  ADDRESS_NOT_OWNED: 'ADDRESS_NOT_OWNED',

  // Orders
  CART_EMPTY: 'CART_EMPTY',
  STOCK_UNAVAILABLE: 'STOCK_UNAVAILABLE',
  PROMOTION_INVALID: 'PROMOTION_INVALID',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  INVOICE_NOT_READY: 'INVOICE_NOT_READY',
  INVALID_TRANSITION: 'INVALID_TRANSITION',

  // Credit Limit
  CREDIT_LIMIT_NOT_GRANTED: 'CREDIT_LIMIT_NOT_GRANTED',
  CREDIT_LIMIT_ALREADY_GRANTED: 'CREDIT_LIMIT_ALREADY_GRANTED',
  LIMIT_INSUFFICIENT: 'LIMIT_INSUFFICIENT',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  ADJUSTMENT_BELOW_ACTIVE: 'ADJUSTMENT_BELOW_ACTIVE',
  ACTIVE_RESERVATIONS_EXIST: 'ACTIVE_RESERVATIONS_EXIST',
  ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
  PRODUCT_IN_STOCK: 'PRODUCT_IN_STOCK',

  // API keys / webhooks / integrations
  API_KEY_OUT_OF_SCOPE: 'API_KEY_OUT_OF_SCOPE',
  WEBHOOK_DELIVERY_NOT_REPLAYABLE: 'WEBHOOK_DELIVERY_NOT_REPLAYABLE',

  // Admin users / roles
  ADMIN_ROLE_CODE_TAKEN: 'ADMIN_ROLE_CODE_TAKEN',
  ADMIN_ROLE_IN_USE: 'ADMIN_ROLE_IN_USE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const errorDetailSchema = z.object({
  path: z.string().describe('dot-path to the offending field inside the request body or query'),
  issue: z.string().describe('human-readable explanation of what failed'),
});

export const errorEnvelopeSchema = z.object({
  error: z.object({
    code: z.enum(Object.values(ERROR_CODES) as [ErrorCode, ...ErrorCode[]]),
    message: z.string(),
    details: z.array(errorDetailSchema).optional(),
    requestId: z.string().optional(),
  }),
});

export type ErrorEnvelope = z.infer<typeof errorEnvelopeSchema>;
