import { z } from 'zod';

/**
 * Central catalog of API error codes — see specs/001-b2b-platform-foundation/contracts/README.md.
 *
 * Every non-2xx response SHOULD use one of these codes. The list grows as modules are added;
 * new codes MUST be screaming-snake-case and documented in the relevant contract file.
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL: 'INTERNAL',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',

  // Catalog
  FILTER_NOT_ALLOWED: 'FILTER_NOT_ALLOWED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  PRODUCT_DELETE_BLOCKED: 'PRODUCT_DELETE_BLOCKED',
  SKU_ALREADY_EXISTS: 'SKU_ALREADY_EXISTS',
  VARIANT_COMBINATION_EXISTS: 'VARIANT_COMBINATION_EXISTS',
  VARIANT_AXIS_MISSING: 'VARIANT_AXIS_MISSING',
  ATTRIBUTE_VALUE_REJECTED: 'ATTRIBUTE_VALUE_REJECTED',
  FIELD_IMMUTABLE: 'FIELD_IMMUTABLE',

  // Catalog 002 — Attribute Sets
  ATTRIBUTE_SET_CODE_TAKEN: 'ATTRIBUTE_SET_CODE_TAKEN',
  ATTRIBUTE_SET_IN_USE: 'ATTRIBUTE_SET_IN_USE',
  SYSTEM_ATTRIBUTE_SET_IMMUTABLE: 'SYSTEM_ATTRIBUTE_SET_IMMUTABLE',
  ATTRIBUTE_SET_NOT_FOUND: 'ATTRIBUTE_SET_NOT_FOUND',
  ATTRIBUTE_NOT_FOUND: 'ATTRIBUTE_NOT_FOUND',

  // Catalog 002 — Gallery + Attachments (US3)
  GALLERY_LABEL_ALREADY_TAKEN: 'GALLERY_LABEL_ALREADY_TAKEN',
  GALLERY_LABEL_LIMIT_EXCEEDED: 'GALLERY_LABEL_LIMIT_EXCEEDED',
  ASSET_KIND_NOT_SUPPORTED: 'ASSET_KIND_NOT_SUPPORTED',
  ATTACHMENT_TYPE_IN_USE: 'ATTACHMENT_TYPE_IN_USE',
  ATTACHMENT_TYPE_CODE_TAKEN: 'ATTACHMENT_TYPE_CODE_TAKEN',
  ATTACHMENT_TYPE_NOT_FOUND: 'ATTACHMENT_TYPE_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  GALLERY_ITEM_NOT_FOUND: 'GALLERY_ITEM_NOT_FOUND',

  // Catalog 002 — Product Links (US4)
  SELF_LINK_NOT_ALLOWED: 'SELF_LINK_NOT_ALLOWED',
  LINK_ALREADY_EXISTS: 'LINK_ALREADY_EXISTS',
  TARGET_PRODUCT_NOT_FOUND: 'TARGET_PRODUCT_NOT_FOUND',
  PRODUCT_LINK_NOT_FOUND: 'PRODUCT_LINK_NOT_FOUND',

  // Catalog 002 — Grouped/Bundle/Virtual composite products (US5)
  PRODUCT_TYPE_MISMATCH: 'PRODUCT_TYPE_MISMATCH',
  NESTED_COMPOSITE_NOT_ALLOWED: 'NESTED_COMPOSITE_NOT_ALLOWED',
  INVALID_QUANTITY_RANGE: 'INVALID_QUANTITY_RANGE',
  OPTION_ALREADY_EXISTS: 'OPTION_ALREADY_EXISTS',
  GROUPED_ITEM_NOT_FOUND: 'GROUPED_ITEM_NOT_FOUND',
  BUNDLE_SLOT_NOT_FOUND: 'BUNDLE_SLOT_NOT_FOUND',
  BUNDLE_SLOT_OPTION_NOT_FOUND: 'BUNDLE_SLOT_OPTION_NOT_FOUND',
  MIN_NOT_MET: 'MIN_NOT_MET',
  MAX_EXCEEDED: 'MAX_EXCEEDED',
  UNKNOWN_OPTION: 'UNKNOWN_OPTION',

  // Quote Requests (RFQ)
  RFQ_NOT_DRAFT: 'RFQ_NOT_DRAFT',
  RFQ_EMPTY: 'RFQ_EMPTY',
  RFQ_NOT_QUOTED: 'RFQ_NOT_QUOTED',
  RFQ_NOT_ACCEPTED: 'RFQ_NOT_ACCEPTED',
  RFQ_NOT_NEW: 'RFQ_NOT_NEW',
  RFQ_ALREADY_CLAIMED: 'RFQ_ALREADY_CLAIMED',
  RFQ_EXPIRED: 'RFQ_EXPIRED',
  QUOTE_INCOMPLETE: 'QUOTE_INCOMPLETE',
  QUOTE_VALIDITY_ENDED: 'QUOTE_VALIDITY_ENDED',

  // Organizations / customer accounts
  ORGANIZATION_TAX_ID_EXISTS: 'ORGANIZATION_TAX_ID_EXISTS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_ALREADY_IN_ORGANIZATION: 'EMAIL_ALREADY_IN_ORGANIZATION',
  EMAIL_BELONGS_TO_ANOTHER_ORGANIZATION: 'EMAIL_BELONGS_TO_ANOTHER_ORGANIZATION',
  TERMS_VERSION_STALE: 'TERMS_VERSION_STALE',
  TOKEN_INVALID_OR_EXPIRED: 'TOKEN_INVALID_OR_EXPIRED',
  // Wrong email/password on login. A code distinct from the generic
  // UNAUTHORIZED ("authentication is required") guard so the storefront can
  // surface an actionable "invalid email or password — try again" message
  // instead of the opaque guard string (mirrors ACCOUNT_BLOCKED).
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_REQUIRED_BY_ROLE: 'TWO_FACTOR_REQUIRED_BY_ROLE',
  CANNOT_REMOVE_LAST_ADMIN: 'CANNOT_REMOVE_LAST_ADMIN',
  CANNOT_DEMOTE_LAST_ADMIN: 'CANNOT_DEMOTE_LAST_ADMIN',
  CANNOT_REVOKE_LAST_ADMIN_INVITE: 'CANNOT_REVOKE_LAST_ADMIN_INVITE',
  ADDRESS_IN_USE: 'ADDRESS_IN_USE',
  ADDRESS_NOT_OWNED: 'ADDRESS_NOT_OWNED',

  // Customers (040)
  REGISTRATION_REQUIRES_ORGANIZATION: 'REGISTRATION_REQUIRES_ORGANIZATION',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ADDRESS_NOT_FOUND: 'CUSTOMER_ADDRESS_NOT_FOUND',
  CUSTOMER_ALREADY_DELETED: 'CUSTOMER_ALREADY_DELETED',
  CUSTOMER_NOT_DELETED: 'CUSTOMER_NOT_DELETED',
  CUSTOMER_RESTORE_WINDOW_ELAPSED: 'CUSTOMER_RESTORE_WINDOW_ELAPSED',
  ORG_OWNER_DEPLETION: 'ORG_OWNER_DEPLETION',

  // Orders + Carts (feature 027)
  CART_EMPTY: 'CART_EMPTY',
  CART_LINE_CAP_EXCEEDED: 'CART_LINE_CAP_EXCEEDED',
  CART_COUPON_REJECTED: 'CART_COUPON_REJECTED',
  STOCK_UNAVAILABLE: 'STOCK_UNAVAILABLE',
  PROMOTION_INVALID: 'PROMOTION_INVALID',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  INVOICE_NOT_READY: 'INVOICE_NOT_READY',
  INVALID_TRANSITION: 'INVALID_TRANSITION',

  // Credit Limit
  CREDIT_LIMIT_NOT_GRANTED: 'CREDIT_LIMIT_NOT_GRANTED',
  CREDIT_LIMIT_ALREADY_GRANTED: 'CREDIT_LIMIT_ALREADY_GRANTED',
  LIMIT_INSUFFICIENT: 'LIMIT_INSUFFICIENT',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  ADJUSTMENT_BELOW_ACTIVE: 'ADJUSTMENT_BELOW_ACTIVE',
  ACTIVE_RESERVATIONS_EXIST: 'ACTIVE_RESERVATIONS_EXIST',
  ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
  PRODUCT_IN_STOCK: 'PRODUCT_IN_STOCK',

  // API keys / webhooks / integrations
  API_KEY_OUT_OF_SCOPE: 'API_KEY_OUT_OF_SCOPE',
  WEBHOOK_DELIVERY_NOT_REPLAYABLE: 'WEBHOOK_DELIVERY_NOT_REPLAYABLE',

  // Admin users / roles
  ADMIN_ROLE_CODE_TAKEN: 'ADMIN_ROLE_CODE_TAKEN',
  ADMIN_ROLE_IN_USE: 'ADMIN_ROLE_IN_USE',

  // Settings (feature 004)
  SETTING_NOT_REGISTERED: 'SETTING_NOT_REGISTERED',
  SETTING_OUT_OF_SCOPE_FOR_CHANNEL: 'SETTING_OUT_OF_SCOPE_FOR_CHANNEL',
  SETTING_VALUE_SHAPE_MISMATCH: 'SETTING_VALUE_SHAPE_MISMATCH',
  SETTING_EMPTY_SUBSET: 'SETTING_EMPTY_SUBSET',
  SETTING_GROUP_PROTECTED: 'SETTING_GROUP_PROTECTED',
  SETTING_GROUP_NOT_FOUND: 'SETTING_GROUP_NOT_FOUND',
  SETTING_CODE_CONFLICT: 'SETTING_CODE_CONFLICT',
  SETTING_GROUP_CODE_CONFLICT: 'SETTING_GROUP_CODE_CONFLICT',
  SETTING_BREAKING_CHANGE_REJECTED: 'SETTING_BREAKING_CHANGE_REJECTED',

  // Search (feature 006)
  QUERY_TOO_SHORT: 'QUERY_TOO_SHORT',
  QUERY_TOO_LONG: 'QUERY_TOO_LONG',
  LIMIT_OUT_OF_RANGE: 'LIMIT_OUT_OF_RANGE',
  SEARCH_BACKEND_UNAVAILABLE: 'SEARCH_BACKEND_UNAVAILABLE',
  PHRASE_REQUIRED: 'PHRASE_REQUIRED',
  PHRASE_TOO_LONG: 'PHRASE_TOO_LONG',
  RESULT_COUNT_INVALID: 'RESULT_COUNT_INVALID',
  LLM_CONFIG_INCOMPLETE: 'LLM_CONFIG_INCOMPLETE',

  // Sales Channels (feature 005)
  UNKNOWN_SALES_CHANNEL: 'UNKNOWN_SALES_CHANNEL',
  INACTIVE_SALES_CHANNEL: 'INACTIVE_SALES_CHANNEL',
  MISSING_SALES_CHANNEL_CONTEXT: 'MISSING_SALES_CHANNEL_CONTEXT',
  DUPLICATE_SALES_CHANNEL_CODE: 'DUPLICATE_SALES_CHANNEL_CODE',
  UNKNOWN_LANGUAGE_CODE: 'UNKNOWN_LANGUAGE_CODE',
  UNKNOWN_CURRENCY_CODE: 'UNKNOWN_CURRENCY_CODE',
  CANNOT_MODIFY_SYSTEM_DEFAULT: 'CANNOT_MODIFY_SYSTEM_DEFAULT',
  SALES_CHANNEL_HAS_ATTRIBUTIONS: 'SALES_CHANNEL_HAS_ATTRIBUTIONS',
  ENTITY_WOULD_HAVE_ZERO_CHANNELS: 'ENTITY_WOULD_HAVE_ZERO_CHANNELS',
  STALE_SALES_CHANNEL_WRITE: 'STALE_SALES_CHANNEL_WRITE',
  SALES_CHANNEL_ATTRIBUTION_IMMUTABLE: 'SALES_CHANNEL_ATTRIBUTION_IMMUTABLE',

  // Compare (feature 007)
  COMPARISON_FULL: 'COMPARISON_FULL',
  COMPARISON_NOT_FOUND: 'COMPARISON_NOT_FOUND',
  COMPARISON_EMPTY: 'COMPARISON_EMPTY',
  PRODUCT_NOT_IN_COMPARISON: 'PRODUCT_NOT_IN_COMPARISON',
  PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',

  // Inventory (feature 010 — multi-warehouse)
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  WAREHOUSE_CODE_TAKEN: 'WAREHOUSE_CODE_TAKEN',
  WAREHOUSE_INVALID_CODE: 'WAREHOUSE_INVALID_CODE',
  WAREHOUSE_CANNOT_DELETE_DEFAULT: 'WAREHOUSE_CANNOT_DELETE_DEFAULT',
  WAREHOUSE_IS_DEFAULT_FOR_CHANNELS: 'WAREHOUSE_IS_DEFAULT_FOR_CHANNELS',
  WAREHOUSE_HAS_STOCK: 'WAREHOUSE_HAS_STOCK',
  CHANNEL_NO_WAREHOUSES: 'CHANNEL_NO_WAREHOUSES',
  CHANNEL_WAREHOUSE_NOT_FOUND: 'CHANNEL_WAREHOUSE_NOT_FOUND',
  STOCK_LEVEL_NOT_FOUND: 'STOCK_LEVEL_NOT_FOUND',
  THRESHOLDS_INVALID: 'THRESHOLDS_INVALID',
  PRODUCT_UNMANAGED_STOCK: 'PRODUCT_UNMANAGED_STOCK',
  AVAILABILITY_NOTIFICATION_NOT_FOUND: 'AVAILABILITY_NOTIFICATION_NOT_FOUND',
  STOCK_IMPORT_INVALID_FILE: 'STOCK_IMPORT_INVALID_FILE',

  // Assets Library (feature 013)
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_REFERENCED: 'ASSET_REFERENCED',
  ASSET_FOLDER_NOT_FOUND: 'ASSET_FOLDER_NOT_FOUND',
  ASSET_FOLDER_NOT_EMPTY: 'ASSET_FOLDER_NOT_EMPTY',
  ASSET_FOLDER_NAME_CONFLICT: 'ASSET_FOLDER_NAME_CONFLICT',
  ASSET_FOLDER_CYCLE: 'ASSET_FOLDER_CYCLE',
  ASSET_UPLOAD_NO_FILE: 'ASSET_UPLOAD_NO_FILE',
  ASSET_UPLOAD_TYPE_NOT_ALLOWED: 'ASSET_UPLOAD_TYPE_NOT_ALLOWED',
  ASSET_UPLOAD_TOO_LARGE: 'ASSET_UPLOAD_TOO_LARGE',
  ASSET_STORAGE_UNAVAILABLE: 'ASSET_STORAGE_UNAVAILABLE',
  ASSET_STORAGE_MISCONFIGURED: 'ASSET_STORAGE_MISCONFIGURED',
  ASSET_LEGACY_LOCATOR_CANNOT_HARDEN: 'ASSET_LEGACY_LOCATOR_CANNOT_HARDEN',
  ASSET_FILE_MISSING: 'ASSET_FILE_MISSING',
  ASSET_GONE: 'ASSET_GONE',
  ASSET_ACCESS_DENIED: 'ASSET_ACCESS_DENIED',

  // CMS (feature 014)
  CMS_PAGE_NOT_FOUND: 'CMS_PAGE_NOT_FOUND',
  CMS_BLOCK_NOT_FOUND: 'CMS_BLOCK_NOT_FOUND',
  CMS_TEMPLATE_NOT_FOUND: 'CMS_TEMPLATE_NOT_FOUND',
  CMS_HOOK_NOT_FOUND: 'CMS_HOOK_NOT_FOUND',
  CMS_SLUG_CONFLICT: 'CMS_SLUG_CONFLICT',
  CMS_CODE_CONFLICT: 'CMS_CODE_CONFLICT',
  CMS_REFERENCED: 'CMS_REFERENCED',
  CMS_HOOK_SYSTEM_PROTECTED: 'CMS_HOOK_SYSTEM_PROTECTED',
  CMS_LANGUAGE_NOT_IN_CHANNEL_SCOPE: 'CMS_LANGUAGE_NOT_IN_CHANNEL_SCOPE',
  CMS_SCHEMA_UPGRADE_FAILED: 'CMS_SCHEMA_UPGRADE_FAILED',

  // Megamenu (feature 015)
  MEGAMENU_NOT_FOUND: 'MEGAMENU_NOT_FOUND',
  MEGAMENU_HAS_ACTIVE_BINDINGS: 'MEGAMENU_HAS_ACTIVE_BINDINGS',
  MEGAMENU_EMPTY_TREE: 'MEGAMENU_EMPTY_TREE',
  MEGAMENU_BINDING_NOT_FOUND: 'MEGAMENU_BINDING_NOT_FOUND',
  MEGAMENU_BINDING_ALREADY_EXISTS: 'MEGAMENU_BINDING_ALREADY_EXISTS',
  MEGAMENU_LANGUAGE_NOT_IN_CHANNEL_SCOPE: 'MEGAMENU_LANGUAGE_NOT_IN_CHANNEL_SCOPE',
  MEGAMENU_TARGET_OUT_OF_SCOPE: 'MEGAMENU_TARGET_OUT_OF_SCOPE',
  MEGAMENU_ASSET_KIND_MISMATCH: 'MEGAMENU_ASSET_KIND_MISMATCH',
  MEGAMENU_REFERENCED: 'MEGAMENU_REFERENCED',
  MEGAMENU_DEPTH_EXCEEDED: 'MEGAMENU_DEPTH_EXCEEDED',

  // Blog (feature 016)
  BLOG_SLUG_INVALID: 'BLOG_SLUG_INVALID',
  BLOG_SLUG_TAKEN: 'BLOG_SLUG_TAKEN',
  BLOG_POST_NOT_FOUND: 'BLOG_POST_NOT_FOUND',
  BLOG_POST_NO_CHANNEL: 'BLOG_POST_NO_CHANNEL',
  BLOG_POST_NO_LANGUAGE: 'BLOG_POST_NO_LANGUAGE',
  BLOG_CATEGORY_NOT_FOUND: 'BLOG_CATEGORY_NOT_FOUND',
  BLOG_CATEGORY_NO_CHANNEL: 'BLOG_CATEGORY_NO_CHANNEL',
  BLOG_CATEGORY_CYCLE: 'BLOG_CATEGORY_CYCLE',
  BLOG_CATEGORY_PROTECTED: 'BLOG_CATEGORY_PROTECTED',
  BLOG_CATEGORY_IN_USE: 'BLOG_CATEGORY_IN_USE',
  BLOG_CATEGORY_HAS_CHILDREN: 'BLOG_CATEGORY_HAS_CHILDREN',
  BLOG_TAG_NOT_FOUND: 'BLOG_TAG_NOT_FOUND',
  BLOG_TAG_CODE_TAKEN: 'BLOG_TAG_CODE_TAKEN',
  BLOG_TAG_IN_USE: 'BLOG_TAG_IN_USE',
  BLOG_URL_PREFIX_INVALID: 'BLOG_URL_PREFIX_INVALID',
  BLOG_URL_PREFIX_RESERVED: 'BLOG_URL_PREFIX_RESERVED',
  BLOG_DISABLED: 'BLOG_DISABLED',
  BLOG_ASSET_KIND_MISMATCH: 'BLOG_ASSET_KIND_MISMATCH',
  BLOG_RELATED_POST_SELF_REFERENCE: 'BLOG_RELATED_POST_SELF_REFERENCE',

  // Admin (feature 016 — extends 003)
  ADMIN_ROLE_PROTECTED: 'ADMIN_ROLE_PROTECTED',

  // Dictionary (feature 017)
  DICTIONARY_ENTRY_NOT_FOUND: 'DICTIONARY_ENTRY_NOT_FOUND',
  DICTIONARY_ENTRY_INACTIVE: 'DICTIONARY_ENTRY_INACTIVE',
  DICTIONARY_ENTRY_HAS_DEPENDENTS: 'DICTIONARY_ENTRY_HAS_DEPENDENTS',
  DICTIONARY_LAST_ACTIVE_ENTRY: 'DICTIONARY_LAST_ACTIVE_ENTRY',
  DICTIONARY_DEFAULT_CANNOT_BE_DEACTIVATED: 'DICTIONARY_DEFAULT_CANNOT_BE_DEACTIVATED',
  DICTIONARY_FALLBACK_CYCLE: 'DICTIONARY_FALLBACK_CYCLE',
  DICTIONARY_CODE_IMMUTABLE: 'DICTIONARY_CODE_IMMUTABLE',
  DICTIONARY_TRANSLATION_LANGUAGE_INACTIVE: 'DICTIONARY_TRANSLATION_LANGUAGE_INACTIVE',

  // Module Lifecycle (feature 018)
  MODULE_DISABLED: 'MODULE_DISABLED',

  // Catalog (feature 022 — Products Bulk Edit)
  BULK_TOO_LARGE: 'BULK_TOO_LARGE',
  ATTRIBUTE_NOT_MASS_EDITABLE: 'ATTRIBUTE_NOT_MASS_EDITABLE',

  // Catalog (feature 033 — Products collection selection)
  SELECTION_TOO_LARGE: 'SELECTION_TOO_LARGE',

  // MFA (feature 042)
  MFA_INVALID_CODE: 'MFA_INVALID_CODE',
  MFA_INVALID_CHALLENGE: 'MFA_INVALID_CHALLENGE',
  MFA_TOO_MANY_ATTEMPTS: 'MFA_TOO_MANY_ATTEMPTS',
  MFA_WRONG_SURFACE: 'MFA_WRONG_SURFACE',
  MFA_ALREADY_ENROLLED: 'MFA_ALREADY_ENROLLED',
  MFA_NO_PENDING_ENROLMENT: 'MFA_NO_PENDING_ENROLMENT',
  MFA_NO_ACTIVE_ENROLMENT: 'MFA_NO_ACTIVE_ENROLMENT',
  MFA_REAUTH_REQUIRED: 'MFA_REAUTH_REQUIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const errorDetailSchema = z.object({
  path: z.string().describe('dot-path to the offending field inside the request body or query'),
  issue: z.string().describe('human-readable explanation of what failed'),
});

export const errorEnvelopeSchema = z.object({
  error: z.object({
    code: z.enum(Object.values(ERROR_CODES) as [ErrorCode, ...ErrorCode[]]),
    message: z.string(),
    // Two shapes: (a) the legacy Zod-style array of {path, issue}, used by
    // request-validation failures, and (b) a free-form object used by
    // domain errors that carry structured metadata (e.g. feature 022's
    // `BULK_TOO_LARGE` envelope carries `{ maxBatchSize, recommendedSplitInto }`).
    details: z.union([z.array(errorDetailSchema), z.record(z.string(), z.unknown())]).optional(),
    requestId: z.string().optional(),
  }),
});

export type ErrorEnvelope = z.infer<typeof errorEnvelopeSchema>;
