// Google Tag Manager module — feature 066 contract surface.
//
// Holds the per-channel setting codes, the container-ID shape, the closed
// event vocabulary shared by the storefront emitter / the backend ingest
// validator / the docs, the storefront config read model, and the server-side
// relay ingest request.
//
// The snake_case body the backend posts to the operator's server container is
// deliberately NOT modelled here: it is an external vendor's wire format,
// constructed in exactly one place and never parsed back, so it lives as a
// plain TypeScript interface in the module's `sgtm-client.ts` (research §R6).

import { z } from 'zod';

// ---------------------------------------------------------------------------
// (1) Setting codes (shared between manifest + services)
// ---------------------------------------------------------------------------

export const GOOGLE_TAG_MANAGER_SETTING_CODES = {
  ENABLED: 'google_tag_manager.enabled',
  CONTAINER_ID: 'google_tag_manager.container_id',
  REQUIRE_CONSENT: 'google_tag_manager.require_consent',
  SERVER_SIDE_ENABLED: 'google_tag_manager.server_side_enabled',
  SERVER_CONTAINER_URL: 'google_tag_manager.server_container_url',
  SERVER_INGEST_PATH: 'google_tag_manager.server_ingest_path',
} as const;

// ---------------------------------------------------------------------------
// (2) Container ID
// ---------------------------------------------------------------------------

/**
 * GTM container ID. Google issues `GTM-` plus 5-7 uppercase alphanumerics
 * today; the 4-10 window absorbs historical and future widths without
 * accepting free text. A `GT-…` Google tag id is deliberately not accepted —
 * it is not a container and would load nothing (research §R15).
 */
export const gtmContainerIdSchema = z
  .string()
  .regex(/^GTM-[A-Z0-9]{4,10}$/, 'Container ID must look like GTM-XXXXXXX');

// ---------------------------------------------------------------------------
// (3) The event vocabulary
// ---------------------------------------------------------------------------

/**
 * The closed allow-list of events the platform emits and may relay to a
 * server-side container. The ingest route rejects anything outside it, which is
 * what makes FR-024 structural rather than a matter of caller discipline.
 */
export const GTM_RELAY_ELIGIBLE_EVENTS = [
  'page_view',
  'view_search_results',
  'view_item',
  'add_to_cart',
  'add_to_quote_request',
  'add_to_shopping_list',
  'begin_checkout',
  'place_order_clicked',
  'purchase',
  'contact_form_submitted',
] as const;
export type GtmRelayEligibleEvent = (typeof GTM_RELAY_ELIGIBLE_EVENTS)[number];

/**
 * Events that depend on browser-only state (viewport, live DOM, wall-clock
 * dwell time) or are generated by the container itself. The platform gives them
 * no server-side path and no implementation at all: the GTM container stays
 * loaded in the browser even in server-side mode, so its own triggers keep
 * handling them (research §R5). Listed here for documentation and as the
 * negative test fixture for the ingest validator.
 */
export const GTM_CLIENT_ONLY_EVENTS = [
  'scroll',
  'click',
  'file_download',
  'form_start',
  'form_submit',
  'gtm.js',
  'gtm.dom',
  'gtm.load',
] as const;
export type GtmClientOnlyEvent = (typeof GTM_CLIENT_ONLY_EVENTS)[number];

/** An event name the platform is willing to relay. */
export const gtmEventNameSchema = z.enum(GTM_RELAY_ELIGIBLE_EVENTS);

// ---------------------------------------------------------------------------
// (4) Storefront — per-channel public config
// ---------------------------------------------------------------------------

export const gtmStorefrontConfigSchema = z.object({
  /** Master switch AND a valid container ID, resolved server-side. */
  enabled: z.boolean(),
  /** `null` when the channel is untracked (blank or malformed value). */
  containerId: z.string().nullable(),
  /** Drives the Consent Mode v2 default state and the shared consent gate. */
  requireConsent: z.boolean(),
  /**
   * True only when server-side tagging is on AND a server container URL is
   * configured. Drives the storefront dispatch switch; the container address
   * itself never leaves the backend.
   */
  serverSide: z.boolean(),
});
export type GtmStorefrontConfig = z.infer<typeof gtmStorefrontConfigSchema>;

/** Fully-off config — the shape every failure path degrades to. */
export const GTM_DISABLED_CONFIG: GtmStorefrontConfig = {
  enabled: false,
  containerId: null,
  requireConsent: true,
  serverSide: false,
};

// ---------------------------------------------------------------------------
// (5) Storefront — server-side relay ingest (producer)
// ---------------------------------------------------------------------------

export const gtmRelayEventSchema = z.object({
  name: gtmEventNameSchema,
  /**
   * Scalars only. `items[]` is serialised by the caller with `JSON.stringify`,
   * exactly as the storefront choke point already does for GA — which is also
   * why a file upload cannot be expressed here at all (FR-021).
   */
  params: z
    .record(z.string(), z.union([z.string(), z.number(), z.boolean()]))
    .default({}),
});
export type GtmRelayEvent = z.infer<typeof gtmRelayEventSchema>;

/** Page context as observed in the browser at emit time. */
export const gtmPageContextSchema = z.object({
  location: z.string().min(1).max(2048),
  referrer: z.string().max(2048).optional(),
  title: z.string().max(512).optional(),
  language: z.string().max(16).optional(),
});
export type GtmPageContext = z.infer<typeof gtmPageContextSchema>;

export const gtmCollectRequestSchema = z.object({
  clientId: z.string().min(1).max(128),
  consent: z.object({
    analyticsStorage: z.enum(['granted', 'denied']),
  }),
  page: gtmPageContextSchema,
  events: z.array(gtmRelayEventSchema).min(1).max(25),
});
export type GtmCollectRequest = z.infer<typeof gtmCollectRequestSchema>;
