// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// The entity registry `mikro-orm.config.ts` discovers through.
//
// Explicit classes rather than a glob: glob discovery needs a runtime dynamic
// `import()` of a `.ts` file, which Node's ESM loader cannot transform and which
// breaks under Vitest. Listing them side-steps that — and since feature 071's F2
// the list is a filesystem walk rather than 219 imports someone kept in sync by
// hand, so adding an entity is adding a file and removing a module is deleting
// its directory.
//
// Every class carrying the MikroORM entity decorator anywhere under `src/` is
// here, in path order. Detection is by that decorator, not by the
// `.entity.ts` suffix, because nothing enforces the suffix — and the decorator
// is deliberately not spelled out in this comment, so that a walk looking for
// it does not find its own output. A per-deployment overlay contributes no
// schema (D-106), so an entity under `src/apps/` is refused by the generator
// rather than registered for a table nothing creates. A **module package** is
// the opposite case and is here: its entities are named by a bare specifier
// derived from that package's own `exports` map (D-149), and they arrive as
// **one `entities` array** rather than as a class per name (D-168) — the same
// export `src/packages/package-runtime.ts` reads when that package is
// installed rather than linked, so the committed registry and the runtime
// loader now read one declaration instead of two.

import type { EntityClassLike } from '../packages/package-runtime.js';
import { AuditLogEntry } from '../kernel/audit/audit-log-entry.entity.js';
import { ModuleRegistration } from '../kernel/lifecycle/module-registration.entity.js';
import { SalesChannel } from '../kernel/sales-channels/sales-channel.entity.js';
import { SettingGroup } from '../kernel/settings/setting-group.entity.js';
import { SettingValue } from '../kernel/settings/setting-value.entity.js';
import { Setting } from '../kernel/settings/setting.entity.js';
import { TranslationBundle } from '../modules/_i18n/entities/translation-bundle.entity.js';
import { ModuleAction } from '../modules/admin_actions/entities/module-action.entity.js';
import { AdminRole } from '../modules/admin_roles/entities/admin-role.entity.js';
import { AdminUser } from '../modules/admin_users/entities/admin-user.entity.js';
import { AssetFolder } from '../modules/assets_library/entities/asset-folder.entity.js';
import { Asset } from '../modules/assets_library/entities/asset.entity.js';
import { Session } from '../modules/auth/entities/session.entity.js';
import { AutopayBlikAlias } from '../modules/autopay/entities/autopay-blik-alias.entity.js';
import { AutopayNotificationEvent } from '../modules/autopay/entities/autopay-notification-event.entity.js';
import { AutopayPaymentMethodOrgDisable } from '../modules/autopay/entities/autopay-payment-method-org-disable.entity.js';
import { AutopayPaymentMethodRule } from '../modules/autopay/entities/autopay-payment-method-rule.entity.js';
import { AutopaySavedCard } from '../modules/autopay/entities/autopay-saved-card.entity.js';
import { AutopayTransaction } from '../modules/autopay/entities/autopay-transaction.entity.js';
import { CartAuditEntry } from '../modules/carts/entities/cart-audit-entry.entity.js';
import { CartItem } from '../modules/carts/entities/cart-item.entity.js';
import { Cart } from '../modules/carts/entities/cart.entity.js';
import { AttachmentType } from '../modules/catalog/entities/attachment-type.entity.js';
import { AttributeSetAttribute } from '../modules/catalog/entities/attribute-set-attribute.entity.js';
import { AttributeSet } from '../modules/catalog/entities/attribute-set.entity.js';
import { BulkOperation } from '../modules/catalog/entities/bulk-operation.entity.js';
import { BundleSlotOption } from '../modules/catalog/entities/bundle-slot-option.entity.js';
import { BundleSlot } from '../modules/catalog/entities/bundle-slot.entity.js';
import { Category } from '../modules/catalog/entities/category.entity.js';
import { GalleryItemLabel } from '../modules/catalog/entities/gallery-item-label.entity.js';
import { GalleryItem } from '../modules/catalog/entities/gallery-item.entity.js';
import { GroupedItem } from '../modules/catalog/entities/grouped-item.entity.js';
import { ProductAttachment } from '../modules/catalog/entities/product-attachment.entity.js';
import { ProductAttribute } from '../modules/catalog/entities/product-attribute.entity.js';
import { ProductEditorPreference } from '../modules/catalog/entities/product-editor-preference.entity.js';
import { ProductLink } from '../modules/catalog/entities/product-link.entity.js';
import { ProductPackagingUnit } from '../modules/catalog/entities/product-packaging-unit.entity.js';
import { ProductValueOverride } from '../modules/catalog/entities/product-value-override.entity.js';
import { ProductVariant } from '../modules/catalog/entities/product-variant.entity.js';
import { Product } from '../modules/catalog/entities/product.entity.js';
import { ComparisonProduct } from '../modules/comparisons/entities/comparison-product.entity.js';
import { Comparison } from '../modules/comparisons/entities/comparison.entity.js';
import { CredentialConfiguration } from '../modules/credentials/entities/credential-configuration.entity.js';
import { CustomFieldDefinition } from '../modules/custom_fields/entities/custom-field-definition.entity.js';
import { CustomFieldOption } from '../modules/custom_fields/entities/custom-field-option.entity.js';
import { CustomerAccount } from '../modules/customer_accounts/entities/customer-account.entity.js';
import { CustomerGroup } from '../modules/customer_accounts/entities/customer-group.entity.js';
import { PasswordResetToken } from '../modules/customer_accounts/entities/password-reset-token.entity.js';
import { CustomerAddress } from '../modules/customers/entities/customer-address.entity.js';
import { Country } from '../modules/dictionaries/entities/country.entity.js';
import { DictionaryTranslation } from '../modules/dictionaries/entities/dictionary-translation.entity.js';
import { LanguageCountry } from '../modules/dictionaries/entities/language-country.entity.js';
import { EmailDelivery } from '../modules/email/entities/email-delivery.entity.js';
import { AvailabilityNotification } from '../modules/inventory/entities/availability-notification.entity.js';
import { InventoryThreshold } from '../modules/inventory/entities/inventory-threshold.entity.js';
import { ProductWarehouseLowStockThreshold } from '../modules/inventory/entities/product-warehouse-low-stock-threshold.entity.js';
import { StockAllocation } from '../modules/inventory/entities/stock-allocation.entity.js';
import { StockLevel } from '../modules/inventory/entities/stock-level.entity.js';
import { WarehouseChannelAssignment } from '../modules/inventory/entities/warehouse-channel-assignment.entity.js';
import { Warehouse } from '../modules/inventory/entities/warehouse.entity.js';
import { InvoiceLine } from '../modules/invoices/entities/invoice-line.entity.js';
import { InvoiceNumberCounter } from '../modules/invoices/entities/invoice-number-counter.entity.js';
import { InvoiceTemplate } from '../modules/invoices/entities/invoice-template.entity.js';
import { Invoice } from '../modules/invoices/entities/invoice.entity.js';
import { KsefCredential } from '../modules/ksef/entities/ksef-credential.entity.js';
import { KsefSubmission } from '../modules/ksef/entities/ksef-submission.entity.js';
import { MegamenuBinding } from '../modules/megamenu/entities/megamenu-binding.entity.js';
import { MegamenuItem } from '../modules/megamenu/entities/megamenu-item.entity.js';
import { Megamenu } from '../modules/megamenu/entities/megamenu.entity.js';
import { MetaCustomEventMapping } from '../modules/meta_ads/entities/meta-custom-event-mapping.entity.js';
import { OrderAppliedPromotion } from '../modules/orders/entities/order-applied-promotion.entity.js';
import { OrderComment } from '../modules/orders/entities/order-comment.entity.js';
import { OrderItem } from '../modules/orders/entities/order-item.entity.js';
import { OrderListSavedView } from '../modules/orders/entities/order-list-saved-view.entity.js';
import { OrderPlacementIntent } from '../modules/orders/entities/order-placement-intent.entity.js';
import { OrderStatusTransition } from '../modules/orders/entities/order-status-transition.entity.js';
import { OrderStatus } from '../modules/orders/entities/order-status.entity.js';
import { Order } from '../modules/orders/entities/order.entity.js';
import { EmailVerificationToken } from '../modules/organizations/entities/email-verification-token.entity.js';
import { OrganizationDeliveryMethodLink } from '../modules/organizations/entities/organization-delivery-method-link.entity.js';
import { OrganizationInvitation } from '../modules/organizations/entities/organization-invitation.entity.js';
import { OrganizationPaymentMethodLink } from '../modules/organizations/entities/organization-payment-method-link.entity.js';
import { OrganizationSalesRepAssignment } from '../modules/organizations/entities/organization-sales-rep-assignment.entity.js';
import { OrganizationTaxIdValidation } from '../modules/organizations/entities/organization-tax-id-validation.entity.js';
import { OrganizationWarehouseLink } from '../modules/organizations/entities/organization-warehouse-link.entity.js';
import { Organization } from '../modules/organizations/entities/organization.entity.js';
import { Payment } from '../modules/payments/entities/payment.entity.js';
import { PaypalPaymentMethodOrgDisable } from '../modules/paypal/entities/paypal-payment-method-org-disable.entity.js';
import { PaypalPaymentMethodRule } from '../modules/paypal/entities/paypal-payment-method-rule.entity.js';
import { PaypalTransaction } from '../modules/paypal/entities/paypal-transaction.entity.js';
import { PaypalWebhookEvent } from '../modules/paypal/entities/paypal-webhook-event.entity.js';
import { PayuBlikAlias } from '../modules/payu/entities/payu-blik-alias.entity.js';
import { PayuNotificationEvent } from '../modules/payu/entities/payu-notification-event.entity.js';
import { PayuOrder } from '../modules/payu/entities/payu-order.entity.js';
import { PayuPaymentMethodOrgDisable } from '../modules/payu/entities/payu-payment-method-org-disable.entity.js';
import { PayuPaymentMethodRule } from '../modules/payu/entities/payu-payment-method-rule.entity.js';
import { PayuSavedCard } from '../modules/payu/entities/payu-saved-card.entity.js';
import { ErgonodeAttributeMapping } from '../modules/pim_ergonode/entities/ergonode-attribute-mapping.entity.js';
import { ErgonodeCategoryMapping } from '../modules/pim_ergonode/entities/ergonode-category-mapping.entity.js';
import { ErgonodeConnection } from '../modules/pim_ergonode/entities/ergonode-connection.entity.js';
import { ErgonodeFieldProtection } from '../modules/pim_ergonode/entities/ergonode-field-protection.entity.js';
import { ErgonodeImportIssue } from '../modules/pim_ergonode/entities/ergonode-import-issue.entity.js';
import { ErgonodeImportRun } from '../modules/pim_ergonode/entities/ergonode-import-run.entity.js';
import { ErgonodeMediaLink } from '../modules/pim_ergonode/entities/ergonode-media-link.entity.js';
import { ErgonodePriceBinding } from '../modules/pim_ergonode/entities/ergonode-price-binding.entity.js';
import { ErgonodeProductLink } from '../modules/pim_ergonode/entities/ergonode-product-link.entity.js';
import { ErgonodeStreamCursor } from '../modules/pim_ergonode/entities/ergonode-stream-cursor.entity.js';
import { PriceDisplayModeOverride } from '../modules/price_lists/entities/price-display-mode-override.entity.js';
import { PriceListPriceBracket } from '../modules/price_lists/entities/price-list-price-bracket.entity.js';
import { PriceListProduct } from '../modules/price_lists/entities/price-list-product.entity.js';
import { PriceList } from '../modules/price_lists/entities/price-list.entity.js';
import { FeedArtefact } from '../modules/product_feeds/entities/feed-artefact.entity.js';
import { FeedDeliveryAttempt } from '../modules/product_feeds/entities/feed-delivery-attempt.entity.js';
import { FeedDelivery } from '../modules/product_feeds/entities/feed-delivery.entity.js';
import { FeedRunIssue } from '../modules/product_feeds/entities/feed-run-issue.entity.js';
import { FeedRun } from '../modules/product_feeds/entities/feed-run.entity.js';
import { FeedTaxonomyCheck } from '../modules/product_feeds/entities/feed-taxonomy-check.entity.js';
import { FeedTaxonomyMapping } from '../modules/product_feeds/entities/feed-taxonomy-mapping.entity.js';
import { FeedTaxonomyNode } from '../modules/product_feeds/entities/feed-taxonomy-node.entity.js';
import { FeedTaxonomy } from '../modules/product_feeds/entities/feed-taxonomy.entity.js';
import { FeedTemplateField } from '../modules/product_feeds/entities/feed-template-field.entity.js';
import { FeedTemplate } from '../modules/product_feeds/entities/feed-template.entity.js';
import { ProductFeed } from '../modules/product_feeds/entities/product-feed.entity.js';
import { QuickOrderDefaultPreference } from '../modules/quick_order/entities/quick-order-default-preference.entity.js';
import { SearchPhraseRecord } from '../modules/search/entities/search-phrase-record.entity.js';
import { StripeCustomer } from '../modules/stripe/entities/stripe-customer.entity.js';
import { StripePaymentIntent } from '../modules/stripe/entities/stripe-payment-intent.entity.js';
import { StripePaymentMethodOrgDisable } from '../modules/stripe/entities/stripe-payment-method-org-disable.entity.js';
import { StripePaymentMethodRule } from '../modules/stripe/entities/stripe-payment-method-rule.entity.js';
import { StripeSavedCard } from '../modules/stripe/entities/stripe-saved-card.entity.js';
import { StripeWebhookEvent } from '../modules/stripe/entities/stripe-webhook-event.entity.js';
import { Tax } from '../modules/taxes/entities/tax.entity.js';
import { TpayBlikAlias } from '../modules/tpay/entities/tpay-blik-alias.entity.js';
import { TpayNotificationEvent } from '../modules/tpay/entities/tpay-notification-event.entity.js';
import { TpayPaymentMethodOrgDisable } from '../modules/tpay/entities/tpay-payment-method-org-disable.entity.js';
import { TpayPaymentMethodRule } from '../modules/tpay/entities/tpay-payment-method-rule.entity.js';
import { TpaySavedCard } from '../modules/tpay/entities/tpay-saved-card.entity.js';
import { TpayTransaction } from '../modules/tpay/entities/tpay-transaction.entity.js';
import { entities as addressesEntities } from '@endora-commerce/mod-addresses/backend';
import { entities as adminNotificationsEntities } from '@endora-commerce/mod-admin-notifications/backend';
import { entities as analyticsEntities } from '@endora-commerce/mod-analytics/backend';
import { entities as apiKeysEntities } from '@endora-commerce/mod-api-keys/backend';
import { entities as blogEntities } from '@endora-commerce/mod-blog/backend';
import { entities as cmsEntities } from '@endora-commerce/mod-cms/backend';
import { entities as promotionsEntities } from '@endora-commerce/mod-promotions/backend';
import { entities as creditLimitsEntities } from '@endora-commerce/mod-credit-limits/backend';
import { entities as currenciesEntities } from '@endora-commerce/mod-currencies/backend';
import { entities as deliveryMethodsEntities } from '@endora-commerce/mod-delivery-methods/backend';
import { entities as transactionalEmailsEntities } from '@endora-commerce/mod-transactional-emails/backend';
import { entities as googleAnalyticsEntities } from '@endora-commerce/mod-google-analytics/backend';
import { entities as languagesEntities } from '@endora-commerce/mod-languages/backend';
import { entities as linkedinAdsEntities } from '@endora-commerce/mod-linkedin-ads/backend';
import { entities as mfaEntities } from '@endora-commerce/mod-mfa/backend';
import { entities as newsletterEntities } from '@endora-commerce/mod-newsletter/backend';
import { entities as paymentMethodsEntities } from '@endora-commerce/mod-payment-methods/backend';
import { entities as promptActionsEntities } from '@endora-commerce/mod-prompt-actions/backend';
import { entities as pwaEntities } from '@endora-commerce/mod-pwa/backend';
import { entities as quoteRequestsEntities } from '@endora-commerce/mod-quote-requests/backend';
import { entities as returnsEntities } from '@endora-commerce/mod-returns/backend';
import { entities as seoEntities } from '@endora-commerce/mod-seo/backend';
import { entities as shipmentsEntities } from '@endora-commerce/mod-shipments/backend';
import { entities as shoppingListsEntities } from '@endora-commerce/mod-shopping-lists/backend';
import { entities as webhooksEntities } from '@endora-commerce/mod-webhooks/backend';

export const ALL_ENTITIES = [
  AuditLogEntry,
  ModuleRegistration,
  SalesChannel,
  SettingGroup,
  SettingValue,
  Setting,
  TranslationBundle,
  ModuleAction,
  AdminRole,
  AdminUser,
  AssetFolder,
  Asset,
  Session,
  AutopayBlikAlias,
  AutopayNotificationEvent,
  AutopayPaymentMethodOrgDisable,
  AutopayPaymentMethodRule,
  AutopaySavedCard,
  AutopayTransaction,
  CartAuditEntry,
  CartItem,
  Cart,
  AttachmentType,
  AttributeSetAttribute,
  AttributeSet,
  BulkOperation,
  BundleSlotOption,
  BundleSlot,
  Category,
  GalleryItemLabel,
  GalleryItem,
  GroupedItem,
  ProductAttachment,
  ProductAttribute,
  ProductEditorPreference,
  ProductLink,
  ProductPackagingUnit,
  ProductValueOverride,
  ProductVariant,
  Product,
  ComparisonProduct,
  Comparison,
  CredentialConfiguration,
  CustomFieldDefinition,
  CustomFieldOption,
  CustomerAccount,
  CustomerGroup,
  PasswordResetToken,
  CustomerAddress,
  Country,
  DictionaryTranslation,
  LanguageCountry,
  EmailDelivery,
  AvailabilityNotification,
  InventoryThreshold,
  ProductWarehouseLowStockThreshold,
  StockAllocation,
  StockLevel,
  WarehouseChannelAssignment,
  Warehouse,
  InvoiceLine,
  InvoiceNumberCounter,
  InvoiceTemplate,
  Invoice,
  KsefCredential,
  KsefSubmission,
  MegamenuBinding,
  MegamenuItem,
  Megamenu,
  MetaCustomEventMapping,
  OrderAppliedPromotion,
  OrderComment,
  OrderItem,
  OrderListSavedView,
  OrderPlacementIntent,
  OrderStatusTransition,
  OrderStatus,
  Order,
  EmailVerificationToken,
  OrganizationDeliveryMethodLink,
  OrganizationInvitation,
  OrganizationPaymentMethodLink,
  OrganizationSalesRepAssignment,
  OrganizationTaxIdValidation,
  OrganizationWarehouseLink,
  Organization,
  Payment,
  PaypalPaymentMethodOrgDisable,
  PaypalPaymentMethodRule,
  PaypalTransaction,
  PaypalWebhookEvent,
  PayuBlikAlias,
  PayuNotificationEvent,
  PayuOrder,
  PayuPaymentMethodOrgDisable,
  PayuPaymentMethodRule,
  PayuSavedCard,
  ErgonodeAttributeMapping,
  ErgonodeCategoryMapping,
  ErgonodeConnection,
  ErgonodeFieldProtection,
  ErgonodeImportIssue,
  ErgonodeImportRun,
  ErgonodeMediaLink,
  ErgonodePriceBinding,
  ErgonodeProductLink,
  ErgonodeStreamCursor,
  PriceDisplayModeOverride,
  PriceListPriceBracket,
  PriceListProduct,
  PriceList,
  FeedArtefact,
  FeedDeliveryAttempt,
  FeedDelivery,
  FeedRunIssue,
  FeedRun,
  FeedTaxonomyCheck,
  FeedTaxonomyMapping,
  FeedTaxonomyNode,
  FeedTaxonomy,
  FeedTemplateField,
  FeedTemplate,
  ProductFeed,
  QuickOrderDefaultPreference,
  SearchPhraseRecord,
  StripeCustomer,
  StripePaymentIntent,
  StripePaymentMethodOrgDisable,
  StripePaymentMethodRule,
  StripeSavedCard,
  StripeWebhookEvent,
  Tax,
  TpayBlikAlias,
  TpayNotificationEvent,
  TpayPaymentMethodOrgDisable,
  TpayPaymentMethodRule,
  TpaySavedCard,
  TpayTransaction,
  ...(addressesEntities as readonly EntityClassLike[]),
  ...(adminNotificationsEntities as readonly EntityClassLike[]),
  ...(analyticsEntities as readonly EntityClassLike[]),
  ...(apiKeysEntities as readonly EntityClassLike[]),
  ...(blogEntities as readonly EntityClassLike[]),
  ...(cmsEntities as readonly EntityClassLike[]),
  ...(promotionsEntities as readonly EntityClassLike[]),
  ...(creditLimitsEntities as readonly EntityClassLike[]),
  ...(currenciesEntities as readonly EntityClassLike[]),
  ...(deliveryMethodsEntities as readonly EntityClassLike[]),
  ...(transactionalEmailsEntities as readonly EntityClassLike[]),
  ...(googleAnalyticsEntities as readonly EntityClassLike[]),
  ...(languagesEntities as readonly EntityClassLike[]),
  ...(linkedinAdsEntities as readonly EntityClassLike[]),
  ...(mfaEntities as readonly EntityClassLike[]),
  ...(newsletterEntities as readonly EntityClassLike[]),
  ...(paymentMethodsEntities as readonly EntityClassLike[]),
  ...(promptActionsEntities as readonly EntityClassLike[]),
  ...(pwaEntities as readonly EntityClassLike[]),
  ...(quoteRequestsEntities as readonly EntityClassLike[]),
  ...(returnsEntities as readonly EntityClassLike[]),
  ...(seoEntities as readonly EntityClassLike[]),
  ...(shipmentsEntities as readonly EntityClassLike[]),
  ...(shoppingListsEntities as readonly EntityClassLike[]),
  ...(webhooksEntities as readonly EntityClassLike[]),
] as const;
