// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// The single registration point for every migration in the repository.
//
// Static imports only — no glob, no dynamic `import()`: Node's ESM loader
// cannot transform `.ts` at runtime and it breaks under Vitest (the same reason
// ./entities-registry.generated.ts exists). A migration that is not registered
// here does not run; since feature 071's F2 registration is a filesystem walk
// rather than a line someone remembers to paste, and the round-trip guard in
// test/unit/db/migrations-registry.test.ts fails the build on a stale artefact.
//
// **Declaration order has no effect on execution order.** That is computed by
// migration-order.ts: the frozen historical prefix marked by BASELINE_THROUGH,
// then module by module in a topological order of the manifest dependency
// graph, each module's migrations contiguous and ascending by timestamp. A
// timestamp orders a module's own migrations and nothing else. Entries below
// are grouped by owning module purely so the diff reads; never "fix" an
// ordering surprise by moving a line, and there is nothing to move —
// regenerating restores it. Fix the manifest `dependencies` instead; a
// timestamp cannot fix a cross-module position.
//
// The `moduleId` is load-bearing beyond ordering: a hard uninstall reverts
// exactly the migrations registered under the module being removed
// (`_lifecycle/services/orchestrator.ts`). It is the directory the file lives
// in, which for kernel-owned tables is `core` —
// test/unit/db/kernel-migration-ownership.test.ts enforces that the tables a
// migration writes to agree with it.
//
// Add one with: pnpm --filter backend run migration:new -- --module <id> --name <slug>

import type { MigrationClass, MigrationRegistryEntry } from '@endora-commerce/platform/db';

// ── _i18n ───────────────────────────────────────────────────────────────────
import { Migration20260507T091405I18nAdminI18nInit } from '@endora-commerce/mod-i18n/migrations';

// ── admin_actions ───────────────────────────────────────────────────────────
import { Migration20260507T142354AdminActionsInit } from '@endora-commerce/mod-admin-actions/migrations';

// ── admin_notifications ─────────────────────────────────────────────────────
import { Migration20260611T140350AdminNotificationsInit } from '@endora-commerce/mod-admin-notifications/migrations';

// ── admin_users ─────────────────────────────────────────────────────────────
import { Migration20260425T053028AdminUsersInit } from '@endora-commerce/mod-admin-users/migrations';
import { Migration20260819T155150AdminUsersFoldEmailCase } from '@endora-commerce/mod-admin-users/migrations';
import { Migration20260825T124801AdminUsersDropLegacyTwoFactorSecret } from '@endora-commerce/mod-admin-users/migrations';

// ── analytics ───────────────────────────────────────────────────────────────
import { Migration20260425T143139AnalyticsInit } from '@endora-commerce/mod-analytics/migrations';
import { Migration20260912T125655AnalyticsEventsTenantScopeIndexes } from '@endora-commerce/mod-analytics/migrations';

// ── api_keys ────────────────────────────────────────────────────────────────
import { Migration20260724T173916ApiKeysDistributorBinding } from '@endora-commerce/mod-api-keys/migrations';

// ── assets_library ──────────────────────────────────────────────────────────
import { Migration20260505T102206AssetsLibraryInit } from '@endora-commerce/mod-assets-library/migrations';

// ── autopay ─────────────────────────────────────────────────────────────────
import { Migration20260803T065409AutopayInit } from '@endora-commerce/mod-autopay/migrations';
import { Migration20260816T053835AutopaySeedPaymentMethods } from '@endora-commerce/mod-autopay/migrations';
import { Migration20260821T084925AutopayFailureStatusOnHold } from '@endora-commerce/mod-autopay/migrations';

// ── blog ────────────────────────────────────────────────────────────────────
import { Migration20260506T081055BlogInit } from '@endora-commerce/mod-blog/migrations';
import { Migration20260903T101744BlogNamespaceBlockNames } from '@endora-commerce/mod-blog/migrations';

// ── carts ───────────────────────────────────────────────────────────────────
import { Migration20260611T140352CartsConsolidation } from '@endora-commerce/mod-carts/migrations';
import { Migration20260611T140413CartsCartItemPackaging } from '@endora-commerce/mod-carts/migrations';
import { Migration20260818T081253CartsCartCompletedOrderFk } from '@endora-commerce/mod-carts/migrations';
import { Migration20260830T112911CartsOrganizationAttributionCheck } from '@endora-commerce/mod-carts/migrations';

// ── catalog ─────────────────────────────────────────────────────────────────
import { Migration20260429T064146CatalogAttributeSetsInit } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260429T070004CatalogProductAttributeExtensions } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260429T102322CatalogProductTypeAndVirtualFields } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260429T111839CatalogGalleryItemsAndLabels } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260429T112543CatalogProductAttachments } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260429T123726CatalogProductLinks } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260429T130803CatalogGroupedAndBundle } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260501T185835CatalogProductAttributeIsComparable } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260505T060113CatalogAttributeOptionsAndFlags } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260515T082629CatalogAttributeMassEditable } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260526T124736CatalogProductStatusInactive } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260611T140346CatalogProductValueOverridesInit } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260611T140400CatalogAttributeQuickSearchable } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260611T140407CatalogBulkOperations } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260611T140408CatalogBulkOperationLogs } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260611T140412CatalogProductPackagingUnits } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260718T060659CatalogBulkOperationRevertState } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260718T200343CatalogCategoryCustomFieldValues } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260723T230401CatalogAttributesOnCustomFields } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260804T152604CatalogWidenProductSku } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260804T160244CatalogCategoryActivation } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260912T094557CatalogSalesChannelProducts } from '@endora-commerce/mod-catalog/migrations';
import { Migration20260912T094623CatalogSalesChannelCategories } from '@endora-commerce/mod-catalog/migrations';

// ── cms ─────────────────────────────────────────────────────────────────────
import { Migration20260425T162418CmsPagesInit } from '@endora-commerce/mod-cms/migrations';
import { Migration20260505T130214CmsInit } from '@endora-commerce/mod-cms/migrations';
import { Migration20260903T101741CmsNamespaceBlockNames } from '@endora-commerce/mod-cms/migrations';
import { Migration20260912T094733CmsSalesChannelCmsPages } from '@endora-commerce/mod-cms/migrations';
import { Migration20260912T125709CmsPageBodyAssetRefIndex } from '@endora-commerce/mod-cms/migrations';

// ── comparisons ─────────────────────────────────────────────────────────────
import { Migration20260501T185834ComparisonsInit } from '@endora-commerce/mod-comparisons/migrations';
import { Migration20260830T163143ComparisonsOrganizationAttribution } from '@endora-commerce/mod-comparisons/migrations';

// ── core ────────────────────────────────────────────────────────────────────
import { Migration20260424T165847CoreFoundationInit } from '@endora-commerce/platform/migrations';
import { Migration20260425T050720CoreCommerceInit } from '@endora-commerce/platform/migrations';
import { Migration20260430T101450CoreSettingsInit } from '@endora-commerce/platform/migrations';
import { Migration20260430T170044CoreSalesChannelsPromote } from '@endora-commerce/platform/migrations';
import { Migration20260506T200657CoreModuleLifecycleInit } from '@endora-commerce/platform/migrations';
import { Migration20260514T111329CoreSettingsGlobalValue } from '@endora-commerce/platform/migrations';
import { Migration20260611T140411CoreSettingsSecretValueType } from '@endora-commerce/platform/migrations';
import { Migration20260611T140419CoreSettingsEnumOptions } from '@endora-commerce/platform/migrations';
import { Migration20260629T090100CoreSettingsHiddenFlag } from '@endora-commerce/platform/migrations';
import { Migration20260717T134752CoreTenantScopeIndexes } from '@endora-commerce/platform/migrations';
import { Migration20260721T011510CoreSettingsCredentialRefValueType } from '@endora-commerce/platform/migrations';
import { Migration20260816T203339CoreRetireCoreActivationSettings } from '@endora-commerce/platform/migrations';

// ── credentials ─────────────────────────────────────────────────────────────
import { Migration20260721T011509CredentialsInit } from '@endora-commerce/mod-credentials/migrations';

// ── credit_limits ───────────────────────────────────────────────────────────
import { Migration20260425T063333CreditLimitsInit } from '@endora-commerce/mod-credit-limits/migrations';
import { Migration20260817T201111CreditLimitsReturnTopups } from '@endora-commerce/mod-credit-limits/migrations';
import { Migration20260818T081252CreditLimitsCreditLimitReservationOrderFk } from '@endora-commerce/mod-credit-limits/migrations';
import { Migration20260821T140323CreditLimitsReservationReservingOrganization } from '@endora-commerce/mod-credit-limits/migrations';

// ── custom_fields ───────────────────────────────────────────────────────────
import { Migration20260718T200338CustomFieldsInit } from '@endora-commerce/mod-custom-fields/migrations';

// ── customer_accounts ───────────────────────────────────────────────────────
import { Migration20260425T055041CustomerAccountsPasswordResetTokens } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260611T140351CustomerAccountsOrganizationOptional } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260611T140403CustomerAccountsLifecycle } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260718T200341CustomerAccountsCustomerAccountCustomFieldValues } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260720T044255CustomerAccountsCustomerSubtreeRollup } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260819T074816CustomerAccountsPasswordSetAt } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260819T142837CustomerAccountsFoldEmailCase } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260825T124759CustomerAccountsDropLegacyTwoFactorSecret } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260825T141659CustomerAccountsOrganizationRequired } from '@endora-commerce/mod-customer-accounts/migrations';
import { Migration20260912T094701CustomerAccountsSalesChannelCustomerAccounts } from '@endora-commerce/mod-customer-accounts/migrations';

// ── customers ───────────────────────────────────────────────────────────────
import { Migration20260611T140404CustomersCustomerAddressesInit } from '@endora-commerce/mod-customers/migrations';

// ── delivery_methods ────────────────────────────────────────────────────────
import { Migration20260611T140354DeliveryMethodsShippingMethodsAdapterAndShipments } from '@endora-commerce/mod-delivery-methods/migrations';
import { Migration20260611T140416DeliveryMethodsFixInPersonPickupAdapter } from '@endora-commerce/mod-delivery-methods/migrations';
import { Migration20260912T094638DeliveryMethodsSalesChannelDeliveryMethods } from '@endora-commerce/mod-delivery-methods/migrations';

// ── dhl_parcel ──────────────────────────────────────────────────────────────
import { Migration20260824T083000DhlParcelInit } from '@endora-commerce/mod-dhl-parcel/migrations';
import { Migration20260824T083100DhlParcelSeedDeliveryMethods } from '@endora-commerce/mod-dhl-parcel/migrations';

// ── dictionaries ────────────────────────────────────────────────────────────
import { Migration20260506T112634DictionariesDictionaryInit } from '@endora-commerce/mod-dictionaries/migrations';

// ── email ───────────────────────────────────────────────────────────────────
import { Migration20260817T070014EmailDeliveryRecord } from '@endora-commerce/mod-email/migrations';

// ── google_analytics ────────────────────────────────────────────────────────
import { Migration20260715T171116GoogleAnalyticsInit } from '@endora-commerce/mod-google-analytics/migrations';

// ── inpost ──────────────────────────────────────────────────────────────────
import { Migration20260821T150748InpostWebhookEventsAndShipmentLinks } from '@endora-commerce/mod-inpost/migrations';
import { Migration20260829T120000InpostSeedDeliveryMethods } from '@endora-commerce/mod-inpost/migrations';

// ── inventory ───────────────────────────────────────────────────────────────
import { Migration20260503T182812InventoryWorkflow } from '@endora-commerce/mod-inventory/migrations';
import { Migration20260611T140347InventoryWarehouseDefaultLowStockThreshold } from '@endora-commerce/mod-inventory/migrations';
import { Migration20260611T140348InventoryPerWarehouseLowStockThresholds } from '@endora-commerce/mod-inventory/migrations';
import { Migration20260818T081243InventoryStockAllocationOrderItemFk } from '@endora-commerce/mod-inventory/migrations';
import { Migration20260830T182139InventoryOrganizationAttribution } from '@endora-commerce/mod-inventory/migrations';
import { Migration20260912T125716InventoryOrganizationWarehouses } from '@endora-commerce/mod-inventory/migrations';

// ── invoice_ledger ──────────────────────────────────────────────────────────
import { Migration20260908T125013InvoiceLedgerInit } from '@endora-commerce/mod-invoice-ledger/migrations';

// ── invoices ────────────────────────────────────────────────────────────────
import { Migration20260629T125121InvoicesModule } from '@endora-commerce/mod-invoices/migrations';
import { Migration20260801T111000InvoicesGenericTemplateReseed } from '@endora-commerce/mod-invoices/migrations';
import { Migration20260817T201110InvoicesCorrectionIdempotencyKey } from '@endora-commerce/mod-invoices/migrations';
import { Migration20260903T101756InvoicesNamespaceBlockNames } from '@endora-commerce/mod-invoices/migrations';

// ── ksef ────────────────────────────────────────────────────────────────────
import { Migration20260722T224358KsefInit } from '@endora-commerce/mod-ksef/migrations';

// ── languages ───────────────────────────────────────────────────────────────
import { Migration20260425T161557LanguagesCurrenciesInit } from '@endora-commerce/mod-languages/migrations';

// ── linkedin_ads ────────────────────────────────────────────────────────────
import { Migration20260727T233211LinkedinAdsInit } from '@endora-commerce/mod-linkedin-ads/migrations';

// ── megamenu ────────────────────────────────────────────────────────────────
import { Migration20260505T193836MegamenuInit } from '@endora-commerce/mod-megamenu/migrations';

// ── meta_ads ────────────────────────────────────────────────────────────────
import { Migration20260728T002715MetaAdsInit } from '@endora-commerce/mod-meta-ads/migrations';

// ── mfa ─────────────────────────────────────────────────────────────────────
import { Migration20260611T140409MfaInit } from '@endora-commerce/mod-mfa/migrations';

// ── newsletter ──────────────────────────────────────────────────────────────
import { Migration20260629T200954NewsletterInit } from '@endora-commerce/mod-newsletter/migrations';
import { Migration20260830T212736NewsletterOrganizationAttribution } from '@endora-commerce/mod-newsletter/migrations';
import { Migration20260903T101752NewsletterNamespaceBlockNames } from '@endora-commerce/mod-newsletter/migrations';
import { Migration20260912T125702NewsletterSubscriberTenantScopeIndex } from '@endora-commerce/mod-newsletter/migrations';

// ── orders ──────────────────────────────────────────────────────────────────
import { Migration20260611T140355OrdersBusinessId } from '@endora-commerce/mod-orders/migrations';
import { Migration20260611T140356OrdersStatusModel } from '@endora-commerce/mod-orders/migrations';
import { Migration20260611T140357OrdersOrderCommentsAndSavedViews } from '@endora-commerce/mod-orders/migrations';
import { Migration20260611T140401OrdersOrderStatusDefaultName } from '@endora-commerce/mod-orders/migrations';
import { Migration20260611T140405OrdersOrderStatusColor } from '@endora-commerce/mod-orders/migrations';
import { Migration20260611T140406OrdersOrderSavedViewColumns } from '@endora-commerce/mod-orders/migrations';
import { Migration20260611T140414OrdersOrderItemPackaging } from '@endora-commerce/mod-orders/migrations';
import { Migration20260618T130459OrdersOrderAppliedPromotions } from '@endora-commerce/mod-orders/migrations';
import { Migration20260718T200339OrdersOrderCustomFieldValues } from '@endora-commerce/mod-orders/migrations';
import { Migration20260724T193611OrdersOrderPlacementIntents } from '@endora-commerce/mod-orders/migrations';
import { Migration20260804T114814OrdersShippingAdapterData } from '@endora-commerce/mod-orders/migrations';
import { Migration20260820T100201OrdersNewToPaidTransition } from '@endora-commerce/mod-orders/migrations';
import { Migration20260821T131145OrdersPurchaseConversionMarker } from '@endora-commerce/mod-orders/migrations';
import { Migration20260824T080000OrdersDeliveryPointSnapshot } from '@endora-commerce/mod-orders/migrations';

// ── organizations ───────────────────────────────────────────────────────────
import { Migration20260424T205317OrganizationsInit } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260425T051700OrganizationsInvitationsInit } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260611T140349OrganizationsConsolidation } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260611T140358OrganizationsOrgOrderConfirmationEmails } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260611T140402OrganizationsOrgFulfilmentStrategy } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260717T151403OrganizationsPersonalOrganizations } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260718T200340OrganizationsOrganizationCustomFieldValues } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260720T044254OrganizationsOrgHierarchy } from '@endora-commerce/mod-organizations/migrations';
import { Migration20260912T094646OrganizationsSalesChannelOrganizations } from '@endora-commerce/mod-organizations/migrations';

// ── payment_methods ─────────────────────────────────────────────────────────
import { Migration20260611T140353PaymentMethodsAdapter } from '@endora-commerce/mod-payment-methods/migrations';
import { Migration20260821T084920PaymentMethodsFailureStatusOnHold } from '@endora-commerce/mod-payment-methods/migrations';
import { Migration20260912T094631PaymentMethodsSalesChannelPaymentMethods } from '@endora-commerce/mod-payment-methods/migrations';

// ── paypal ──────────────────────────────────────────────────────────────────
import { Migration20260821T110651PaypalInit } from '@endora-commerce/mod-paypal/migrations';
import { Migration20260821T110652PaypalSeedPaymentMethods } from '@endora-commerce/mod-paypal/migrations';
import { Migration20260821T164749PaypalFailureStatusOnHold } from '@endora-commerce/mod-paypal/migrations';

// ── payu ────────────────────────────────────────────────────────────────────
import { Migration20260801T100943PayuInit } from '@endora-commerce/mod-payu/migrations';
import { Migration20260816T053830PayuSeedPaymentMethods } from '@endora-commerce/mod-payu/migrations';
import { Migration20260821T084923PayuFailureStatusOnHold } from '@endora-commerce/mod-payu/migrations';

// ── pim_akeneo ──────────────────────────────────────────────────────────────
import { Migration20260825T124458PimAkeneoInit } from '@endora-commerce/mod-pim-akeneo/migrations';

// ── pim_connector ───────────────────────────────────────────────────────────
import { Migration20260826T153500PimConnectorInit } from '@endora-commerce/mod-pim-connector/migrations';

// ── pim_ergonode ────────────────────────────────────────────────────────────
import { Migration20260804T190439PimErgonodeInit } from '@endora-commerce/mod-pim-ergonode/migrations';
import { Migration20260819T193653PimErgonodeFoldDerivedKeys } from '@endora-commerce/mod-pim-ergonode/migrations';

// ── pim_pimcore ─────────────────────────────────────────────────────────────
import { Migration20260818T102204PimPimcoreInit } from '@endora-commerce/mod-pim-pimcore/migrations';
import { Migration20260820T150317PimPimcoreCompleteRecordDelivery } from '@endora-commerce/mod-pim-pimcore/migrations';
import { Migration20260901T102908PimPimcoreDeliveredRecordColumnWidths } from '@endora-commerce/mod-pim-pimcore/migrations';

// ── pim_unopim ──────────────────────────────────────────────────────────────
import { Migration20260826T160000PimUnopimInit } from '@endora-commerce/mod-pim-unopim/migrations';

// ── price_lists ─────────────────────────────────────────────────────────────
import { Migration20260426T075235PriceListsPricingInit } from '@endora-commerce/mod-price-lists/migrations';
import { Migration20260504T125655PriceListsEngine } from '@endora-commerce/mod-price-lists/migrations';
import { Migration20260817T055457PriceListsSingleSystemPriceList } from '@endora-commerce/mod-price-lists/migrations';
import { Migration20260821T135907PriceListsUnitPriceAmountIndex } from '@endora-commerce/mod-price-lists/migrations';

// ── product_feeds ───────────────────────────────────────────────────────────
import { Migration20260802T073547ProductFeedsInit } from '@endora-commerce/mod-product-feeds/migrations';
import { Migration20260802T073627ProductFeedsRuns } from '@endora-commerce/mod-product-feeds/migrations';
import { Migration20260802T110630ProductFeedsTaxonomies } from '@endora-commerce/mod-product-feeds/migrations';
import { Migration20260803T060153ProductFeedsTaxonomyRefresh } from '@endora-commerce/mod-product-feeds/migrations';
import { Migration20260804T152741ProductFeedsWidenIssueSku } from '@endora-commerce/mod-product-feeds/migrations';
import { Migration20260806T105956ProductFeedsFeedTokenSecret } from '@endora-commerce/mod-product-feeds/migrations';
import { Migration20260806T125806ProductFeedsDelivery } from '@endora-commerce/mod-product-feeds/migrations';

// ── promotions ──────────────────────────────────────────────────────────────
import { Migration20260505T074605PromotionsCriteria } from '@endora-commerce/mod-promotions/migrations';
import { Migration20260618T100727PromotionsEngine } from '@endora-commerce/mod-promotions/migrations';
import { Migration20260818T081251PromotionsPromotionUsageOrderFk } from '@endora-commerce/mod-promotions/migrations';
import { Migration20260912T094715PromotionsSalesChannelPromotions } from '@endora-commerce/mod-promotions/migrations';

// ── prompt_actions ──────────────────────────────────────────────────────────
import { Migration20260611T140410PromptActionsInit } from '@endora-commerce/mod-prompt-actions/migrations';

// ── pwa ─────────────────────────────────────────────────────────────────────
import { Migration20260625T144228PwaInit } from '@endora-commerce/mod-pwa/migrations';
import { Migration20260830T172022PwaOrganizationAttribution } from '@endora-commerce/mod-pwa/migrations';

// ── quick_order ─────────────────────────────────────────────────────────────
import { Migration20260611T140359QuickOrderDefaultPreferences } from '@endora-commerce/mod-quick-order/migrations';

// ── quote_requests ──────────────────────────────────────────────────────────
import { Migration20260424T190112QuoteRequestsInit } from '@endora-commerce/mod-quote-requests/migrations';
import { Migration20260503T141344QuoteRequestsWorkflow } from '@endora-commerce/mod-quote-requests/migrations';
import { Migration20260611T140415QuoteRequestsQrItemPackaging } from '@endora-commerce/mod-quote-requests/migrations';
import { Migration20260611T140417QuoteRequestsBusinessId } from '@endora-commerce/mod-quote-requests/migrations';
import { Migration20260617T095510QuoteRequestsBackfillAdminCreatedAwaiting } from '@endora-commerce/mod-quote-requests/migrations';
import { Migration20260718T200342QuoteRequestsQuoteRequestCustomFieldValues } from '@endora-commerce/mod-quote-requests/migrations';
import { Migration20260912T125614QuoteRequestsQuoteRequestChannelAttribution } from '@endora-commerce/mod-quote-requests/migrations';

// ── returns ─────────────────────────────────────────────────────────────────
import { Migration20260625T144227ReturnsInit } from '@endora-commerce/mod-returns/migrations';
import { Migration20260817T203206ReturnsRefundCorrectiveInvoiceOutcome } from '@endora-commerce/mod-returns/migrations';

// ── search ──────────────────────────────────────────────────────────────────
import { Migration20260501T123145SearchPhraseRecordsInit } from '@endora-commerce/mod-search/migrations';

// ── seo ─────────────────────────────────────────────────────────────────────
import { Migration20260425T154404SeoInit } from '@endora-commerce/mod-seo/migrations';

// ── shipments ───────────────────────────────────────────────────────────────
import { Migration20260817T194652ShipmentsOrderFk } from '@endora-commerce/mod-shipments/migrations';
import { Migration20260819T171006ShipmentsStatusPendingManual } from '@endora-commerce/mod-shipments/migrations';

// ── shopping_lists ──────────────────────────────────────────────────────────
import { Migration20260426T135443ShoppingListsInit } from '@endora-commerce/mod-shopping-lists/migrations';
import { Migration20260611T140418ShoppingListsDefault } from '@endora-commerce/mod-shopping-lists/migrations';

// ── stripe ──────────────────────────────────────────────────────────────────
import { Migration20260708T101135StripeInit } from '@endora-commerce/mod-stripe/migrations';
import { Migration20260715T103358StripePaymentRefundedAmount } from '@endora-commerce/mod-stripe/migrations';
import { Migration20260816T053826StripeSeedPaymentMethods } from '@endora-commerce/mod-stripe/migrations';
import { Migration20260821T084922StripeFailureStatusOnHold } from '@endora-commerce/mod-stripe/migrations';

// ── taxes ───────────────────────────────────────────────────────────────────
import { Migration20260426T081516TaxesPromotionsInit } from '@endora-commerce/mod-taxes/migrations';
import { Migration20260912T094654TaxesSalesChannelTaxes } from '@endora-commerce/mod-taxes/migrations';

// ── tpay ────────────────────────────────────────────────────────────────────
import { Migration20260729T132507TpayInit } from '@endora-commerce/mod-tpay/migrations';
import { Migration20260816T053834TpaySeedPaymentMethods } from '@endora-commerce/mod-tpay/migrations';
import { Migration20260821T084924TpayFailureStatusOnHold } from '@endora-commerce/mod-tpay/migrations';

// ── transactional_emails ────────────────────────────────────────────────────
import { Migration20260629T113442TransactionalEmailsInit } from '@endora-commerce/mod-transactional-emails/migrations';
import { Migration20260801T111001TransactionalEmailsEmailDefaultsReseed } from '@endora-commerce/mod-transactional-emails/migrations';
import { Migration20260903T101748TransactionalEmailsNamespaceBlockNames } from '@endora-commerce/mod-transactional-emails/migrations';

// ── webhooks ────────────────────────────────────────────────────────────────
import { Migration20260425T091359WebhooksUs7Init } from '@endora-commerce/mod-webhooks/migrations';
import { Migration20260724T203140WebhooksOrgFilter } from '@endora-commerce/mod-webhooks/migrations';
import { Migration20260727T200555WebhooksDropExternalIntegrations } from '@endora-commerce/mod-webhooks/migrations';

export type { MigrationClass, MigrationRegistryEntry };

/** One-line helper: the migration name is always `cls.name`, never hand-written. */
function migration(moduleId: string, cls: MigrationClass): MigrationRegistryEntry {
  return { moduleId, cls };
}

export const MIGRATION_REGISTRY: readonly MigrationRegistryEntry[] = [
  // ── _i18n ───────────────────────────────────────────────────────────────────
  migration('_i18n', Migration20260507T091405I18nAdminI18nInit),

  // ── admin_actions ───────────────────────────────────────────────────────────
  migration('admin_actions', Migration20260507T142354AdminActionsInit),

  // ── admin_notifications ─────────────────────────────────────────────────────
  migration('admin_notifications', Migration20260611T140350AdminNotificationsInit),

  // ── admin_users ─────────────────────────────────────────────────────────────
  migration('admin_users', Migration20260425T053028AdminUsersInit),
  migration('admin_users', Migration20260819T155150AdminUsersFoldEmailCase),
  migration('admin_users', Migration20260825T124801AdminUsersDropLegacyTwoFactorSecret),

  // ── analytics ───────────────────────────────────────────────────────────────
  migration('analytics', Migration20260425T143139AnalyticsInit),
  migration('analytics', Migration20260912T125655AnalyticsEventsTenantScopeIndexes),

  // ── api_keys ────────────────────────────────────────────────────────────────
  migration('api_keys', Migration20260724T173916ApiKeysDistributorBinding),

  // ── assets_library ──────────────────────────────────────────────────────────
  migration('assets_library', Migration20260505T102206AssetsLibraryInit),

  // ── autopay ─────────────────────────────────────────────────────────────────
  migration('autopay', Migration20260803T065409AutopayInit),
  migration('autopay', Migration20260816T053835AutopaySeedPaymentMethods),
  migration('autopay', Migration20260821T084925AutopayFailureStatusOnHold),

  // ── blog ────────────────────────────────────────────────────────────────────
  migration('blog', Migration20260506T081055BlogInit),
  migration('blog', Migration20260903T101744BlogNamespaceBlockNames),

  // ── carts ───────────────────────────────────────────────────────────────────
  migration('carts', Migration20260611T140352CartsConsolidation),
  migration('carts', Migration20260611T140413CartsCartItemPackaging),
  migration('carts', Migration20260818T081253CartsCartCompletedOrderFk),
  migration('carts', Migration20260830T112911CartsOrganizationAttributionCheck),

  // ── catalog ─────────────────────────────────────────────────────────────────
  migration('catalog', Migration20260429T064146CatalogAttributeSetsInit),
  migration('catalog', Migration20260429T070004CatalogProductAttributeExtensions),
  migration('catalog', Migration20260429T102322CatalogProductTypeAndVirtualFields),
  migration('catalog', Migration20260429T111839CatalogGalleryItemsAndLabels),
  migration('catalog', Migration20260429T112543CatalogProductAttachments),
  migration('catalog', Migration20260429T123726CatalogProductLinks),
  migration('catalog', Migration20260429T130803CatalogGroupedAndBundle),
  migration('catalog', Migration20260501T185835CatalogProductAttributeIsComparable),
  migration('catalog', Migration20260505T060113CatalogAttributeOptionsAndFlags),
  migration('catalog', Migration20260515T082629CatalogAttributeMassEditable),
  migration('catalog', Migration20260526T124736CatalogProductStatusInactive),
  migration('catalog', Migration20260611T140346CatalogProductValueOverridesInit),
  migration('catalog', Migration20260611T140400CatalogAttributeQuickSearchable),
  migration('catalog', Migration20260611T140407CatalogBulkOperations),
  migration('catalog', Migration20260611T140408CatalogBulkOperationLogs),
  migration('catalog', Migration20260611T140412CatalogProductPackagingUnits),
  migration('catalog', Migration20260718T060659CatalogBulkOperationRevertState),
  migration('catalog', Migration20260718T200343CatalogCategoryCustomFieldValues),
  migration('catalog', Migration20260723T230401CatalogAttributesOnCustomFields),
  migration('catalog', Migration20260804T152604CatalogWidenProductSku),
  migration('catalog', Migration20260804T160244CatalogCategoryActivation),
  migration('catalog', Migration20260912T094557CatalogSalesChannelProducts),
  migration('catalog', Migration20260912T094623CatalogSalesChannelCategories),

  // ── cms ─────────────────────────────────────────────────────────────────────
  migration('cms', Migration20260425T162418CmsPagesInit),
  migration('cms', Migration20260505T130214CmsInit),
  migration('cms', Migration20260903T101741CmsNamespaceBlockNames),
  migration('cms', Migration20260912T094733CmsSalesChannelCmsPages),
  migration('cms', Migration20260912T125709CmsPageBodyAssetRefIndex),

  // ── comparisons ─────────────────────────────────────────────────────────────
  migration('comparisons', Migration20260501T185834ComparisonsInit),
  migration('comparisons', Migration20260830T163143ComparisonsOrganizationAttribution),

  // ── core ────────────────────────────────────────────────────────────────────
  migration('core', Migration20260424T165847CoreFoundationInit),
  migration('core', Migration20260425T050720CoreCommerceInit),
  migration('core', Migration20260430T101450CoreSettingsInit),
  migration('core', Migration20260430T170044CoreSalesChannelsPromote),
  migration('core', Migration20260506T200657CoreModuleLifecycleInit),
  migration('core', Migration20260514T111329CoreSettingsGlobalValue),
  migration('core', Migration20260611T140411CoreSettingsSecretValueType),
  migration('core', Migration20260611T140419CoreSettingsEnumOptions),
  migration('core', Migration20260629T090100CoreSettingsHiddenFlag),
  migration('core', Migration20260717T134752CoreTenantScopeIndexes),
  migration('core', Migration20260721T011510CoreSettingsCredentialRefValueType),
  migration('core', Migration20260816T203339CoreRetireCoreActivationSettings),

  // ── credentials ─────────────────────────────────────────────────────────────
  migration('credentials', Migration20260721T011509CredentialsInit),

  // ── credit_limits ───────────────────────────────────────────────────────────
  migration('credit_limits', Migration20260425T063333CreditLimitsInit),
  migration('credit_limits', Migration20260817T201111CreditLimitsReturnTopups),
  migration('credit_limits', Migration20260818T081252CreditLimitsCreditLimitReservationOrderFk),
  migration('credit_limits', Migration20260821T140323CreditLimitsReservationReservingOrganization),

  // ── custom_fields ───────────────────────────────────────────────────────────
  migration('custom_fields', Migration20260718T200338CustomFieldsInit),

  // ── customer_accounts ───────────────────────────────────────────────────────
  migration('customer_accounts', Migration20260425T055041CustomerAccountsPasswordResetTokens),
  migration('customer_accounts', Migration20260611T140351CustomerAccountsOrganizationOptional),
  migration('customer_accounts', Migration20260611T140403CustomerAccountsLifecycle),
  migration('customer_accounts', Migration20260718T200341CustomerAccountsCustomerAccountCustomFieldValues),
  migration('customer_accounts', Migration20260720T044255CustomerAccountsCustomerSubtreeRollup),
  migration('customer_accounts', Migration20260819T074816CustomerAccountsPasswordSetAt),
  migration('customer_accounts', Migration20260819T142837CustomerAccountsFoldEmailCase),
  migration('customer_accounts', Migration20260825T124759CustomerAccountsDropLegacyTwoFactorSecret),
  migration('customer_accounts', Migration20260825T141659CustomerAccountsOrganizationRequired),
  migration('customer_accounts', Migration20260912T094701CustomerAccountsSalesChannelCustomerAccounts),

  // ── customers ───────────────────────────────────────────────────────────────
  migration('customers', Migration20260611T140404CustomersCustomerAddressesInit),

  // ── delivery_methods ────────────────────────────────────────────────────────
  migration('delivery_methods', Migration20260611T140354DeliveryMethodsShippingMethodsAdapterAndShipments),
  migration('delivery_methods', Migration20260611T140416DeliveryMethodsFixInPersonPickupAdapter),
  migration('delivery_methods', Migration20260912T094638DeliveryMethodsSalesChannelDeliveryMethods),

  // ── dhl_parcel ──────────────────────────────────────────────────────────────
  migration('dhl_parcel', Migration20260824T083000DhlParcelInit),
  migration('dhl_parcel', Migration20260824T083100DhlParcelSeedDeliveryMethods),

  // ── dictionaries ────────────────────────────────────────────────────────────
  migration('dictionaries', Migration20260506T112634DictionariesDictionaryInit),

  // ── email ───────────────────────────────────────────────────────────────────
  migration('email', Migration20260817T070014EmailDeliveryRecord),

  // ── google_analytics ────────────────────────────────────────────────────────
  migration('google_analytics', Migration20260715T171116GoogleAnalyticsInit),

  // ── inpost ──────────────────────────────────────────────────────────────────
  migration('inpost', Migration20260821T150748InpostWebhookEventsAndShipmentLinks),
  migration('inpost', Migration20260829T120000InpostSeedDeliveryMethods),

  // ── inventory ───────────────────────────────────────────────────────────────
  migration('inventory', Migration20260503T182812InventoryWorkflow),
  migration('inventory', Migration20260611T140347InventoryWarehouseDefaultLowStockThreshold),
  migration('inventory', Migration20260611T140348InventoryPerWarehouseLowStockThresholds),
  migration('inventory', Migration20260818T081243InventoryStockAllocationOrderItemFk),
  migration('inventory', Migration20260830T182139InventoryOrganizationAttribution),
  migration('inventory', Migration20260912T125716InventoryOrganizationWarehouses),

  // ── invoice_ledger ──────────────────────────────────────────────────────────
  migration('invoice_ledger', Migration20260908T125013InvoiceLedgerInit),

  // ── invoices ────────────────────────────────────────────────────────────────
  migration('invoices', Migration20260629T125121InvoicesModule),
  migration('invoices', Migration20260801T111000InvoicesGenericTemplateReseed),
  migration('invoices', Migration20260817T201110InvoicesCorrectionIdempotencyKey),
  migration('invoices', Migration20260903T101756InvoicesNamespaceBlockNames),

  // ── ksef ────────────────────────────────────────────────────────────────────
  migration('ksef', Migration20260722T224358KsefInit),

  // ── languages ───────────────────────────────────────────────────────────────
  migration('languages', Migration20260425T161557LanguagesCurrenciesInit),

  // ── linkedin_ads ────────────────────────────────────────────────────────────
  migration('linkedin_ads', Migration20260727T233211LinkedinAdsInit),

  // ── megamenu ────────────────────────────────────────────────────────────────
  migration('megamenu', Migration20260505T193836MegamenuInit),

  // ── meta_ads ────────────────────────────────────────────────────────────────
  migration('meta_ads', Migration20260728T002715MetaAdsInit),

  // ── mfa ─────────────────────────────────────────────────────────────────────
  migration('mfa', Migration20260611T140409MfaInit),

  // ── newsletter ──────────────────────────────────────────────────────────────
  migration('newsletter', Migration20260629T200954NewsletterInit),
  migration('newsletter', Migration20260830T212736NewsletterOrganizationAttribution),
  migration('newsletter', Migration20260903T101752NewsletterNamespaceBlockNames),
  migration('newsletter', Migration20260912T125702NewsletterSubscriberTenantScopeIndex),

  // ── orders ──────────────────────────────────────────────────────────────────
  migration('orders', Migration20260611T140355OrdersBusinessId),
  migration('orders', Migration20260611T140356OrdersStatusModel),
  migration('orders', Migration20260611T140357OrdersOrderCommentsAndSavedViews),
  migration('orders', Migration20260611T140401OrdersOrderStatusDefaultName),
  migration('orders', Migration20260611T140405OrdersOrderStatusColor),
  migration('orders', Migration20260611T140406OrdersOrderSavedViewColumns),
  migration('orders', Migration20260611T140414OrdersOrderItemPackaging),
  migration('orders', Migration20260618T130459OrdersOrderAppliedPromotions),
  migration('orders', Migration20260718T200339OrdersOrderCustomFieldValues),
  migration('orders', Migration20260724T193611OrdersOrderPlacementIntents),
  migration('orders', Migration20260804T114814OrdersShippingAdapterData),
  migration('orders', Migration20260820T100201OrdersNewToPaidTransition),
  migration('orders', Migration20260821T131145OrdersPurchaseConversionMarker),
  migration('orders', Migration20260824T080000OrdersDeliveryPointSnapshot),

  // ── organizations ───────────────────────────────────────────────────────────
  migration('organizations', Migration20260424T205317OrganizationsInit),
  migration('organizations', Migration20260425T051700OrganizationsInvitationsInit),
  migration('organizations', Migration20260611T140349OrganizationsConsolidation),
  migration('organizations', Migration20260611T140358OrganizationsOrgOrderConfirmationEmails),
  migration('organizations', Migration20260611T140402OrganizationsOrgFulfilmentStrategy),
  migration('organizations', Migration20260717T151403OrganizationsPersonalOrganizations),
  migration('organizations', Migration20260718T200340OrganizationsOrganizationCustomFieldValues),
  migration('organizations', Migration20260720T044254OrganizationsOrgHierarchy),
  migration('organizations', Migration20260912T094646OrganizationsSalesChannelOrganizations),

  // ── payment_methods ─────────────────────────────────────────────────────────
  migration('payment_methods', Migration20260611T140353PaymentMethodsAdapter),
  migration('payment_methods', Migration20260821T084920PaymentMethodsFailureStatusOnHold),
  migration('payment_methods', Migration20260912T094631PaymentMethodsSalesChannelPaymentMethods),

  // ── paypal ──────────────────────────────────────────────────────────────────
  migration('paypal', Migration20260821T110651PaypalInit),
  migration('paypal', Migration20260821T110652PaypalSeedPaymentMethods),
  migration('paypal', Migration20260821T164749PaypalFailureStatusOnHold),

  // ── payu ────────────────────────────────────────────────────────────────────
  migration('payu', Migration20260801T100943PayuInit),
  migration('payu', Migration20260816T053830PayuSeedPaymentMethods),
  migration('payu', Migration20260821T084923PayuFailureStatusOnHold),

  // ── pim_akeneo ──────────────────────────────────────────────────────────────
  migration('pim_akeneo', Migration20260825T124458PimAkeneoInit),

  // ── pim_connector ───────────────────────────────────────────────────────────
  migration('pim_connector', Migration20260826T153500PimConnectorInit),

  // ── pim_ergonode ────────────────────────────────────────────────────────────
  migration('pim_ergonode', Migration20260804T190439PimErgonodeInit),
  migration('pim_ergonode', Migration20260819T193653PimErgonodeFoldDerivedKeys),

  // ── pim_pimcore ─────────────────────────────────────────────────────────────
  migration('pim_pimcore', Migration20260818T102204PimPimcoreInit),
  migration('pim_pimcore', Migration20260820T150317PimPimcoreCompleteRecordDelivery),
  migration('pim_pimcore', Migration20260901T102908PimPimcoreDeliveredRecordColumnWidths),

  // ── pim_unopim ──────────────────────────────────────────────────────────────
  migration('pim_unopim', Migration20260826T160000PimUnopimInit),

  // ── price_lists ─────────────────────────────────────────────────────────────
  migration('price_lists', Migration20260426T075235PriceListsPricingInit),
  migration('price_lists', Migration20260504T125655PriceListsEngine),
  migration('price_lists', Migration20260817T055457PriceListsSingleSystemPriceList),
  migration('price_lists', Migration20260821T135907PriceListsUnitPriceAmountIndex),

  // ── product_feeds ───────────────────────────────────────────────────────────
  migration('product_feeds', Migration20260802T073547ProductFeedsInit),
  migration('product_feeds', Migration20260802T073627ProductFeedsRuns),
  migration('product_feeds', Migration20260802T110630ProductFeedsTaxonomies),
  migration('product_feeds', Migration20260803T060153ProductFeedsTaxonomyRefresh),
  migration('product_feeds', Migration20260804T152741ProductFeedsWidenIssueSku),
  migration('product_feeds', Migration20260806T105956ProductFeedsFeedTokenSecret),
  migration('product_feeds', Migration20260806T125806ProductFeedsDelivery),

  // ── promotions ──────────────────────────────────────────────────────────────
  migration('promotions', Migration20260505T074605PromotionsCriteria),
  migration('promotions', Migration20260618T100727PromotionsEngine),
  migration('promotions', Migration20260818T081251PromotionsPromotionUsageOrderFk),
  migration('promotions', Migration20260912T094715PromotionsSalesChannelPromotions),

  // ── prompt_actions ──────────────────────────────────────────────────────────
  migration('prompt_actions', Migration20260611T140410PromptActionsInit),

  // ── pwa ─────────────────────────────────────────────────────────────────────
  migration('pwa', Migration20260625T144228PwaInit),
  migration('pwa', Migration20260830T172022PwaOrganizationAttribution),

  // ── quick_order ─────────────────────────────────────────────────────────────
  migration('quick_order', Migration20260611T140359QuickOrderDefaultPreferences),

  // ── quote_requests ──────────────────────────────────────────────────────────
  migration('quote_requests', Migration20260424T190112QuoteRequestsInit),
  migration('quote_requests', Migration20260503T141344QuoteRequestsWorkflow),
  migration('quote_requests', Migration20260611T140415QuoteRequestsQrItemPackaging),
  migration('quote_requests', Migration20260611T140417QuoteRequestsBusinessId),
  migration('quote_requests', Migration20260617T095510QuoteRequestsBackfillAdminCreatedAwaiting),
  migration('quote_requests', Migration20260718T200342QuoteRequestsQuoteRequestCustomFieldValues),
  migration('quote_requests', Migration20260912T125614QuoteRequestsQuoteRequestChannelAttribution),

  // ── returns ─────────────────────────────────────────────────────────────────
  migration('returns', Migration20260625T144227ReturnsInit),
  migration('returns', Migration20260817T203206ReturnsRefundCorrectiveInvoiceOutcome),

  // ── search ──────────────────────────────────────────────────────────────────
  migration('search', Migration20260501T123145SearchPhraseRecordsInit),

  // ── seo ─────────────────────────────────────────────────────────────────────
  migration('seo', Migration20260425T154404SeoInit),

  // ── shipments ───────────────────────────────────────────────────────────────
  migration('shipments', Migration20260817T194652ShipmentsOrderFk),
  migration('shipments', Migration20260819T171006ShipmentsStatusPendingManual),

  // ── shopping_lists ──────────────────────────────────────────────────────────
  migration('shopping_lists', Migration20260426T135443ShoppingListsInit),
  migration('shopping_lists', Migration20260611T140418ShoppingListsDefault),

  // ── stripe ──────────────────────────────────────────────────────────────────
  migration('stripe', Migration20260708T101135StripeInit),
  migration('stripe', Migration20260715T103358StripePaymentRefundedAmount),
  migration('stripe', Migration20260816T053826StripeSeedPaymentMethods),
  migration('stripe', Migration20260821T084922StripeFailureStatusOnHold),

  // ── taxes ───────────────────────────────────────────────────────────────────
  migration('taxes', Migration20260426T081516TaxesPromotionsInit),
  migration('taxes', Migration20260912T094654TaxesSalesChannelTaxes),

  // ── tpay ────────────────────────────────────────────────────────────────────
  migration('tpay', Migration20260729T132507TpayInit),
  migration('tpay', Migration20260816T053834TpaySeedPaymentMethods),
  migration('tpay', Migration20260821T084924TpayFailureStatusOnHold),

  // ── transactional_emails ────────────────────────────────────────────────────
  migration('transactional_emails', Migration20260629T113442TransactionalEmailsInit),
  migration('transactional_emails', Migration20260801T111001TransactionalEmailsEmailDefaultsReseed),
  migration('transactional_emails', Migration20260903T101748TransactionalEmailsNamespaceBlockNames),

  // ── webhooks ────────────────────────────────────────────────────────────────
  migration('webhooks', Migration20260425T091359WebhooksUs7Init),
  migration('webhooks', Migration20260724T203140WebhooksOrgFilter),
  migration('webhooks', Migration20260727T200555WebhooksDropExternalIntegrations),
];
