// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// The single registration point for every migration in the repository.
//
// Static imports only — no glob, no dynamic `import()`: Node's ESM loader
// cannot transform `.ts` at runtime and it breaks under Vitest (the same reason
// ./entities-registry.generated.ts exists). A migration that is not registered
// here does not run; since feature 071's F2 registration is a filesystem walk
// rather than a line someone remembers to paste, and the round-trip guard in
// test/unit/db/migrations-registry.test.ts fails the build on a stale artefact.
//
// **Declaration order has no effect on execution order.** That is computed by
// migration-order.ts: the frozen historical prefix marked by BASELINE_THROUGH,
// then module by module in a topological order of the manifest dependency
// graph, each module's migrations contiguous and ascending by timestamp. A
// timestamp orders a module's own migrations and nothing else. Entries below
// are grouped by owning module purely so the diff reads; never "fix" an
// ordering surprise by moving a line, and there is nothing to move —
// regenerating restores it. Fix the manifest `dependencies` instead; a
// timestamp cannot fix a cross-module position.
//
// The `moduleId` is load-bearing beyond ordering: a hard uninstall reverts
// exactly the migrations registered under the module being removed
// (`_lifecycle/services/orchestrator.ts`). It is the directory the file lives
// in, which for kernel-owned tables is `core` —
// test/unit/db/kernel-migration-ownership.test.ts enforces that the tables a
// migration writes to agree with it.
//
// Add one with: pnpm --filter backend run migration:new -- --module <id> --name <slug>

import type { MigrationClass, MigrationRegistryEntry } from './migration-order.js';

// ── _i18n ───────────────────────────────────────────────────────────────────
import { Migration20260507T091405I18nAdminI18nInit } from '../modules/_i18n/migrations/20260507T091405_i18n_admin_i18n_init.js';

// ── admin_actions ───────────────────────────────────────────────────────────
import { Migration20260507T142354AdminActionsInit } from '../modules/admin_actions/migrations/20260507T142354_admin_actions_init.js';

// ── admin_notifications ─────────────────────────────────────────────────────
import { Migration20260611T140350AdminNotificationsInit } from '../modules/admin_notifications/migrations/20260611T140350_admin_notifications_init.js';

// ── admin_users ─────────────────────────────────────────────────────────────
import { Migration20260425T053028AdminUsersInit } from '../modules/admin_users/migrations/20260425T053028_admin_users_init.js';
import { Migration20260819T155150AdminUsersFoldEmailCase } from '../modules/admin_users/migrations/20260819T155150_admin_users_fold_email_case.js';

// ── analytics ───────────────────────────────────────────────────────────────
import { Migration20260425T143139AnalyticsInit } from '../modules/analytics/migrations/20260425T143139_analytics_init.js';

// ── api_keys ────────────────────────────────────────────────────────────────
import { Migration20260724T173916ApiKeysDistributorBinding } from '../modules/api_keys/migrations/20260724T173916_api_keys_distributor_binding.js';

// ── assets_library ──────────────────────────────────────────────────────────
import { Migration20260505T102206AssetsLibraryInit } from '../modules/assets_library/migrations/20260505T102206_assets_library_init.js';

// ── autopay ─────────────────────────────────────────────────────────────────
import { Migration20260803T065409AutopayInit } from '../modules/autopay/migrations/20260803T065409_autopay_init.js';
import { Migration20260816T053835AutopaySeedPaymentMethods } from '../modules/autopay/migrations/20260816T053835_autopay_seed_payment_methods.js';

// ── blog ────────────────────────────────────────────────────────────────────
import { Migration20260506T081055BlogInit } from '../modules/blog/migrations/20260506T081055_blog_init.js';

// ── carts ───────────────────────────────────────────────────────────────────
import { Migration20260611T140352CartsConsolidation } from '../modules/carts/migrations/20260611T140352_carts_consolidation.js';
import { Migration20260611T140413CartsCartItemPackaging } from '../modules/carts/migrations/20260611T140413_carts_cart_item_packaging.js';
import { Migration20260818T081253CartsCartCompletedOrderFk } from '../modules/carts/migrations/20260818T081253_carts_cart_completed_order_fk.js';

// ── catalog ─────────────────────────────────────────────────────────────────
import { Migration20260429T064146CatalogAttributeSetsInit } from '../modules/catalog/migrations/20260429T064146_catalog_attribute_sets_init.js';
import { Migration20260429T070004CatalogProductAttributeExtensions } from '../modules/catalog/migrations/20260429T070004_catalog_product_attribute_extensions.js';
import { Migration20260429T102322CatalogProductTypeAndVirtualFields } from '../modules/catalog/migrations/20260429T102322_catalog_product_type_and_virtual_fields.js';
import { Migration20260429T111839CatalogGalleryItemsAndLabels } from '../modules/catalog/migrations/20260429T111839_catalog_gallery_items_and_labels.js';
import { Migration20260429T112543CatalogProductAttachments } from '../modules/catalog/migrations/20260429T112543_catalog_product_attachments.js';
import { Migration20260429T123726CatalogProductLinks } from '../modules/catalog/migrations/20260429T123726_catalog_product_links.js';
import { Migration20260429T130803CatalogGroupedAndBundle } from '../modules/catalog/migrations/20260429T130803_catalog_grouped_and_bundle.js';
import { Migration20260501T185835CatalogProductAttributeIsComparable } from '../modules/catalog/migrations/20260501T185835_catalog_product_attribute_is_comparable.js';
import { Migration20260505T060113CatalogAttributeOptionsAndFlags } from '../modules/catalog/migrations/20260505T060113_catalog_attribute_options_and_flags.js';
import { Migration20260515T082629CatalogAttributeMassEditable } from '../modules/catalog/migrations/20260515T082629_catalog_attribute_mass_editable.js';
import { Migration20260526T124736CatalogProductStatusInactive } from '../modules/catalog/migrations/20260526T124736_catalog_product_status_inactive.js';
import { Migration20260611T140346CatalogProductValueOverridesInit } from '../modules/catalog/migrations/20260611T140346_catalog_product_value_overrides_init.js';
import { Migration20260611T140400CatalogAttributeQuickSearchable } from '../modules/catalog/migrations/20260611T140400_catalog_attribute_quick_searchable.js';
import { Migration20260611T140407CatalogBulkOperations } from '../modules/catalog/migrations/20260611T140407_catalog_bulk_operations.js';
import { Migration20260611T140408CatalogBulkOperationLogs } from '../modules/catalog/migrations/20260611T140408_catalog_bulk_operation_logs.js';
import { Migration20260611T140412CatalogProductPackagingUnits } from '../modules/catalog/migrations/20260611T140412_catalog_product_packaging_units.js';
import { Migration20260718T060659CatalogBulkOperationRevertState } from '../modules/catalog/migrations/20260718T060659_catalog_bulk_operation_revert_state.js';
import { Migration20260718T200343CatalogCategoryCustomFieldValues } from '../modules/catalog/migrations/20260718T200343_catalog_category_custom_field_values.js';
import { Migration20260723T230401CatalogAttributesOnCustomFields } from '../modules/catalog/migrations/20260723T230401_catalog_attributes_on_custom_fields.js';
import { Migration20260804T152604CatalogWidenProductSku } from '../modules/catalog/migrations/20260804T152604_catalog_widen_product_sku.js';
import { Migration20260804T160244CatalogCategoryActivation } from '../modules/catalog/migrations/20260804T160244_catalog_category_activation.js';

// ── cms ─────────────────────────────────────────────────────────────────────
import { Migration20260425T162418CmsPagesInit } from '../modules/cms/migrations/20260425T162418_cms_pages_init.js';
import { Migration20260505T130214CmsInit } from '../modules/cms/migrations/20260505T130214_cms_init.js';

// ── comparisons ─────────────────────────────────────────────────────────────
import { Migration20260501T185834ComparisonsInit } from '../modules/comparisons/migrations/20260501T185834_comparisons_init.js';

// ── core ────────────────────────────────────────────────────────────────────
import { Migration20260424T165847CoreFoundationInit } from './migrations/20260424T165847_core_foundation_init.js';
import { Migration20260425T050720CoreCommerceInit } from './migrations/20260425T050720_core_commerce_init.js';
import { Migration20260430T101450CoreSettingsInit } from './migrations/20260430T101450_core_settings_init.js';
import { Migration20260430T170044CoreSalesChannelsPromote } from './migrations/20260430T170044_core_sales_channels_promote.js';
import { Migration20260506T200657CoreModuleLifecycleInit } from './migrations/20260506T200657_core_module_lifecycle_init.js';
import { Migration20260514T111329CoreSettingsGlobalValue } from './migrations/20260514T111329_core_settings_global_value.js';
import { Migration20260611T140411CoreSettingsSecretValueType } from './migrations/20260611T140411_core_settings_secret_value_type.js';
import { Migration20260611T140419CoreSettingsEnumOptions } from './migrations/20260611T140419_core_settings_enum_options.js';
import { Migration20260629T090100CoreSettingsHiddenFlag } from './migrations/20260629T090100_core_settings_hidden_flag.js';
import { Migration20260717T134752CoreTenantScopeIndexes } from './migrations/20260717T134752_core_tenant_scope_indexes.js';
import { Migration20260721T011510CoreSettingsCredentialRefValueType } from './migrations/20260721T011510_core_settings_credential_ref_value_type.js';
import { Migration20260816T203339CoreRetireCoreActivationSettings } from './migrations/20260816T203339_core_retire_core_activation_settings.js';

// ── credentials ─────────────────────────────────────────────────────────────
import { Migration20260721T011509CredentialsInit } from '../modules/credentials/migrations/20260721T011509_credentials_init.js';

// ── credit_limits ───────────────────────────────────────────────────────────
import { Migration20260425T063333CreditLimitsInit } from '../modules/credit_limits/migrations/20260425T063333_credit_limits_init.js';
import { Migration20260817T201111CreditLimitsReturnTopups } from '../modules/credit_limits/migrations/20260817T201111_credit_limits_return_topups.js';
import { Migration20260818T081252CreditLimitsCreditLimitReservationOrderFk } from '../modules/credit_limits/migrations/20260818T081252_credit_limits_credit_limit_reservation_order_fk.js';

// ── custom_fields ───────────────────────────────────────────────────────────
import { Migration20260718T200338CustomFieldsInit } from '../modules/custom_fields/migrations/20260718T200338_custom_fields_init.js';

// ── customer_accounts ───────────────────────────────────────────────────────
import { Migration20260425T055041CustomerAccountsPasswordResetTokens } from '../modules/customer_accounts/migrations/20260425T055041_customer_accounts_password_reset_tokens.js';
import { Migration20260611T140351CustomerAccountsOrganizationOptional } from '../modules/customer_accounts/migrations/20260611T140351_customer_accounts_organization_optional.js';
import { Migration20260611T140403CustomerAccountsLifecycle } from '../modules/customer_accounts/migrations/20260611T140403_customer_accounts_lifecycle.js';
import { Migration20260718T200341CustomerAccountsCustomerAccountCustomFieldValues } from '../modules/customer_accounts/migrations/20260718T200341_customer_accounts_customer_account_custom_field_values.js';
import { Migration20260720T044255CustomerAccountsCustomerSubtreeRollup } from '../modules/customer_accounts/migrations/20260720T044255_customer_accounts_customer_subtree_rollup.js';
import { Migration20260819T074816CustomerAccountsPasswordSetAt } from '../modules/customer_accounts/migrations/20260819T074816_customer_accounts_password_set_at.js';
import { Migration20260819T142837CustomerAccountsFoldEmailCase } from '../modules/customer_accounts/migrations/20260819T142837_customer_accounts_fold_email_case.js';

// ── customers ───────────────────────────────────────────────────────────────
import { Migration20260611T140404CustomersCustomerAddressesInit } from '../modules/customers/migrations/20260611T140404_customers_customer_addresses_init.js';

// ── delivery_methods ────────────────────────────────────────────────────────
import { Migration20260611T140354DeliveryMethodsShippingMethodsAdapterAndShipments } from '../modules/delivery_methods/migrations/20260611T140354_delivery_methods_shipping_methods_adapter_and_shipments.js';
import { Migration20260611T140416DeliveryMethodsFixInPersonPickupAdapter } from '../modules/delivery_methods/migrations/20260611T140416_delivery_methods_fix_in_person_pickup_adapter.js';

// ── dictionaries ────────────────────────────────────────────────────────────
import { Migration20260506T112634DictionariesDictionaryInit } from '../modules/dictionaries/migrations/20260506T112634_dictionaries_dictionary_init.js';

// ── email ───────────────────────────────────────────────────────────────────
import { Migration20260817T070014EmailDeliveryRecord } from '../modules/email/migrations/20260817T070014_email_delivery_record.js';

// ── google_analytics ────────────────────────────────────────────────────────
import { Migration20260715T171116GoogleAnalyticsInit } from '../modules/google_analytics/migrations/20260715T171116_google_analytics_init.js';

// ── inpost ──────────────────────────────────────────────────────────────────
import { Migration20260821T150748InpostWebhookEventsAndShipmentLinks } from '../modules/inpost/migrations/20260821T150748_inpost_webhook_events_and_shipment_links.js';

// ── inventory ───────────────────────────────────────────────────────────────
import { Migration20260503T182812InventoryWorkflow } from '../modules/inventory/migrations/20260503T182812_inventory_workflow.js';
import { Migration20260611T140347InventoryWarehouseDefaultLowStockThreshold } from '../modules/inventory/migrations/20260611T140347_inventory_warehouse_default_low_stock_threshold.js';
import { Migration20260611T140348InventoryPerWarehouseLowStockThresholds } from '../modules/inventory/migrations/20260611T140348_inventory_per_warehouse_low_stock_thresholds.js';
import { Migration20260818T081243InventoryStockAllocationOrderItemFk } from '../modules/inventory/migrations/20260818T081243_inventory_stock_allocation_order_item_fk.js';

// ── invoices ────────────────────────────────────────────────────────────────
import { Migration20260629T125121InvoicesModule } from '../modules/invoices/migrations/20260629T125121_invoices_module.js';
import { Migration20260801T111000InvoicesGenericTemplateReseed } from '../modules/invoices/migrations/20260801T111000_invoices_generic_template_reseed.js';
import { Migration20260817T201110InvoicesCorrectionIdempotencyKey } from '../modules/invoices/migrations/20260817T201110_invoices_correction_idempotency_key.js';

// ── ksef ────────────────────────────────────────────────────────────────────
import { Migration20260722T224358KsefInit } from '../modules/ksef/migrations/20260722T224358_ksef_init.js';

// ── languages ───────────────────────────────────────────────────────────────
import { Migration20260425T161557LanguagesCurrenciesInit } from '../modules/languages/migrations/20260425T161557_languages_currencies_init.js';

// ── linkedin_ads ────────────────────────────────────────────────────────────
import { Migration20260727T233211LinkedinAdsInit } from '../modules/linkedin_ads/migrations/20260727T233211_linkedin_ads_init.js';

// ── megamenu ────────────────────────────────────────────────────────────────
import { Migration20260505T193836MegamenuInit } from '../modules/megamenu/migrations/20260505T193836_megamenu_init.js';

// ── meta_ads ────────────────────────────────────────────────────────────────
import { Migration20260728T002715MetaAdsInit } from '../modules/meta_ads/migrations/20260728T002715_meta_ads_init.js';

// ── mfa ─────────────────────────────────────────────────────────────────────
import { Migration20260611T140409MfaInit } from '../modules/mfa/migrations/20260611T140409_mfa_init.js';

// ── newsletter ──────────────────────────────────────────────────────────────
import { Migration20260629T200954NewsletterInit } from '../modules/newsletter/migrations/20260629T200954_newsletter_init.js';

// ── orders ──────────────────────────────────────────────────────────────────
import { Migration20260611T140355OrdersBusinessId } from '../modules/orders/migrations/20260611T140355_orders_business_id.js';
import { Migration20260611T140356OrdersStatusModel } from '../modules/orders/migrations/20260611T140356_orders_status_model.js';
import { Migration20260611T140357OrdersOrderCommentsAndSavedViews } from '../modules/orders/migrations/20260611T140357_orders_order_comments_and_saved_views.js';
import { Migration20260611T140401OrdersOrderStatusDefaultName } from '../modules/orders/migrations/20260611T140401_orders_order_status_default_name.js';
import { Migration20260611T140405OrdersOrderStatusColor } from '../modules/orders/migrations/20260611T140405_orders_order_status_color.js';
import { Migration20260611T140406OrdersOrderSavedViewColumns } from '../modules/orders/migrations/20260611T140406_orders_order_saved_view_columns.js';
import { Migration20260611T140414OrdersOrderItemPackaging } from '../modules/orders/migrations/20260611T140414_orders_order_item_packaging.js';
import { Migration20260618T130459OrdersOrderAppliedPromotions } from '../modules/orders/migrations/20260618T130459_orders_order_applied_promotions.js';
import { Migration20260718T200339OrdersOrderCustomFieldValues } from '../modules/orders/migrations/20260718T200339_orders_order_custom_field_values.js';
import { Migration20260724T193611OrdersOrderPlacementIntents } from '../modules/orders/migrations/20260724T193611_orders_order_placement_intents.js';
import { Migration20260804T114814OrdersShippingAdapterData } from '../modules/orders/migrations/20260804T114814_orders_shipping_adapter_data.js';

// ── organizations ───────────────────────────────────────────────────────────
import { Migration20260424T205317OrganizationsInit } from '../modules/organizations/migrations/20260424T205317_organizations_init.js';
import { Migration20260425T051700OrganizationsInvitationsInit } from '../modules/organizations/migrations/20260425T051700_organizations_invitations_init.js';
import { Migration20260611T140349OrganizationsConsolidation } from '../modules/organizations/migrations/20260611T140349_organizations_consolidation.js';
import { Migration20260611T140358OrganizationsOrgOrderConfirmationEmails } from '../modules/organizations/migrations/20260611T140358_organizations_org_order_confirmation_emails.js';
import { Migration20260611T140402OrganizationsOrgFulfilmentStrategy } from '../modules/organizations/migrations/20260611T140402_organizations_org_fulfilment_strategy.js';
import { Migration20260717T151403OrganizationsPersonalOrganizations } from '../modules/organizations/migrations/20260717T151403_organizations_personal_organizations.js';
import { Migration20260718T200340OrganizationsOrganizationCustomFieldValues } from '../modules/organizations/migrations/20260718T200340_organizations_organization_custom_field_values.js';
import { Migration20260720T044254OrganizationsOrgHierarchy } from '../modules/organizations/migrations/20260720T044254_organizations_org_hierarchy.js';

// ── payment_methods ─────────────────────────────────────────────────────────
import { Migration20260611T140353PaymentMethodsAdapter } from '../modules/payment_methods/migrations/20260611T140353_payment_methods_adapter.js';

// ── payu ────────────────────────────────────────────────────────────────────
import { Migration20260801T100943PayuInit } from '../modules/payu/migrations/20260801T100943_payu_init.js';
import { Migration20260816T053830PayuSeedPaymentMethods } from '../modules/payu/migrations/20260816T053830_payu_seed_payment_methods.js';

// ── pim_ergonode ────────────────────────────────────────────────────────────
import { Migration20260804T190439PimErgonodeInit } from '../modules/pim_ergonode/migrations/20260804T190439_pim_ergonode_init.js';
import { Migration20260819T193653PimErgonodeFoldDerivedKeys } from '../modules/pim_ergonode/migrations/20260819T193653_pim_ergonode_fold_derived_keys.js';

// ── price_lists ─────────────────────────────────────────────────────────────
import { Migration20260426T075235PriceListsPricingInit } from '../modules/price_lists/migrations/20260426T075235_price_lists_pricing_init.js';
import { Migration20260504T125655PriceListsEngine } from '../modules/price_lists/migrations/20260504T125655_price_lists_engine.js';
import { Migration20260817T055457PriceListsSingleSystemPriceList } from '../modules/price_lists/migrations/20260817T055457_price_lists_single_system_price_list.js';

// ── product_feeds ───────────────────────────────────────────────────────────
import { Migration20260802T073547ProductFeedsInit } from '../modules/product_feeds/migrations/20260802T073547_product_feeds_init.js';
import { Migration20260802T073627ProductFeedsRuns } from '../modules/product_feeds/migrations/20260802T073627_product_feeds_runs.js';
import { Migration20260802T110630ProductFeedsTaxonomies } from '../modules/product_feeds/migrations/20260802T110630_product_feeds_taxonomies.js';
import { Migration20260803T060153ProductFeedsTaxonomyRefresh } from '../modules/product_feeds/migrations/20260803T060153_product_feeds_taxonomy_refresh.js';
import { Migration20260804T152741ProductFeedsWidenIssueSku } from '../modules/product_feeds/migrations/20260804T152741_product_feeds_widen_issue_sku.js';
import { Migration20260806T105956ProductFeedsFeedTokenSecret } from '../modules/product_feeds/migrations/20260806T105956_product_feeds_feed_token_secret.js';
import { Migration20260806T125806ProductFeedsDelivery } from '../modules/product_feeds/migrations/20260806T125806_product_feeds_delivery.js';

// ── promotions ──────────────────────────────────────────────────────────────
import { Migration20260505T074605PromotionsCriteria } from '../modules/promotions/migrations/20260505T074605_promotions_criteria.js';
import { Migration20260618T100727PromotionsEngine } from '../modules/promotions/migrations/20260618T100727_promotions_engine.js';
import { Migration20260818T081251PromotionsPromotionUsageOrderFk } from '../modules/promotions/migrations/20260818T081251_promotions_promotion_usage_order_fk.js';

// ── prompt_actions ──────────────────────────────────────────────────────────
import { Migration20260611T140410PromptActionsInit } from '../modules/prompt_actions/migrations/20260611T140410_prompt_actions_init.js';

// ── pwa ─────────────────────────────────────────────────────────────────────
import { Migration20260625T144228PwaInit } from '../modules/pwa/migrations/20260625T144228_pwa_init.js';

// ── quick_order ─────────────────────────────────────────────────────────────
import { Migration20260611T140359QuickOrderDefaultPreferences } from '../modules/quick_order/migrations/20260611T140359_quick_order_default_preferences.js';

// ── quote_requests ──────────────────────────────────────────────────────────
import { Migration20260424T190112QuoteRequestsInit } from '../modules/quote_requests/migrations/20260424T190112_quote_requests_init.js';
import { Migration20260503T141344QuoteRequestsWorkflow } from '../modules/quote_requests/migrations/20260503T141344_quote_requests_workflow.js';
import { Migration20260611T140415QuoteRequestsQrItemPackaging } from '../modules/quote_requests/migrations/20260611T140415_quote_requests_qr_item_packaging.js';
import { Migration20260611T140417QuoteRequestsBusinessId } from '../modules/quote_requests/migrations/20260611T140417_quote_requests_business_id.js';
import { Migration20260617T095510QuoteRequestsBackfillAdminCreatedAwaiting } from '../modules/quote_requests/migrations/20260617T095510_quote_requests_backfill_admin_created_awaiting.js';
import { Migration20260718T200342QuoteRequestsQuoteRequestCustomFieldValues } from '../modules/quote_requests/migrations/20260718T200342_quote_requests_quote_request_custom_field_values.js';

// ── returns ─────────────────────────────────────────────────────────────────
import { Migration20260625T144227ReturnsInit } from '../modules/returns/migrations/20260625T144227_returns_init.js';
import { Migration20260817T203206ReturnsRefundCorrectiveInvoiceOutcome } from '../modules/returns/migrations/20260817T203206_returns_refund_corrective_invoice_outcome.js';

// ── search ──────────────────────────────────────────────────────────────────
import { Migration20260501T123145SearchPhraseRecordsInit } from '../modules/search/migrations/20260501T123145_search_phrase_records_init.js';

// ── seo ─────────────────────────────────────────────────────────────────────
import { Migration20260425T154404SeoInit } from '../modules/seo/migrations/20260425T154404_seo_init.js';

// ── shipments ───────────────────────────────────────────────────────────────
import { Migration20260817T194652ShipmentsOrderFk } from '../modules/shipments/migrations/20260817T194652_shipments_order_fk.js';
import { Migration20260819T171006ShipmentsStatusPendingManual } from '../modules/shipments/migrations/20260819T171006_shipments_status_pending_manual.js';

// ── shopping_lists ──────────────────────────────────────────────────────────
import { Migration20260426T135443ShoppingListsInit } from '../modules/shopping_lists/migrations/20260426T135443_shopping_lists_init.js';
import { Migration20260611T140418ShoppingListsDefault } from '../modules/shopping_lists/migrations/20260611T140418_shopping_lists_default.js';

// ── stripe ──────────────────────────────────────────────────────────────────
import { Migration20260708T101135StripeInit } from '../modules/stripe/migrations/20260708T101135_stripe_init.js';
import { Migration20260715T103358StripePaymentRefundedAmount } from '../modules/stripe/migrations/20260715T103358_stripe_payment_refunded_amount.js';
import { Migration20260816T053826StripeSeedPaymentMethods } from '../modules/stripe/migrations/20260816T053826_stripe_seed_payment_methods.js';

// ── taxes ───────────────────────────────────────────────────────────────────
import { Migration20260426T081516TaxesPromotionsInit } from '../modules/taxes/migrations/20260426T081516_taxes_promotions_init.js';

// ── tpay ────────────────────────────────────────────────────────────────────
import { Migration20260729T132507TpayInit } from '../modules/tpay/migrations/20260729T132507_tpay_init.js';
import { Migration20260816T053834TpaySeedPaymentMethods } from '../modules/tpay/migrations/20260816T053834_tpay_seed_payment_methods.js';

// ── transactional_emails ────────────────────────────────────────────────────
import { Migration20260629T113442TransactionalEmailsInit } from '../modules/transactional_emails/migrations/20260629T113442_transactional_emails_init.js';
import { Migration20260801T111001TransactionalEmailsEmailDefaultsReseed } from '../modules/transactional_emails/migrations/20260801T111001_transactional_emails_email_defaults_reseed.js';

// ── webhooks ────────────────────────────────────────────────────────────────
import { Migration20260425T091359WebhooksUs7Init } from '../modules/webhooks/migrations/20260425T091359_webhooks_us7_init.js';
import { Migration20260724T203140WebhooksOrgFilter } from '../modules/webhooks/migrations/20260724T203140_webhooks_org_filter.js';
import { Migration20260727T200555WebhooksDropExternalIntegrations } from '../modules/webhooks/migrations/20260727T200555_webhooks_drop_external_integrations.js';

export type { MigrationClass, MigrationRegistryEntry };

/** One-line helper: the migration name is always `cls.name`, never hand-written. */
function migration(moduleId: string, cls: MigrationClass): MigrationRegistryEntry {
  return { moduleId, cls };
}

export const MIGRATION_REGISTRY: readonly MigrationRegistryEntry[] = [
  // ── _i18n ───────────────────────────────────────────────────────────────────
  migration('_i18n', Migration20260507T091405I18nAdminI18nInit),

  // ── admin_actions ───────────────────────────────────────────────────────────
  migration('admin_actions', Migration20260507T142354AdminActionsInit),

  // ── admin_notifications ─────────────────────────────────────────────────────
  migration('admin_notifications', Migration20260611T140350AdminNotificationsInit),

  // ── admin_users ─────────────────────────────────────────────────────────────
  migration('admin_users', Migration20260425T053028AdminUsersInit),
  migration('admin_users', Migration20260819T155150AdminUsersFoldEmailCase),

  // ── analytics ───────────────────────────────────────────────────────────────
  migration('analytics', Migration20260425T143139AnalyticsInit),

  // ── api_keys ────────────────────────────────────────────────────────────────
  migration('api_keys', Migration20260724T173916ApiKeysDistributorBinding),

  // ── assets_library ──────────────────────────────────────────────────────────
  migration('assets_library', Migration20260505T102206AssetsLibraryInit),

  // ── autopay ─────────────────────────────────────────────────────────────────
  migration('autopay', Migration20260803T065409AutopayInit),
  migration('autopay', Migration20260816T053835AutopaySeedPaymentMethods),

  // ── blog ────────────────────────────────────────────────────────────────────
  migration('blog', Migration20260506T081055BlogInit),

  // ── carts ───────────────────────────────────────────────────────────────────
  migration('carts', Migration20260611T140352CartsConsolidation),
  migration('carts', Migration20260611T140413CartsCartItemPackaging),
  migration('carts', Migration20260818T081253CartsCartCompletedOrderFk),

  // ── catalog ─────────────────────────────────────────────────────────────────
  migration('catalog', Migration20260429T064146CatalogAttributeSetsInit),
  migration('catalog', Migration20260429T070004CatalogProductAttributeExtensions),
  migration('catalog', Migration20260429T102322CatalogProductTypeAndVirtualFields),
  migration('catalog', Migration20260429T111839CatalogGalleryItemsAndLabels),
  migration('catalog', Migration20260429T112543CatalogProductAttachments),
  migration('catalog', Migration20260429T123726CatalogProductLinks),
  migration('catalog', Migration20260429T130803CatalogGroupedAndBundle),
  migration('catalog', Migration20260501T185835CatalogProductAttributeIsComparable),
  migration('catalog', Migration20260505T060113CatalogAttributeOptionsAndFlags),
  migration('catalog', Migration20260515T082629CatalogAttributeMassEditable),
  migration('catalog', Migration20260526T124736CatalogProductStatusInactive),
  migration('catalog', Migration20260611T140346CatalogProductValueOverridesInit),
  migration('catalog', Migration20260611T140400CatalogAttributeQuickSearchable),
  migration('catalog', Migration20260611T140407CatalogBulkOperations),
  migration('catalog', Migration20260611T140408CatalogBulkOperationLogs),
  migration('catalog', Migration20260611T140412CatalogProductPackagingUnits),
  migration('catalog', Migration20260718T060659CatalogBulkOperationRevertState),
  migration('catalog', Migration20260718T200343CatalogCategoryCustomFieldValues),
  migration('catalog', Migration20260723T230401CatalogAttributesOnCustomFields),
  migration('catalog', Migration20260804T152604CatalogWidenProductSku),
  migration('catalog', Migration20260804T160244CatalogCategoryActivation),

  // ── cms ─────────────────────────────────────────────────────────────────────
  migration('cms', Migration20260425T162418CmsPagesInit),
  migration('cms', Migration20260505T130214CmsInit),

  // ── comparisons ─────────────────────────────────────────────────────────────
  migration('comparisons', Migration20260501T185834ComparisonsInit),

  // ── core ────────────────────────────────────────────────────────────────────
  migration('core', Migration20260424T165847CoreFoundationInit),
  migration('core', Migration20260425T050720CoreCommerceInit),
  migration('core', Migration20260430T101450CoreSettingsInit),
  migration('core', Migration20260430T170044CoreSalesChannelsPromote),
  migration('core', Migration20260506T200657CoreModuleLifecycleInit),
  migration('core', Migration20260514T111329CoreSettingsGlobalValue),
  migration('core', Migration20260611T140411CoreSettingsSecretValueType),
  migration('core', Migration20260611T140419CoreSettingsEnumOptions),
  migration('core', Migration20260629T090100CoreSettingsHiddenFlag),
  migration('core', Migration20260717T134752CoreTenantScopeIndexes),
  migration('core', Migration20260721T011510CoreSettingsCredentialRefValueType),
  migration('core', Migration20260816T203339CoreRetireCoreActivationSettings),

  // ── credentials ─────────────────────────────────────────────────────────────
  migration('credentials', Migration20260721T011509CredentialsInit),

  // ── credit_limits ───────────────────────────────────────────────────────────
  migration('credit_limits', Migration20260425T063333CreditLimitsInit),
  migration('credit_limits', Migration20260817T201111CreditLimitsReturnTopups),
  migration('credit_limits', Migration20260818T081252CreditLimitsCreditLimitReservationOrderFk),

  // ── custom_fields ───────────────────────────────────────────────────────────
  migration('custom_fields', Migration20260718T200338CustomFieldsInit),

  // ── customer_accounts ───────────────────────────────────────────────────────
  migration('customer_accounts', Migration20260425T055041CustomerAccountsPasswordResetTokens),
  migration('customer_accounts', Migration20260611T140351CustomerAccountsOrganizationOptional),
  migration('customer_accounts', Migration20260611T140403CustomerAccountsLifecycle),
  migration('customer_accounts', Migration20260718T200341CustomerAccountsCustomerAccountCustomFieldValues),
  migration('customer_accounts', Migration20260720T044255CustomerAccountsCustomerSubtreeRollup),
  migration('customer_accounts', Migration20260819T074816CustomerAccountsPasswordSetAt),
  migration('customer_accounts', Migration20260819T142837CustomerAccountsFoldEmailCase),

  // ── customers ───────────────────────────────────────────────────────────────
  migration('customers', Migration20260611T140404CustomersCustomerAddressesInit),

  // ── delivery_methods ────────────────────────────────────────────────────────
  migration('delivery_methods', Migration20260611T140354DeliveryMethodsShippingMethodsAdapterAndShipments),
  migration('delivery_methods', Migration20260611T140416DeliveryMethodsFixInPersonPickupAdapter),

  // ── dictionaries ────────────────────────────────────────────────────────────
  migration('dictionaries', Migration20260506T112634DictionariesDictionaryInit),

  // ── email ───────────────────────────────────────────────────────────────────
  migration('email', Migration20260817T070014EmailDeliveryRecord),

  // ── google_analytics ────────────────────────────────────────────────────────
  migration('google_analytics', Migration20260715T171116GoogleAnalyticsInit),

  // ── inpost ──────────────────────────────────────────────────────────────────
  migration('inpost', Migration20260821T150748InpostWebhookEventsAndShipmentLinks),

  // ── inventory ───────────────────────────────────────────────────────────────
  migration('inventory', Migration20260503T182812InventoryWorkflow),
  migration('inventory', Migration20260611T140347InventoryWarehouseDefaultLowStockThreshold),
  migration('inventory', Migration20260611T140348InventoryPerWarehouseLowStockThresholds),
  migration('inventory', Migration20260818T081243InventoryStockAllocationOrderItemFk),

  // ── invoices ────────────────────────────────────────────────────────────────
  migration('invoices', Migration20260629T125121InvoicesModule),
  migration('invoices', Migration20260801T111000InvoicesGenericTemplateReseed),
  migration('invoices', Migration20260817T201110InvoicesCorrectionIdempotencyKey),

  // ── ksef ────────────────────────────────────────────────────────────────────
  migration('ksef', Migration20260722T224358KsefInit),

  // ── languages ───────────────────────────────────────────────────────────────
  migration('languages', Migration20260425T161557LanguagesCurrenciesInit),

  // ── linkedin_ads ────────────────────────────────────────────────────────────
  migration('linkedin_ads', Migration20260727T233211LinkedinAdsInit),

  // ── megamenu ────────────────────────────────────────────────────────────────
  migration('megamenu', Migration20260505T193836MegamenuInit),

  // ── meta_ads ────────────────────────────────────────────────────────────────
  migration('meta_ads', Migration20260728T002715MetaAdsInit),

  // ── mfa ─────────────────────────────────────────────────────────────────────
  migration('mfa', Migration20260611T140409MfaInit),

  // ── newsletter ──────────────────────────────────────────────────────────────
  migration('newsletter', Migration20260629T200954NewsletterInit),

  // ── orders ──────────────────────────────────────────────────────────────────
  migration('orders', Migration20260611T140355OrdersBusinessId),
  migration('orders', Migration20260611T140356OrdersStatusModel),
  migration('orders', Migration20260611T140357OrdersOrderCommentsAndSavedViews),
  migration('orders', Migration20260611T140401OrdersOrderStatusDefaultName),
  migration('orders', Migration20260611T140405OrdersOrderStatusColor),
  migration('orders', Migration20260611T140406OrdersOrderSavedViewColumns),
  migration('orders', Migration20260611T140414OrdersOrderItemPackaging),
  migration('orders', Migration20260618T130459OrdersOrderAppliedPromotions),
  migration('orders', Migration20260718T200339OrdersOrderCustomFieldValues),
  migration('orders', Migration20260724T193611OrdersOrderPlacementIntents),
  migration('orders', Migration20260804T114814OrdersShippingAdapterData),

  // ── organizations ───────────────────────────────────────────────────────────
  migration('organizations', Migration20260424T205317OrganizationsInit),
  migration('organizations', Migration20260425T051700OrganizationsInvitationsInit),
  migration('organizations', Migration20260611T140349OrganizationsConsolidation),
  migration('organizations', Migration20260611T140358OrganizationsOrgOrderConfirmationEmails),
  migration('organizations', Migration20260611T140402OrganizationsOrgFulfilmentStrategy),
  migration('organizations', Migration20260717T151403OrganizationsPersonalOrganizations),
  migration('organizations', Migration20260718T200340OrganizationsOrganizationCustomFieldValues),
  migration('organizations', Migration20260720T044254OrganizationsOrgHierarchy),

  // ── payment_methods ─────────────────────────────────────────────────────────
  migration('payment_methods', Migration20260611T140353PaymentMethodsAdapter),

  // ── payu ────────────────────────────────────────────────────────────────────
  migration('payu', Migration20260801T100943PayuInit),
  migration('payu', Migration20260816T053830PayuSeedPaymentMethods),

  // ── pim_ergonode ────────────────────────────────────────────────────────────
  migration('pim_ergonode', Migration20260804T190439PimErgonodeInit),
  migration('pim_ergonode', Migration20260819T193653PimErgonodeFoldDerivedKeys),

  // ── price_lists ─────────────────────────────────────────────────────────────
  migration('price_lists', Migration20260426T075235PriceListsPricingInit),
  migration('price_lists', Migration20260504T125655PriceListsEngine),
  migration('price_lists', Migration20260817T055457PriceListsSingleSystemPriceList),

  // ── product_feeds ───────────────────────────────────────────────────────────
  migration('product_feeds', Migration20260802T073547ProductFeedsInit),
  migration('product_feeds', Migration20260802T073627ProductFeedsRuns),
  migration('product_feeds', Migration20260802T110630ProductFeedsTaxonomies),
  migration('product_feeds', Migration20260803T060153ProductFeedsTaxonomyRefresh),
  migration('product_feeds', Migration20260804T152741ProductFeedsWidenIssueSku),
  migration('product_feeds', Migration20260806T105956ProductFeedsFeedTokenSecret),
  migration('product_feeds', Migration20260806T125806ProductFeedsDelivery),

  // ── promotions ──────────────────────────────────────────────────────────────
  migration('promotions', Migration20260505T074605PromotionsCriteria),
  migration('promotions', Migration20260618T100727PromotionsEngine),
  migration('promotions', Migration20260818T081251PromotionsPromotionUsageOrderFk),

  // ── prompt_actions ──────────────────────────────────────────────────────────
  migration('prompt_actions', Migration20260611T140410PromptActionsInit),

  // ── pwa ─────────────────────────────────────────────────────────────────────
  migration('pwa', Migration20260625T144228PwaInit),

  // ── quick_order ─────────────────────────────────────────────────────────────
  migration('quick_order', Migration20260611T140359QuickOrderDefaultPreferences),

  // ── quote_requests ──────────────────────────────────────────────────────────
  migration('quote_requests', Migration20260424T190112QuoteRequestsInit),
  migration('quote_requests', Migration20260503T141344QuoteRequestsWorkflow),
  migration('quote_requests', Migration20260611T140415QuoteRequestsQrItemPackaging),
  migration('quote_requests', Migration20260611T140417QuoteRequestsBusinessId),
  migration('quote_requests', Migration20260617T095510QuoteRequestsBackfillAdminCreatedAwaiting),
  migration('quote_requests', Migration20260718T200342QuoteRequestsQuoteRequestCustomFieldValues),

  // ── returns ─────────────────────────────────────────────────────────────────
  migration('returns', Migration20260625T144227ReturnsInit),
  migration('returns', Migration20260817T203206ReturnsRefundCorrectiveInvoiceOutcome),

  // ── search ──────────────────────────────────────────────────────────────────
  migration('search', Migration20260501T123145SearchPhraseRecordsInit),

  // ── seo ─────────────────────────────────────────────────────────────────────
  migration('seo', Migration20260425T154404SeoInit),

  // ── shipments ───────────────────────────────────────────────────────────────
  migration('shipments', Migration20260817T194652ShipmentsOrderFk),
  migration('shipments', Migration20260819T171006ShipmentsStatusPendingManual),

  // ── shopping_lists ──────────────────────────────────────────────────────────
  migration('shopping_lists', Migration20260426T135443ShoppingListsInit),
  migration('shopping_lists', Migration20260611T140418ShoppingListsDefault),

  // ── stripe ──────────────────────────────────────────────────────────────────
  migration('stripe', Migration20260708T101135StripeInit),
  migration('stripe', Migration20260715T103358StripePaymentRefundedAmount),
  migration('stripe', Migration20260816T053826StripeSeedPaymentMethods),

  // ── taxes ───────────────────────────────────────────────────────────────────
  migration('taxes', Migration20260426T081516TaxesPromotionsInit),

  // ── tpay ────────────────────────────────────────────────────────────────────
  migration('tpay', Migration20260729T132507TpayInit),
  migration('tpay', Migration20260816T053834TpaySeedPaymentMethods),

  // ── transactional_emails ────────────────────────────────────────────────────
  migration('transactional_emails', Migration20260629T113442TransactionalEmailsInit),
  migration('transactional_emails', Migration20260801T111001TransactionalEmailsEmailDefaultsReseed),

  // ── webhooks ────────────────────────────────────────────────────────────────
  migration('webhooks', Migration20260425T091359WebhooksUs7Init),
  migration('webhooks', Migration20260724T203140WebhooksOrgFilter),
  migration('webhooks', Migration20260727T200555WebhooksDropExternalIntegrations),
];
