// AUTO-GENERATED by scripts/generate-divergence.ts — DO NOT EDIT.
// Run `pnpm --filter backend run overlay:divergence` (or rebuild) to refresh.
// Deterministic record of this deployment's divergence from core.

import type { DivergenceReport } from '../../overlay/types.js';

export const DIVERGENCE_REPORT: DivergenceReport = {
  "deployment": "acceptance",
  "generatedFrom": {
    "overlayRoot": "backend/src/apps/acceptance/modules"
  },
  "overlayModules": [
    "acceptance_overlay"
  ],
  "entries": [
    {
      "key": "decoration:acceptance_overlay:acceptanceProbeGreeter",
      "kind": "decoration",
      "module": "acceptance_overlay",
      "subject": "acceptanceProbeGreeter",
      "owner": "acceptance_probe",
      "rung": 4,
      "detail": {
        "kind": "decoration",
        "depth": null
      },
      "reason": "Core hands every consumer the greeter that `@endora-commerce/mod-acceptance-probe` — an installed extension package — registers. This deployment wraps it, delegating, so that the acceptance criterion can measure what the platform does when an overlay module reaches for a registration an installed package owns. The answer is `PackageDecorationNotOfferedError` (D-176 Q3): the wrap is expected to be refused, and the refusal is what A10 asserts. It stays because deleting it would delete the reach that makes the refusal measurable."
    }
  ],
  "boundary": {
    "recorded": [
      "decoration",
      "interceptor",
      "omission",
      "port-consumed",
      "port-provided",
      "registration",
      "root-plugin",
      "subscription",
      "worker"
    ],
    "notRecorded": [
      {
        "seam": "ctx.onBoot",
        "why": "the module's own boot hook, run inside its own system scope; it contributes nothing another module resolves"
      },
      {
        "seam": "ctx.routes",
        "why": "a route an overlay module registers is its own route, gated on its own module — not a change to what core serves"
      },
      {
        "seam": "ctx.ungatedRoutes",
        "why": "the module's own route, outside the module's own gate; the reason string is required at the call and is read there, and it removes no other module's gate"
      },
      {
        "seam": "manifest.ts declarations (permissions, palette actions, i18n bundles, CLI commands)",
        "why": "each is a module declaring its own surface, and each is already swept by the instrument that owns it — the permission inventory, the bundle-shape test, the action-route check"
      }
    ],
    "runtimeOnly": [
      {
        "fact": "an installed extension package's interceptors and subscriptions",
        "why": "a package is discovered at run time and ships compiled output; what it registers is a fact about a process, not about this tree. An installed package cannot decorate at all (D-156.3), which is what keeps the highest-value seam inside this artefact"
      },
      {
        "fact": "the operator's activation choices",
        "why": "presence is the conjunction of two orthogonal axes (Principle XVII), and activation is a Setting in the store. Whether a divergence recorded here is live is the running instance’s answer, and a build-time artefact gating on it would be the shape D-67/D-68 refuse"
      },
      {
        "fact": "whether each decoration applied, and at what depth",
        "why": "depth is a fact about a composition rather than about a tree: which wrap went innermost is what `decorationOrder` and the composer’s emission order decide together. `detail.depth` is `null` here rather than guessed"
      }
    ]
  }
};
