// AUTO-GENERATED by scripts/generate-override-manifest.ts — DO NOT EDIT.
// Run `pnpm --filter backend run overlay:manifest` (or rebuild) to refresh.
// Deterministic audit artifact of this deployment's divergence from core.

import type { OverrideManifest } from '../../overlay/types.js';

export const OVERRIDE_MANIFEST: OverrideManifest = {
  "deployment": "acceptance",
  "generatedFrom": {
    "coreRoot": "backend/src/modules",
    "overlayRoot": "backend/src/apps/acceptance/modules"
  },
  "overrides": [],
  "newModules": [
    "acceptance_overlay"
  ]
};
