// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// Every **core** module that ships a `backend.ts` exporting `registerModule`,
// in the order a composition root must compose them:
//
//   1. `api_keys` first — a **construction** dependency, not a manifest one:
//      the API-key authenticator is injected into the auth plugin, and
//      `api_keys`' manifest declares nothing about `auth`. Pinned here, in the
//      open, until F3 fixes the declaration.
//   2. then a topological order over `manifest.dependencies`, ties broken
//      alphabetically so this file is a function of the tree and nothing else.
//
// This list is bare core under every value of `DEPLOYMENT` (D-104). A
// deployment's overlay modules are discovered at runtime by
// `loadOverlayModuleEntries` (`src/overlay/overlay-runtime.ts`) and **appended**
// to this list in the one `composeModules` call, which is what makes "overlay
// last, so a deployment's `di.decorate` wins" structural rather than a property
// of this generator's sort — and what keeps this committed artefact meaning the
// same thing in every environment.
//
// A module missing from this list is a module the tree walk found no
// `backend.ts` for. Every core module exports `registerModule` today, so an
// absence here means a file was not written or not named `backend.ts` — not
// that the module is composed somewhere else.

import type { ModuleEntry } from './kernel/compose.js';

import * as module0 from './modules/_lifecycle/backend.js';
import { manifest as manifest0 } from './modules/_lifecycle/manifest.js';
import * as module1 from './modules/admin_roles/backend.js';
import { manifest as manifest1 } from './modules/admin_roles/manifest.js';
import * as module2 from './modules/auth/backend.js';
import { manifest as manifest2 } from './modules/auth/manifest.js';
import * as module3 from './modules/admin_users/backend.js';
import { manifest as manifest3 } from './modules/admin_users/manifest.js';
import * as module4 from './modules/_i18n/backend.js';
import { manifest as manifest4 } from './modules/_i18n/manifest.js';
import * as module5 from './modules/admin_actions/backend.js';
import { manifest as manifest5 } from './modules/admin_actions/manifest.js';
import * as module6 from './modules/admin_notifications/backend.js';
import { manifest as manifest6 } from './modules/admin_notifications/manifest.js';
import * as module7 from './modules/analytics/backend.js';
import { manifest as manifest7 } from './modules/analytics/manifest.js';
import * as module8 from './modules/assets_library/backend.js';
import { manifest as manifest8 } from './modules/assets_library/manifest.js';
import * as module9 from './modules/audit_logs/backend.js';
import { manifest as manifest9 } from './modules/audit_logs/manifest.js';
import * as module10 from './modules/currencies/backend.js';
import { manifest as manifest10 } from './modules/currencies/manifest.js';
import * as module11 from './modules/custom_fields/backend.js';
import { manifest as manifest11 } from './modules/custom_fields/manifest.js';
import * as module12 from './modules/email/backend.js';
import { manifest as manifest12 } from './modules/email/manifest.js';
import * as module13 from './modules/health_checks/backend.js';
import { manifest as manifest13 } from './modules/health_checks/manifest.js';
import * as module14 from './modules/import_export/backend.js';
import { manifest as manifest14 } from './modules/import_export/manifest.js';
import * as module15 from './modules/languages/backend.js';
import { manifest as manifest15 } from './modules/languages/manifest.js';
import * as module16 from './modules/dictionaries/backend.js';
import { manifest as manifest16 } from './modules/dictionaries/manifest.js';
import * as module17 from './modules/settings/backend.js';
import { manifest as manifest17 } from './modules/settings/manifest.js';
import * as module18 from './modules/credentials/backend.js';
import { manifest as manifest18 } from './modules/credentials/manifest.js';
import * as module19 from './modules/prompt_actions/backend.js';
import { manifest as manifest19 } from './modules/prompt_actions/manifest.js';
import * as module20 from './modules/sales_channels/backend.js';
import { manifest as manifest20 } from './modules/sales_channels/manifest.js';
import * as module21 from './modules/catalog/backend.js';
import { manifest as manifest21 } from './modules/catalog/manifest.js';
import * as module22 from './modules/cms/backend.js';
import { manifest as manifest22 } from './modules/cms/manifest.js';
import * as module23 from './modules/blog/backend.js';
import { manifest as manifest23 } from './modules/blog/manifest.js';
import * as module24 from './modules/google_analytics/backend.js';
import { manifest as manifest24 } from './modules/google_analytics/manifest.js';
import * as module25 from './modules/google_tag_manager/backend.js';
import { manifest as manifest25 } from './modules/google_tag_manager/manifest.js';
import * as module26 from './modules/linkedin_ads/backend.js';
import { manifest as manifest26 } from './modules/linkedin_ads/manifest.js';
import * as module27 from './modules/megamenu/backend.js';
import { manifest as manifest27 } from './modules/megamenu/manifest.js';
import * as module28 from './modules/meta_ads/backend.js';
import { manifest as manifest28 } from './modules/meta_ads/manifest.js';
import * as module29 from './modules/seo/backend.js';
import { manifest as manifest29 } from './modules/seo/manifest.js';
import * as module30 from './modules/taxes/backend.js';
import { manifest as manifest30 } from './modules/taxes/manifest.js';
import * as module31 from './modules/transactional_emails/backend.js';
import { manifest as manifest31 } from './modules/transactional_emails/manifest.js';
import * as module32 from './modules/organizations/backend.js';
import { manifest as manifest32 } from './modules/organizations/manifest.js';
import * as module33 from './modules/addresses/backend.js';
import { manifest as manifest33 } from './modules/addresses/manifest.js';
import * as module34 from './modules/customer_accounts/backend.js';
import { manifest as manifest34 } from './modules/customer_accounts/manifest.js';
import * as module35 from './modules/api_keys/backend.js';
import { manifest as manifest35 } from './modules/api_keys/manifest.js';
import * as module36 from './modules/delivery_methods/backend.js';
import { manifest as manifest36 } from './modules/delivery_methods/manifest.js';
import * as module37 from './modules/mfa/backend.js';
import { manifest as manifest37 } from './modules/mfa/manifest.js';
import * as module38 from './modules/payment_methods/backend.js';
import { manifest as manifest38 } from './modules/payment_methods/manifest.js';
import * as module39 from './modules/price_lists/backend.js';
import { manifest as manifest39 } from './modules/price_lists/manifest.js';
import * as module40 from './modules/comparisons/backend.js';
import { manifest as manifest40 } from './modules/comparisons/manifest.js';
import * as module41 from './modules/orders/backend.js';
import { manifest as manifest41 } from './modules/orders/manifest.js';
import * as module42 from './modules/credit_limits/backend.js';
import { manifest as manifest42 } from './modules/credit_limits/manifest.js';
import * as module43 from './modules/inventory/backend.js';
import { manifest as manifest43 } from './modules/inventory/manifest.js';
import * as module44 from './modules/invoices/backend.js';
import { manifest as manifest44 } from './modules/invoices/manifest.js';
import * as module45 from './modules/ksef/backend.js';
import { manifest as manifest45 } from './modules/ksef/manifest.js';
import * as module46 from './modules/payments/backend.js';
import { manifest as manifest46 } from './modules/payments/manifest.js';
import * as module47 from './modules/pim_ergonode/backend.js';
import { manifest as manifest47 } from './modules/pim_ergonode/manifest.js';
import * as module48 from './modules/product_feeds/backend.js';
import { manifest as manifest48 } from './modules/product_feeds/manifest.js';
import * as module49 from './modules/promotions/backend.js';
import { manifest as manifest49 } from './modules/promotions/manifest.js';
import * as module50 from './modules/pwa/backend.js';
import { manifest as manifest50 } from './modules/pwa/manifest.js';
import * as module51 from './modules/quote_requests/backend.js';
import { manifest as manifest51 } from './modules/quote_requests/manifest.js';
import * as module52 from './modules/carts/backend.js';
import { manifest as manifest52 } from './modules/carts/manifest.js';
import * as module53 from './modules/quick_order/backend.js';
import { manifest as manifest53 } from './modules/quick_order/manifest.js';
import * as module54 from './modules/customers/backend.js';
import { manifest as manifest54 } from './modules/customers/manifest.js';
import * as module55 from './modules/newsletter/backend.js';
import { manifest as manifest55 } from './modules/newsletter/manifest.js';
import * as module56 from './modules/returns/backend.js';
import { manifest as manifest56 } from './modules/returns/manifest.js';
import * as module57 from './modules/autopay/backend.js';
import { manifest as manifest57 } from './modules/autopay/manifest.js';
import * as module58 from './modules/paypal/backend.js';
import { manifest as manifest58 } from './modules/paypal/manifest.js';
import * as module59 from './modules/payu/backend.js';
import { manifest as manifest59 } from './modules/payu/manifest.js';
import * as module60 from './modules/search/backend.js';
import { manifest as manifest60 } from './modules/search/manifest.js';
import * as module61 from './modules/shipments/backend.js';
import { manifest as manifest61 } from './modules/shipments/manifest.js';
import * as module62 from './modules/shopping_lists/backend.js';
import { manifest as manifest62 } from './modules/shopping_lists/manifest.js';
import * as module63 from './modules/stripe/backend.js';
import { manifest as manifest63 } from './modules/stripe/manifest.js';
import * as module64 from './modules/tpay/backend.js';
import { manifest as manifest64 } from './modules/tpay/manifest.js';
import * as module65 from './modules/webhooks/backend.js';
import { manifest as manifest65 } from './modules/webhooks/manifest.js';

export const MODULES: readonly ModuleEntry[] = [
  { id: '_lifecycle', version: manifest0.version, registerModule: module0.registerModule },
  { id: 'admin_roles', version: manifest1.version, registerModule: module1.registerModule },
  { id: 'auth', version: manifest2.version, registerModule: module2.registerModule },
  { id: 'admin_users', version: manifest3.version, registerModule: module3.registerModule },
  { id: '_i18n', version: manifest4.version, registerModule: module4.registerModule },
  { id: 'admin_actions', version: manifest5.version, registerModule: module5.registerModule },
  { id: 'admin_notifications', version: manifest6.version, registerModule: module6.registerModule },
  { id: 'analytics', version: manifest7.version, registerModule: module7.registerModule },
  { id: 'assets_library', version: manifest8.version, registerModule: module8.registerModule },
  { id: 'audit_logs', version: manifest9.version, registerModule: module9.registerModule },
  { id: 'currencies', version: manifest10.version, registerModule: module10.registerModule },
  { id: 'custom_fields', version: manifest11.version, registerModule: module11.registerModule },
  { id: 'email', version: manifest12.version, registerModule: module12.registerModule },
  { id: 'health_checks', version: manifest13.version, registerModule: module13.registerModule },
  { id: 'import_export', version: manifest14.version, registerModule: module14.registerModule },
  { id: 'languages', version: manifest15.version, registerModule: module15.registerModule },
  { id: 'dictionaries', version: manifest16.version, registerModule: module16.registerModule },
  { id: 'settings', version: manifest17.version, registerModule: module17.registerModule },
  { id: 'credentials', version: manifest18.version, registerModule: module18.registerModule },
  { id: 'prompt_actions', version: manifest19.version, registerModule: module19.registerModule },
  { id: 'sales_channels', version: manifest20.version, registerModule: module20.registerModule },
  { id: 'catalog', version: manifest21.version, registerModule: module21.registerModule },
  { id: 'cms', version: manifest22.version, registerModule: module22.registerModule },
  { id: 'blog', version: manifest23.version, registerModule: module23.registerModule },
  { id: 'google_analytics', version: manifest24.version, registerModule: module24.registerModule },
  { id: 'google_tag_manager', version: manifest25.version, registerModule: module25.registerModule },
  { id: 'linkedin_ads', version: manifest26.version, registerModule: module26.registerModule },
  { id: 'megamenu', version: manifest27.version, registerModule: module27.registerModule },
  { id: 'meta_ads', version: manifest28.version, registerModule: module28.registerModule },
  { id: 'seo', version: manifest29.version, registerModule: module29.registerModule },
  { id: 'taxes', version: manifest30.version, registerModule: module30.registerModule },
  { id: 'transactional_emails', version: manifest31.version, registerModule: module31.registerModule },
  { id: 'organizations', version: manifest32.version, registerModule: module32.registerModule },
  { id: 'addresses', version: manifest33.version, registerModule: module33.registerModule },
  { id: 'customer_accounts', version: manifest34.version, registerModule: module34.registerModule },
  { id: 'api_keys', version: manifest35.version, registerModule: module35.registerModule },
  { id: 'delivery_methods', version: manifest36.version, registerModule: module36.registerModule },
  { id: 'mfa', version: manifest37.version, registerModule: module37.registerModule },
  { id: 'payment_methods', version: manifest38.version, registerModule: module38.registerModule },
  { id: 'price_lists', version: manifest39.version, registerModule: module39.registerModule },
  { id: 'comparisons', version: manifest40.version, registerModule: module40.registerModule },
  { id: 'orders', version: manifest41.version, registerModule: module41.registerModule },
  { id: 'credit_limits', version: manifest42.version, registerModule: module42.registerModule },
  { id: 'inventory', version: manifest43.version, registerModule: module43.registerModule },
  { id: 'invoices', version: manifest44.version, registerModule: module44.registerModule },
  { id: 'ksef', version: manifest45.version, registerModule: module45.registerModule },
  { id: 'payments', version: manifest46.version, registerModule: module46.registerModule },
  { id: 'pim_ergonode', version: manifest47.version, registerModule: module47.registerModule },
  { id: 'product_feeds', version: manifest48.version, registerModule: module48.registerModule },
  { id: 'promotions', version: manifest49.version, registerModule: module49.registerModule },
  { id: 'pwa', version: manifest50.version, registerModule: module50.registerModule },
  { id: 'quote_requests', version: manifest51.version, registerModule: module51.registerModule },
  { id: 'carts', version: manifest52.version, registerModule: module52.registerModule },
  { id: 'quick_order', version: manifest53.version, registerModule: module53.registerModule },
  { id: 'customers', version: manifest54.version, registerModule: module54.registerModule },
  { id: 'newsletter', version: manifest55.version, registerModule: module55.registerModule },
  { id: 'returns', version: manifest56.version, registerModule: module56.registerModule },
  { id: 'autopay', version: manifest57.version, registerModule: module57.registerModule },
  { id: 'paypal', version: manifest58.version, registerModule: module58.registerModule },
  { id: 'payu', version: manifest59.version, registerModule: module59.registerModule },
  { id: 'search', version: manifest60.version, registerModule: module60.registerModule },
  { id: 'shipments', version: manifest61.version, registerModule: module61.registerModule },
  { id: 'shopping_lists', version: manifest62.version, registerModule: module62.registerModule },
  { id: 'stripe', version: manifest63.version, registerModule: module63.registerModule },
  { id: 'tpay', version: manifest64.version, registerModule: module64.registerModule },
  { id: 'webhooks', version: manifest65.version, registerModule: module65.registerModule },
];
