// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// Every module that ships a `backend.ts` exporting `registerModule`, in the
// order a composition root must compose them:
//
//   1. `api_keys` first — a **construction** dependency, not a manifest one:
//      the API-key authenticator is injected into the auth plugin, and
//      `api_keys`' manifest declares nothing about `auth`. Pinned here, in the
//      open, until F3 fixes the declaration.
//   2. then a topological order over `manifest.dependencies`, ties broken
//      alphabetically so this file is a function of the tree and nothing else.
//   3. overlay modules (feature 057) last, so a deployment's `di.decorate`
//      wins over the core registration it decorates.
//
// A module missing from this list is a module with no `backend.ts` — it is
// still hand-wired in `composition.ts` until its own conversion lands.

import type { ModuleEntry } from './kernel/compose.js';

import * as module0 from './modules/admin_roles/backend.js';
import { manifest as manifest0 } from './modules/admin_roles/manifest.js';
import * as module1 from './modules/auth/backend.js';
import { manifest as manifest1 } from './modules/auth/manifest.js';
import * as module2 from './modules/admin_notifications/backend.js';
import { manifest as manifest2 } from './modules/admin_notifications/manifest.js';
import * as module3 from './modules/analytics/backend.js';
import { manifest as manifest3 } from './modules/analytics/manifest.js';
import * as module4 from './modules/blog/backend.js';
import { manifest as manifest4 } from './modules/blog/manifest.js';
import * as module5 from './modules/credentials/backend.js';
import { manifest as manifest5 } from './modules/credentials/manifest.js';
import * as module6 from './modules/currencies/backend.js';
import { manifest as manifest6 } from './modules/currencies/manifest.js';
import * as module7 from './modules/email/backend.js';
import { manifest as manifest7 } from './modules/email/manifest.js';
import * as module8 from './modules/health_checks/backend.js';
import { manifest as manifest8 } from './modules/health_checks/manifest.js';

export const MODULES: readonly ModuleEntry[] = [
  { id: 'admin_roles', version: manifest0.version, registerModule: module0.registerModule },
  { id: 'auth', version: manifest1.version, registerModule: module1.registerModule },
  { id: 'admin_notifications', version: manifest2.version, registerModule: module2.registerModule },
  { id: 'analytics', version: manifest3.version, registerModule: module3.registerModule },
  { id: 'blog', version: manifest4.version, registerModule: module4.registerModule },
  { id: 'credentials', version: manifest5.version, registerModule: module5.registerModule },
  { id: 'currencies', version: manifest6.version, registerModule: module6.registerModule },
  { id: 'email', version: manifest7.version, registerModule: module7.registerModule },
  { id: 'health_checks', version: manifest8.version, registerModule: module8.registerModule },
];
