// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// Every module that ships a `backend.ts` exporting `registerModule`, in the
// order a composition root must compose them:
//
//   1. `api_keys` first — a **construction** dependency, not a manifest one:
//      the API-key authenticator is injected into the auth plugin, and
//      `api_keys`' manifest declares nothing about `auth`. Pinned here, in the
//      open, until F3 fixes the declaration.
//   2. then a topological order over `manifest.dependencies`, ties broken
//      alphabetically so this file is a function of the tree and nothing else.
//   3. overlay modules (feature 057) last, so a deployment's `di.decorate`
//      wins over the core registration it decorates.
//
// A module missing from this list is a module with no `backend.ts` — it is
// still hand-wired in `composition.ts` until its own conversion lands.

import type { ModuleEntry } from './kernel/compose.js';

import * as module0 from './modules/admin_roles/backend.js';
import { manifest as manifest0 } from './modules/admin_roles/manifest.js';
import * as module1 from './modules/auth/backend.js';
import { manifest as manifest1 } from './modules/auth/manifest.js';
import * as module2 from './modules/_i18n/backend.js';
import { manifest as manifest2 } from './modules/_i18n/manifest.js';
import * as module3 from './modules/admin_notifications/backend.js';
import { manifest as manifest3 } from './modules/admin_notifications/manifest.js';
import * as module4 from './modules/analytics/backend.js';
import { manifest as manifest4 } from './modules/analytics/manifest.js';
import * as module5 from './modules/assets_library/backend.js';
import { manifest as manifest5 } from './modules/assets_library/manifest.js';
import * as module6 from './modules/audit_logs/backend.js';
import { manifest as manifest6 } from './modules/audit_logs/manifest.js';
import * as module7 from './modules/cms/backend.js';
import { manifest as manifest7 } from './modules/cms/manifest.js';
import * as module8 from './modules/credentials/backend.js';
import { manifest as manifest8 } from './modules/credentials/manifest.js';
import * as module9 from './modules/credit_limits/backend.js';
import { manifest as manifest9 } from './modules/credit_limits/manifest.js';
import * as module10 from './modules/currencies/backend.js';
import { manifest as manifest10 } from './modules/currencies/manifest.js';
import * as module11 from './modules/custom_fields/backend.js';
import { manifest as manifest11 } from './modules/custom_fields/manifest.js';
import * as module12 from './modules/customer_accounts/backend.js';
import { manifest as manifest12 } from './modules/customer_accounts/manifest.js';
import * as module13 from './modules/api_keys/backend.js';
import { manifest as manifest13 } from './modules/api_keys/manifest.js';
import * as module14 from './modules/comparisons/backend.js';
import { manifest as manifest14 } from './modules/comparisons/manifest.js';
import * as module15 from './modules/delivery_methods/backend.js';
import { manifest as manifest15 } from './modules/delivery_methods/manifest.js';
import * as module16 from './modules/email/backend.js';
import { manifest as manifest16 } from './modules/email/manifest.js';
import * as module17 from './modules/google_analytics/backend.js';
import { manifest as manifest17 } from './modules/google_analytics/manifest.js';
import * as module18 from './modules/google_tag_manager/backend.js';
import { manifest as manifest18 } from './modules/google_tag_manager/manifest.js';
import * as module19 from './modules/health_checks/backend.js';
import { manifest as manifest19 } from './modules/health_checks/manifest.js';
import * as module20 from './modules/import_export/backend.js';
import { manifest as manifest20 } from './modules/import_export/manifest.js';
import * as module21 from './modules/languages/backend.js';
import { manifest as manifest21 } from './modules/languages/manifest.js';
import * as module22 from './modules/dictionaries/backend.js';
import { manifest as manifest22 } from './modules/dictionaries/manifest.js';
import * as module23 from './modules/addresses/backend.js';
import { manifest as manifest23 } from './modules/addresses/manifest.js';
import * as module24 from './modules/blog/backend.js';
import { manifest as manifest24 } from './modules/blog/manifest.js';
import * as module25 from './modules/linkedin_ads/backend.js';
import { manifest as manifest25 } from './modules/linkedin_ads/manifest.js';
import * as module26 from './modules/megamenu/backend.js';
import { manifest as manifest26 } from './modules/megamenu/manifest.js';
import * as module27 from './modules/meta_ads/backend.js';
import { manifest as manifest27 } from './modules/meta_ads/manifest.js';
import * as module28 from './modules/mfa/backend.js';
import { manifest as manifest28 } from './modules/mfa/manifest.js';
import * as module29 from './modules/payment_methods/backend.js';
import { manifest as manifest29 } from './modules/payment_methods/manifest.js';
import * as module30 from './modules/promotions/backend.js';
import { manifest as manifest30 } from './modules/promotions/manifest.js';
import * as module31 from './modules/prompt_actions/backend.js';
import { manifest as manifest31 } from './modules/prompt_actions/manifest.js';
import * as module32 from './modules/seo/backend.js';
import { manifest as manifest32 } from './modules/seo/manifest.js';
import * as module33 from './modules/taxes/backend.js';
import { manifest as manifest33 } from './modules/taxes/manifest.js';
import * as module34 from './modules/webhooks/backend.js';
import { manifest as manifest34 } from './modules/webhooks/manifest.js';

export const MODULES: readonly ModuleEntry[] = [
  { id: 'admin_roles', version: manifest0.version, registerModule: module0.registerModule },
  { id: 'auth', version: manifest1.version, registerModule: module1.registerModule },
  { id: '_i18n', version: manifest2.version, registerModule: module2.registerModule },
  { id: 'admin_notifications', version: manifest3.version, registerModule: module3.registerModule },
  { id: 'analytics', version: manifest4.version, registerModule: module4.registerModule },
  { id: 'assets_library', version: manifest5.version, registerModule: module5.registerModule },
  { id: 'audit_logs', version: manifest6.version, registerModule: module6.registerModule },
  { id: 'cms', version: manifest7.version, registerModule: module7.registerModule },
  { id: 'credentials', version: manifest8.version, registerModule: module8.registerModule },
  { id: 'credit_limits', version: manifest9.version, registerModule: module9.registerModule },
  { id: 'currencies', version: manifest10.version, registerModule: module10.registerModule },
  { id: 'custom_fields', version: manifest11.version, registerModule: module11.registerModule },
  { id: 'customer_accounts', version: manifest12.version, registerModule: module12.registerModule },
  { id: 'api_keys', version: manifest13.version, registerModule: module13.registerModule },
  { id: 'comparisons', version: manifest14.version, registerModule: module14.registerModule },
  { id: 'delivery_methods', version: manifest15.version, registerModule: module15.registerModule },
  { id: 'email', version: manifest16.version, registerModule: module16.registerModule },
  { id: 'google_analytics', version: manifest17.version, registerModule: module17.registerModule },
  { id: 'google_tag_manager', version: manifest18.version, registerModule: module18.registerModule },
  { id: 'health_checks', version: manifest19.version, registerModule: module19.registerModule },
  { id: 'import_export', version: manifest20.version, registerModule: module20.registerModule },
  { id: 'languages', version: manifest21.version, registerModule: module21.registerModule },
  { id: 'dictionaries', version: manifest22.version, registerModule: module22.registerModule },
  { id: 'addresses', version: manifest23.version, registerModule: module23.registerModule },
  { id: 'blog', version: manifest24.version, registerModule: module24.registerModule },
  { id: 'linkedin_ads', version: manifest25.version, registerModule: module25.registerModule },
  { id: 'megamenu', version: manifest26.version, registerModule: module26.registerModule },
  { id: 'meta_ads', version: manifest27.version, registerModule: module27.registerModule },
  { id: 'mfa', version: manifest28.version, registerModule: module28.registerModule },
  { id: 'payment_methods', version: manifest29.version, registerModule: module29.registerModule },
  { id: 'promotions', version: manifest30.version, registerModule: module30.registerModule },
  { id: 'prompt_actions', version: manifest31.version, registerModule: module31.registerModule },
  { id: 'seo', version: manifest32.version, registerModule: module32.registerModule },
  { id: 'taxes', version: manifest33.version, registerModule: module33.registerModule },
  { id: 'webhooks', version: manifest34.version, registerModule: module34.registerModule },
];
