/**
 * GENERATED by `pnpm run blocks:generate`.
 * Never edit this file; run the generator.
 *
 * The storefront layers of the module packages this storefront has installed —
 * every package whose own `package.json` says `endora.type` is `module` and
 * whose `exports` map declares `./storefront`. Installing a module's renderers
 * is adding the package and nothing else; `lib/page-builder/config.ts` is what
 * reads this, and nothing else should.
 *
 * Static imports on purpose: a block is part of the server-rendered HTML, and
 * a rendering server may have no `node_modules` tree to walk at run time.
 */
import type { StorefrontContributions } from '@endora-commerce/page-builder-core/contributions';

/** One installed module's storefront renderers, keyed by the module id that shipped them. */
export interface StorefrontBlockRegistryEntry {
  readonly moduleId: string;
  readonly contributions: StorefrontContributions;
}

export const STOREFRONT_BLOCK_CONTRIBUTIONS: readonly StorefrontBlockRegistryEntry[] = [];
