/**
 * GENERATED by `pnpm --filter storefront run themes:generate`.
 * Never edit this file; run the generator.
 *
 * The theme codes this storefront instance provides — the union of its own
 * `:root[data-theme='…']` blocks and the `endora.themes` declarations of the
 * theme packages it has installed. `lib/theme/instance-themes.ts` is what
 * asks it; nothing else should.
 */
export const INSTANCE_THEME_CODES = ['industria', 'nordic'] as const;
