// The deployment divergence report — the two renderings, from one derivation.
//
// The report itself is derived by `scripts/lib/divergence.ts`, which reads the
// deployment's overlay sources through the TypeScript compiler API. That half is
// not here for one reason: `typescript` is a devDependency and `backend/src/**`
// is compiled into the production image (D-165), so an analysis imported from
// here would make the compiler a runtime dependency of every instance. What
// lives here is the half the *artefact* needs — the shape, and the two functions
// that turn it into files.
//
// **One derivation, two renders** (`data-model.md` §3). The alternative — a
// second derivation for the human rendering — was rejected as two answers to one
// question waiting to disagree; `serializeManifestModule` already had this shape
// and feature 100's generated module map is the precedent for the `.md`.
//
// The report supersedes the v2 override manifest, which recorded exactly one
// fact: which overlay modules a deployment adds. That field survives here as
// `overlayModules`, and it is legitimately empty for a deployment shipping no
// overlay module — so `overlay:check`'s `empty` verdict does not apply to either
// rendering. A deployment that diverges by nothing says so explicitly, which is
// the whole difference between an empty report and an absent one.

import { relative, sep } from 'node:path';
import type { DivergenceEntry, DivergenceKind, DivergenceReport } from '@endora-commerce/contracts';
import { repoRoot } from './overlay-roots.js';

/** Repo-relative, POSIX separators — determinism (FR-013). */
export function repoRelativePath(absPath: string, base: string = repoRoot()): string {
  const rel = relative(base, absPath);
  return sep === '/' ? rel : rel.split(sep).join('/');
}

/**
 * What each rung costs, in the words a reader who has never seen this repository
 * needs (SC-001).
 *
 * The human rendering spells the **cost** rather than the number, because a
 * number is only meaningful to somebody who has the ladder open beside them —
 * and the reader this artefact exists for is a client's developer who has not.
 * The full ladder is `docs/docs/architecture/customisation-ladder.md`; these are
 * its one-line summaries and they are kept in step by
 * `test/unit/overlay/divergence-render.test.ts`.
 */
export const RUNG_COSTS: Readonly<Record<number, string>> = {
  0: 'rung 0 — configuration. Costs nothing and survives every upgrade, because it is data.',
  1: 'rung 1 — subscribe to what the owner already emits. Costs nothing at the seam; you observe, you do not change what the owner did.',
  2: 'rung 2 — run before or after what the owner already serves. Costs a coupling to an endpoint identity, which is versioned public API.',
  3: 'rung 3 — a strategy port the owner published. Costs a dependency edge in your manifest; the owner keeps the seam and keeps fixing it behind you.',
  4: 'rung 4 — change what the container hands out. Costs a contract-version coupling to a shape nothing checks for you: `ctx.di.decorate<T>` asserts `T` at the call site and compares it to nothing.',
  5: 'rung 5 — fork. Costs everything, permanently.',
};

/** The heading each kind gets in the human rendering. */
const KIND_HEADINGS: Readonly<Record<DivergenceKind, string>> = {
  omission: 'Modules this deployment does not ship',
  registration: 'Services this deployment adds to the container',
  'port-provided': 'Ports this deployment publishes',
  'port-consumed': 'Ports this deployment consumes',
  subscription: 'Events this deployment subscribes to',
  interceptor: 'Endpoints this deployment intercepts',
  decoration: 'Registrations this deployment wraps',
  'root-plugin': 'Plugins this deployment mounts at the server root',
  worker: 'Queues this deployment consumes',
};

/** Stable order for the human rendering — most invasive last is not the point;
 *  a reader wants the same order every time, so it is the ladder's own. */
const KIND_ORDER: readonly DivergenceKind[] = [
  'omission',
  'subscription',
  'interceptor',
  'port-provided',
  'port-consumed',
  'decoration',
  'root-plugin',
  'registration',
  'worker',
];

/**
 * Emit the report as a committed, typed TS module (mirrors
 * `manifest-index.generated.ts`).
 *
 * `typesImportSpecifier` is the module-resolvable path from the emitted file's
 * directory to `src/overlay/types.js` — it differs between the core output
 * (`./types.js`) and a deployment output (`../../overlay/types.js`), so the
 * caller computes and passes it.
 */
export function serializeDivergenceModule(
  report: DivergenceReport,
  typesImportSpecifier: string,
): string {
  const body = JSON.stringify(report, null, 2);
  return `// AUTO-GENERATED by scripts/generate-divergence.ts — DO NOT EDIT.
// Run \`pnpm --filter backend run overlay:divergence\` (or rebuild) to refresh.
// Deterministic record of this deployment's divergence from core.

import type { DivergenceReport } from '${typesImportSpecifier}';

export const DIVERGENCE_REPORT: DivergenceReport = ${body};
`;
}

/** Stable JSON serialization, for a caller that wants the shape and no module. */
export function serializeDivergenceJson(report: DivergenceReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function ownerCell(entry: DivergenceEntry): string {
  if (entry.kind === 'omission') return '—';
  return entry.owner === null ? 'a composition root (no module owns it)' : `\`${entry.owner}\``;
}

function subjectCell(entry: DivergenceEntry): string {
  if (entry.kind === 'interceptor' && entry.detail.kind === 'interceptor') {
    return `\`${entry.subject}\` (${entry.detail.phase})`;
  }
  return `\`${entry.subject}\``;
}

/**
 * The human rendering — D-30's own word for this artefact is *report*.
 *
 * Three rules, all of them SC-001's: no key strings (a reader is not looking
 * anything up), no repository-relative paths (the reader's tree is not this
 * one), and the rung's **cost** spelled out rather than its number.
 */
export function renderDivergenceMarkdown(report: DivergenceReport): string {
  const lines: string[] = [];
  const isCore = report.deployment === 'core';

  lines.push('<!-- AUTO-GENERATED by scripts/generate-divergence.ts — DO NOT EDIT. -->');
  lines.push('<!-- Run `pnpm --filter backend run overlay:divergence` (or rebuild) to refresh. -->');
  lines.push('');
  lines.push(
    isCore
      ? '# Divergence from core: bare core'
      : `# Divergence from core: \`${report.deployment}\``,
  );
  lines.push('');
  lines.push(
    'Every way this deployment differs from the platform it was built on, derived from its own',
    'tree. It is the first thing to consult when an upgrade changes behaviour you depended on.',
    '',
    'Each entry names **what** was changed, **which of this deployment’s modules** changed it,',
    '**which module owns** the thing that was changed, what the change **costs**, and the',
    'sentence this deployment wrote when it made the change.',
    '',
  );

  if (isCore) {
    lines.push(
      'This is the bare-core build: no deployment is selected, so there is nothing to diverge',
      'from core *with*. It is generated and committed anyway, because an absent report and a',
      'report that says "nothing" are indistinguishable, and only one of them is a statement.',
      '',
    );
  }

  lines.push('## What this deployment adds');
  lines.push('');
  if (report.overlayModules.length === 0) {
    lines.push('No overlay modules. This deployment ships the platform’s own module set.');
  } else {
    lines.push('| Overlay module |');
    lines.push('| --- |');
    for (const moduleId of report.overlayModules) lines.push(`| \`${moduleId}\` |`);
  }
  lines.push('');

  lines.push('## What this deployment changes');
  lines.push('');
  if (report.entries.length === 0) {
    lines.push(
      'Nothing. This deployment changes no registration, intercepts no endpoint, subscribes to no',
      'event, publishes and consumes no port, mounts no root plugin and omits no module.',
      '',
      'That is a statement rather than an absence: the derivation ran over this deployment’s own',
      'tree and found no divergence of any recorded kind.',
    );
    lines.push('');
  } else {
    for (const kind of KIND_ORDER) {
      const entries = report.entries.filter((entry) => entry.kind === kind);
      if (entries.length === 0) continue;
      lines.push(`### ${KIND_HEADINGS[kind]}`);
      lines.push('');
      const rungs = [...new Set(entries.map((entry) => entry.rung))].filter(
        (rung): rung is number => rung !== null,
      );
      for (const rung of rungs.sort((a, b) => a - b)) {
        const cost = RUNG_COSTS[rung];
        if (cost !== undefined) lines.push(`${cost}`, '');
      }
      lines.push('| What | Changed by | Owned by | Why |');
      lines.push('| --- | --- | --- | --- |');
      for (const entry of entries) {
        const changedBy = entry.kind === 'omission' ? '—' : `\`${entry.module}\``;
        lines.push(
          `| ${escapeCell(subjectCell(entry))} | ${changedBy} | ${escapeCell(ownerCell(entry))} | ` +
            `${escapeCell(entry.reason.length === 0 ? '**not declared**' : entry.reason)} |`,
        );
      }
      lines.push('');
    }
  }

  lines.push('## What this report does not cover');
  lines.push('');
  lines.push(
    'A report that lists what it records and says nothing about the rest is indistinguishable',
    'from a complete one. These are the seams that exist and are deliberately not divergences,',
    'and the facts only a running instance can answer.',
    '',
  );
  lines.push('### Seams that are a module’s own business');
  lines.push('');
  lines.push('| Seam | Why it is not a divergence |');
  lines.push('| --- | --- |');
  for (const entry of report.boundary.notRecorded) {
    lines.push(`| \`${escapeCell(entry.seam)}\` | ${escapeCell(entry.why)} |`);
  }
  lines.push('');
  lines.push('### Facts only a running instance knows');
  lines.push('');
  lines.push('| Fact | Why it is not here |');
  lines.push('| --- | --- |');
  for (const entry of report.boundary.runtimeOnly) {
    lines.push(`| ${escapeCell(entry.fact)} | ${escapeCell(entry.why)} |`);
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
}
