// Overlay resolution — override-manifest builder + serializer.
//
// The override manifest is the audit artifact of a deployment build (US3,
// FR-005): it enumerates every core unit an overlay replaced and every
// overlay-only module added. It is deterministic (repo-relative paths, sorted
// arrays, no timestamps) so identical inputs produce byte-identical output
// (FR-006, SC-003). See contracts/override-manifest.md.

import { relative, sep } from 'node:path';
import { repoRoot } from './overlay-roots.js';
import {
  type OverrideEntry,
  type OverrideManifest,
  type OverlayResolution,
  unitKey,
} from './types.js';

function repoRelative(absPath: string, base: string): string {
  const rel = relative(base, absPath);
  return sep === '/' ? rel : rel.split(sep).join('/');
}

/**
 * Build the deterministic override manifest for a resolution. `coreRoot` /
 * `overlayRoot` are recorded (repo-relative) for reproducibility. `base`
 * defaults to the repository root; tests pass an explicit base.
 */
export function buildOverrideManifest(params: {
  deployment: string | null;
  coreRoot: string;
  overlayRoot: string | null;
  resolution: OverlayResolution;
  base?: string;
}): OverrideManifest {
  const base = params.base ?? repoRoot();
  const overrides: OverrideEntry[] = params.resolution.overrides
    .map((o) => ({
      moduleId: o.moduleId,
      kind: o.kind,
      unitKey: o.relPath,
      overlayPath: repoRelative(o.overlayPath, base),
      satisfiesInterface:
        o.interfaceRelPath === null
          ? null
          : `modules/${o.moduleId}/${o.interfaceRelPath}`,
    }))
    .sort(
      (a, b) =>
        a.moduleId.localeCompare(b.moduleId) ||
        a.kind.localeCompare(b.kind) ||
        a.unitKey.localeCompare(b.unitKey),
    );
  return {
    deployment: params.deployment ?? 'core',
    generatedFrom: {
      coreRoot: repoRelative(params.coreRoot, base),
      overlayRoot: params.overlayRoot === null ? null : repoRelative(params.overlayRoot, base),
    },
    overrides,
    newModules: [...params.resolution.newModules].sort(),
  };
}

/** Stable JSON serialization (2-space, sorted keys already fixed by the shape). */
export function serializeManifestJson(manifest: OverrideManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * Emit the manifest as a committed, typed TS module (mirrors
 * manifest-index.generated.ts). `typesImportSpecifier` is the module-resolvable
 * path from the emitted file's directory to `src/overlay/types.js` — it differs
 * between the core output (`./types.js`) and a deployment output
 * (`../../overlay/types.js`), so the caller computes and passes it.
 */
export function serializeManifestModule(
  manifest: OverrideManifest,
  typesImportSpecifier: string,
): string {
  const body = JSON.stringify(manifest, null, 2);
  return `// AUTO-GENERATED by scripts/generate-override-manifest.ts — DO NOT EDIT.
// Run \`pnpm --filter backend run overlay:manifest\` (or rebuild) to refresh.
// Deterministic audit artifact of this deployment's divergence from core.

import type { OverrideManifest } from '${typesImportSpecifier}';

export const OVERRIDE_MANIFEST: OverrideManifest = ${body};
`;
}

/** Convenience: does this manifest describe a divergence from core? */
export function hasOverrides(manifest: OverrideManifest): boolean {
  return manifest.overrides.length > 0 || manifest.newModules.length > 0;
}

// Re-export for consumers that build a key from a manifest entry.
export { unitKey };
