// Overlay resolution — override-manifest builder + serializer.
//
// The override manifest is the audit artifact of a deployment build (US3,
// FR-005): it records which deployment this is, which overlay root was read,
// and which modules the deployment adds. It is deterministic (repo-relative
// paths, sorted arrays, no timestamps) so identical inputs produce
// byte-identical output (FR-006, SC-003).
//
// v2 dropped `overrides` and `generatedFrom.coreRoot` (feature 103, D-201). The
// first enumerated the core units an overlay replaced, and nothing replaces a
// core unit — the array could only ever be empty, and an always-empty field in
// an artefact a determinism check byte-compares is a field that makes the check
// agree with itself. See
// specs/103-overlay-shadowing-retirement/contracts/override-manifest-v2.md.
//
// A `newModules` array is legitimately empty for a deployment shipping no
// overlay module, so `overlay:check`'s `empty` verdict does not apply to an
// override manifest. That was true in v1 and stays true; it is recorded here
// because it is the property that let the always-empty `overrides` array go
// unnoticed for a year.

import { relative, sep } from 'node:path';
import { repoRoot } from './overlay-roots.js';
import { type OverrideManifest, type OverlayResolution } from './types.js';

function repoRelative(absPath: string, base: string): string {
  const rel = relative(base, absPath);
  return sep === '/' ? rel : rel.split(sep).join('/');
}

/**
 * Build the deterministic override manifest for a resolution. `overlayRoot` is
 * recorded (repo-relative) for reproducibility. `base` defaults to the
 * repository root; tests pass an explicit base.
 */
export function buildOverrideManifest(params: {
  deployment: string | null;
  overlayRoot: string | null;
  resolution: OverlayResolution;
  base?: string;
}): OverrideManifest {
  const base = params.base ?? repoRoot();
  return {
    deployment: params.deployment ?? 'core',
    generatedFrom: {
      overlayRoot: params.overlayRoot === null ? null : repoRelative(params.overlayRoot, base),
    },
    newModules: [...params.resolution.newModules].sort(),
  };
}

/** Stable JSON serialization (2-space, sorted keys already fixed by the shape). */
export function serializeManifestJson(manifest: OverrideManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * Emit the manifest as a committed, typed TS module (mirrors
 * manifest-index.generated.ts). `typesImportSpecifier` is the module-resolvable
 * path from the emitted file's directory to `src/overlay/types.js` — it differs
 * between the core output (`./types.js`) and a deployment output
 * (`../../overlay/types.js`), so the caller computes and passes it.
 */
export function serializeManifestModule(
  manifest: OverrideManifest,
  typesImportSpecifier: string,
): string {
  const body = JSON.stringify(manifest, null, 2);
  return `// AUTO-GENERATED by scripts/generate-override-manifest.ts — DO NOT EDIT.
// Run \`pnpm --filter backend run overlay:manifest\` (or rebuild) to refresh.
// Deterministic audit artifact of this deployment's divergence from core.

import type { OverrideManifest } from '${typesImportSpecifier}';

export const OVERRIDE_MANIFEST: OverrideManifest = ${body};
`;
}
