import { describe, expect, it } from 'vitest';
import { generatedArtifactPaths, renderAll } from '../../scripts/generate-composer.js';
import { coveredArtifactPaths } from '../../scripts/check-overlay-determinism.js';

/**
 * T-E — every generated artefact renders identically with and without
 * `DEPLOYMENT` set (D-104).
 *
 * This is the issue-#120 ruling applied to the family it was missed in. Before
 * D-104, `manifest-index.generated.ts` was rendered from a walk that read
 * `DEPLOYMENT`, so the committed file — the bare-core render — reported STALE on
 * **every** run that set the variable, while no run that left it unset looked at
 * the deployment at all. Measured on `master` at 432455a3:
 *
 *     $ DEPLOYMENT=example pnpm --filter backend run overlay:check
 *     [overlay:check] composition.generated: up-to-date and deterministic ✓
 *     [overlay:check] manifest-index: committed file is STALE at …
 *     exit 1
 *
 * And `composition.generated` read clean there only because `example_overlay`
 * shipped no `backend.ts`. Giving it one — which D-103 requires — would have put
 * a second artefact into the permanently-stale set. An artefact that is always
 * stale for a deployment is one nobody can use to detect a genuinely stale one.
 *
 * The comparison is over the **rendered** content rather than over the check's
 * exit code, so a regression is reported as the artefact that moved rather than
 * as a failed subprocess.
 */
describe('T-E — the generated artefacts are environment-independent', () => {
  it('renders every artefact byte-identically with and without DEPLOYMENT=example', async () => {
    const before = process.env['DEPLOYMENT'];
    let withDeployment: ReadonlyArray<{ label: string; content: string }>;
    try {
      process.env['DEPLOYMENT'] = 'example';
      withDeployment = (await renderAll()).map(({ label, content }) => ({ label, content }));
    } finally {
      if (before === undefined) delete process.env['DEPLOYMENT'];
      else process.env['DEPLOYMENT'] = before;
    }

    const bareCore = (await renderAll()).map(({ label, content }) => ({ label, content }));

    // Non-vacuity: one artefact per committed output path, and a render that
    // found nothing would compare two empty strings equal. The count is
    // **derived** rather than written down (D-100) — feature 091's admin
    // registry made a literal `4` here stale in the merge request that added
    // a fifth artefact, and `generatedArtifactPaths()` is the same generator's
    // own answer to "what does this command write".
    expect(bareCore.length).toBeGreaterThan(0);
    expect(bareCore).toHaveLength(generatedArtifactPaths().length);
    for (const artefact of bareCore) expect(artefact.content.length).toBeGreaterThan(0);

    expect(withDeployment).toEqual(bareCore);
  });

  it('names nothing from a deployment tree, in any committed artefact', async () => {
    const artefacts = await renderAll();
    // Every artefact contributes, and the count is derived (D-100) — the
    // enumeration this predicate replaced went blind on two of seven, and a
    // whole-run total would have hidden that behind the five that still read.
    const inspected = artefacts.map(({ label, content }) => ({
      label,
      lines: assertNamesNoDeployment(label, content),
    }));
    expect(inspected).toHaveLength(generatedArtifactPaths().length);
    for (const { label, lines } of inspected) {
      expect(lines, `${label} contributed no inspected line`).toBeGreaterThan(0);
    }
  });

  describe('the refusal itself', () => {
    // Issue #130: one proof per shape the assertion refuses, each entering at
    // the top of the analysis — a rendered artefact's own text — so the
    // predicate and the guard both run. Two of these three fixtures pass the
    // enumeration this predicate replaced, which is the regression they pin.
    const SIDEBAR_SHAPED = [
      '// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.',
      '',
      "/** @type {import('@docusaurus/plugin-content-docs').SidebarItemConfig[]} */",
      'const modules = [',
      "  { type: 'doc', id: 'modules/addresses', label: 'addresses' },",
      "  { type: 'doc', id: 'modules/example_overlay', label: 'Example overlay' },",
      '];',
      '',
      'module.exports = modules;',
    ].join('\n');

    // The sidebar's second entry shape: a category, whose `id:` lines sit two
    // and three levels in and whose `items` name a page with no key at all.
    const SIDEBAR_CATEGORY_SHAPED = [
      'const modules = [',
      '  {',
      "    type: 'category',",
      "    label: 'Example overlay',",
      "    link: { type: 'doc', id: 'modules/example_overlay' },",
      "    items: ['modules/example_overlay/setup'],",
      '  },',
      '];',
    ].join('\n');

    const MAP_SHAPED = [
      '<!-- AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.',
      '     Run `pnpm --filter backend run composer:generate` to refresh. -->',
      '---',
      'title: Module map',
      '---',
      '',
      '| Module | Capability | Ships from |',
      '| --- | --- | --- |',
      '| [addresses](./addresses.md) | Customer postal addresses | @endora-commerce/mod-addresses |',
      '| [example_overlay](./example-overlay.md) | A deployment overlay | core |',
    ].join('\n');

    it('catches a deployment reference in a sidebar-shaped entry', () => {
      // The `id:` sits behind two spaces and a `{ type: …`, so the old
      // `startsWith('  { id:')` selected it in neither shape the sidebar writes.
      expect(() => assertNamesNoDeployment('docs-sidebar', SIDEBAR_SHAPED)).toThrow(
        /names the example overlay module/,
      );
    });

    it('pins the two directions the retired enumeration was wrong in', () => {
      // The predicate this replaced, spelled out over the same fixtures: it
      // selected **nothing** from either documentation artefact, so the
      // deployment reference in each went unread. Restoring it — or answering
      // its zero with `startsWith('  {')`, which matches a bare brace and can
      // carry no reference — puts the blind spot back.
      const retired = (content: string): readonly string[] =>
        content
          .split('\n')
          .filter((line) => line.startsWith('import ') || line.startsWith('  { id:'));
      expect(retired(SIDEBAR_SHAPED)).toHaveLength(0);
      expect(retired(MAP_SHAPED)).toHaveLength(0);
      expect(
        emittedLines(SIDEBAR_SHAPED).filter((line) => line.includes('example_overlay')),
      ).toHaveLength(1);
      expect(
        emittedLines(MAP_SHAPED).filter((line) => line.includes('example_overlay')),
      ).toHaveLength(1);
      // And the cheap repair, measured rather than argued: widening the
      // enumeration with `startsWith('  {')` selects the sidebar's bare category
      // brace — a line that can carry no reference under any tree — while the
      // `id:` two lines below it, which carries one, stays unread. The guard
      // goes quiet and the assertion under it inspects nothing that matters.
      const braceWidened = SIDEBAR_CATEGORY_SHAPED.split('\n').filter(
        (line) =>
          line.startsWith('import ') || line.startsWith('  { id:') || line.startsWith('  {'),
      );
      expect(braceWidened).toEqual(['  {']);
      expect(braceWidened.some((line) => line.includes('example_overlay'))).toBe(false);
      expect(() => assertNamesNoDeployment('docs-sidebar', SIDEBAR_CATEGORY_SHAPED)).toThrow(
        /names the example overlay module/,
      );
    });

    it('catches a deployment reference in a markdown table row', () => {
      expect(() => assertNamesNoDeployment('module-map', MAP_SHAPED)).toThrow(
        /names the example overlay module/,
      );
    });

    it('catches a deployment path wherever the artefact indents it', () => {
      const nested = [
        'export const entries = [',
        '  {',
        "    id: 'example',",
        "    manifestPath: '../src/apps/example/modules/example_overlay/manifest.js',",
        '  },',
        '];',
      ].join('\n');
      expect(() => assertNamesNoDeployment('manifest-index', nested)).toThrow(
        /names a deployment tree/,
      );
    });

    it('still refuses an artefact that renders nothing', () => {
      expect(() => assertNamesNoDeployment('docs-sidebar', '')).toThrow(/emitted nothing/);
    });

    it('refuses an artefact whose whole body is a header comment', () => {
      // The state the guard exists for, and the one a shape enumeration cannot
      // tell from a clean artefact: a generator that found nothing still emits
      // its banner.
      const bannerOnly = [
        '// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.',
        '/*',
        ' * A block comment whose continuation lines start with neither marker.',
        ' */',
        '',
      ].join('\n');
      expect(() => assertNamesNoDeployment('composition.generated', bannerOnly)).toThrow(
        /emitted nothing/,
      );
    });

    it('does not read a generator header that discusses `src/apps/` as a reference', () => {
      // Why comments are excluded: `entities-registry`'s own header explains
      // that an entity under `src/apps/` is refused, and this assertion must
      // read what the generator emitted rather than what it says about itself.
      const documented = [
        '// An `@Entity()` under `src/apps/` is refused — an overlay module ships',
        '// no schema (D-106), so `example_overlay` contributes no entity here.',
        '<!-- a markdown banner naming src/apps/ too -->',
        "import { AuditLogEntry } from '../kernel/audit/audit-log-entry.entity.js';",
        'export const entities = [AuditLogEntry];',
      ].join('\n');
      expect(assertNamesNoDeployment('entities-registry', documented)).toBe(2);
    });
  });

  it('covers the same artefacts whichever way the environment is set', () => {
    const before = process.env['DEPLOYMENT'];
    try {
      process.env['DEPLOYMENT'] = 'example';
      const withDeployment = coveredArtifactPaths();
      delete process.env['DEPLOYMENT'];
      expect(withDeployment).toEqual(coveredArtifactPaths());
    } finally {
      if (before === undefined) delete process.env['DEPLOYMENT'];
      else process.env['DEPLOYMENT'] = before;
    }
  });
});

/**
 * The lines of a rendered artefact that could **carry** a deployment reference:
 * everything the generator emitted that is neither blank nor a comment.
 *
 * It is a subtraction rather than an enumeration of shapes, and that is the
 * whole design. The predicate here read
 *
 *     line.startsWith('import ') || line.startsWith('  { id:')
 *
 * — an enumeration of two shapes the five `.ts` artefacts happened to write, an
 * import and a one-line entry indented by exactly two spaces — and feature
 * 100's `docs/sidebars.modules.generated.js` matched neither: its
 * entries are indented differently, its category entries put `id:` on a deeper
 * line, and its bare `'modules/<slug>',` items name a page with no key at all.
 * `docs/docs/modules/module-map.generated.md` matched nothing either, being a
 * markdown table; it was simply never reached, because the non-vacuity guard
 * below stopped the run at the sidebar first. Two artefacts inspected zero
 * lines, and the guard is what said so — issue #113's rule working as designed.
 *
 * **The cheap repair is the trap.** Adding `line.startsWith('  {')` satisfies
 * the guard with lines that are a bare brace: they cannot contain `/apps/` or
 * `example_overlay` under any tree, so the count goes non-zero while the
 * assertion under it inspects nothing. A loud, correct refusal becomes a silent
 * vacuous pass, introduced by the fix.
 *
 * So the population is every emitted content line, whatever its indentation and
 * whatever syntax the artefact is written in. It cannot miss a carrier line by
 * construction — that is what makes it survive the eighth artefact — and it is a
 * strict superset of what the enumeration selected. Measured on this tree, lines
 * inspected per artefact, enumeration -> subtraction: composition 214 -> 216,
 * manifest-index 144 -> 156, entities-registry 71 -> 143, migrations-registry
 * 183 -> 371, admin-registry 56 -> 117, docs-sidebar **0** -> 105, module-map
 * **0** -> 83.
 *
 * **Comments are out, and not for tidiness.** `entities-registry`'s header
 * explains in prose why an entity under `src/apps/` is refused, so a search over
 * the whole file matches that sentence — the same lesson the `overlay: true`
 * case learned: assert on what the generator emits, not on what it says about
 * itself. Block comments are tracked rather than matched line by line, because a
 * continuation line inside `/* … *\/` or `<!-- … -->` starts with neither marker.
 *
 * The known cost is a false positive: fixed prose a generator writes into a
 * markdown body would be inspected like any other content line. That failure is
 * loud and lands on the merge request that writes the prose, which is the
 * direction to be wrong in.
 */
function emittedLines(content: string): readonly string[] {
  const lines: string[] = [];
  let openBlock: '/*' | '<!--' | null = null;
  for (const raw of content.split('\n')) {
    const line = raw.trim();
    if (openBlock !== null) {
      if (line.includes(openBlock === '/*' ? '*/' : '-->')) openBlock = null;
      continue;
    }
    if (line === '' || line.startsWith('//')) continue;
    if (line.startsWith('/*')) {
      if (!line.includes('*/')) openBlock = '/*';
      continue;
    }
    if (line.startsWith('<!--')) {
      if (!line.includes('-->')) openBlock = '<!--';
      continue;
    }
    lines.push(raw);
  }
  return lines;
}

/**
 * The assertion itself, over one artefact — the non-vacuity guard and the two
 * refusals, in one place so a fixture enters where a real artefact enters
 * (issue #130). A proof handed a pre-selected line list would exercise neither
 * the predicate above nor the guard, which is the half that went blind.
 *
 * Returns the number of lines inspected, so a caller can say what it read.
 */
function assertNamesNoDeployment(label: string, content: string): number {
  const lines = emittedLines(content);
  expect(lines.length, `${label} emitted nothing`).toBeGreaterThan(0);
  for (const line of lines) {
    expect(line, `${label} names a deployment tree`).not.toContain('/apps/');
    expect(line, `${label} names the example overlay module`).not.toContain('example_overlay');
  }
  return lines.length;
}
