// AUTO-GENERATED by scripts/generate-manifest-index.ts — DO NOT EDIT.
// Run `pnpm --filter backend exec tsx scripts/generate-manifest-index.ts`
// (or rebuild the backend) to refresh.

import type { ModuleManifest } from '@b2b/contracts';

import { manifest as manifest_0 } from '../_i18n/manifest.js';
import { manifest as manifest_1 } from '../_lifecycle/manifest.js';
import { manifest as manifest_2 } from '../addresses/manifest.js';
import { manifest as manifest_3 } from '../admin_actions/manifest.js';
import { manifest as manifest_4 } from '../admin_notifications/manifest.js';
import { manifest as manifest_5 } from '../admin_roles/manifest.js';
import { manifest as manifest_6 } from '../admin_users/manifest.js';
import { manifest as manifest_7 } from '../analytics/manifest.js';
import { manifest as manifest_8 } from '../api_keys/manifest.js';
import { manifest as manifest_9 } from '../assets/manifest.js';
import { manifest as manifest_10 } from '../assets_library/manifest.js';
import { manifest as manifest_11 } from '../audit_logs/manifest.js';
import { manifest as manifest_12 } from '../auth/manifest.js';
import { manifest as manifest_13 } from '../blog/manifest.js';
import { manifest as manifest_14 } from '../carts/manifest.js';
import { manifest as manifest_15 } from '../catalog/manifest.js';
import { manifest as manifest_16 } from '../cms/manifest.js';
import { manifest as manifest_17 } from '../comparisons/manifest.js';
import { manifest as manifest_18 } from '../credentials/manifest.js';
import { manifest as manifest_19 } from '../credit_limits/manifest.js';
import { manifest as manifest_20 } from '../currencies/manifest.js';
import { manifest as manifest_21 } from '../custom_fields/manifest.js';
import { manifest as manifest_22 } from '../customer_accounts/manifest.js';
import { manifest as manifest_23 } from '../customers/manifest.js';
import { manifest as manifest_24 } from '../delivery_methods/manifest.js';
import { manifest as manifest_25 } from '../dictionaries/manifest.js';
import { manifest as manifest_26 } from '../email/manifest.js';
import { manifest as manifest_27 } from '../google_analytics/manifest.js';
import { manifest as manifest_28 } from '../health_checks/manifest.js';
import { manifest as manifest_29 } from '../import_export/manifest.js';
import { manifest as manifest_30 } from '../inventory/manifest.js';
import { manifest as manifest_31 } from '../invoices/manifest.js';
import { manifest as manifest_32 } from '../ksef/manifest.js';
import { manifest as manifest_33 } from '../languages/manifest.js';
import { manifest as manifest_34 } from '../linkedin_ads/manifest.js';
import { manifest as manifest_35 } from '../megamenu/manifest.js';
import { manifest as manifest_36 } from '../meta_ads/manifest.js';
import { manifest as manifest_37 } from '../mfa/manifest.js';
import { manifest as manifest_38 } from '../newsletter/manifest.js';
import { manifest as manifest_39 } from '../orders/manifest.js';
import { manifest as manifest_40 } from '../organizations/manifest.js';
import { manifest as manifest_41 } from '../payment_methods/manifest.js';
import { manifest as manifest_42 } from '../payments/manifest.js';
import { manifest as manifest_43 } from '../price_lists/manifest.js';
import { manifest as manifest_44 } from '../promotions/manifest.js';
import { manifest as manifest_45 } from '../prompt_actions/manifest.js';
import { manifest as manifest_46 } from '../pwa/manifest.js';
import { manifest as manifest_47 } from '../quick_order/manifest.js';
import { manifest as manifest_48 } from '../quote_requests/manifest.js';
import { manifest as manifest_49 } from '../returns/manifest.js';
import { manifest as manifest_50 } from '../sales_channels/manifest.js';
import { manifest as manifest_51 } from '../search/manifest.js';
import { manifest as manifest_52 } from '../seo/manifest.js';
import { manifest as manifest_53 } from '../settings/manifest.js';
import { manifest as manifest_54 } from '../shipments/manifest.js';
import { manifest as manifest_55 } from '../shopping_lists/manifest.js';
import { manifest as manifest_56 } from '../stripe/manifest.js';
import { manifest as manifest_57 } from '../taxes/manifest.js';
import { manifest as manifest_58 } from '../tpay/manifest.js';
import { manifest as manifest_59 } from '../transactional_emails/manifest.js';
import { manifest as manifest_60 } from '../webhooks/manifest.js';

export interface DiscoveredManifestEntry {
  id: string;
  manifest: ModuleManifest;
}

export const DISCOVERED_MANIFESTS: ReadonlyArray<DiscoveredManifestEntry> = [
  { id: '_i18n', manifest: manifest_0 },
  { id: '_lifecycle', manifest: manifest_1 },
  { id: 'addresses', manifest: manifest_2 },
  { id: 'admin_actions', manifest: manifest_3 },
  { id: 'admin_notifications', manifest: manifest_4 },
  { id: 'admin_roles', manifest: manifest_5 },
  { id: 'admin_users', manifest: manifest_6 },
  { id: 'analytics', manifest: manifest_7 },
  { id: 'api_keys', manifest: manifest_8 },
  { id: 'assets', manifest: manifest_9 },
  { id: 'assets_library', manifest: manifest_10 },
  { id: 'audit_logs', manifest: manifest_11 },
  { id: 'auth', manifest: manifest_12 },
  { id: 'blog', manifest: manifest_13 },
  { id: 'carts', manifest: manifest_14 },
  { id: 'catalog', manifest: manifest_15 },
  { id: 'cms', manifest: manifest_16 },
  { id: 'comparisons', manifest: manifest_17 },
  { id: 'credentials', manifest: manifest_18 },
  { id: 'credit_limits', manifest: manifest_19 },
  { id: 'currencies', manifest: manifest_20 },
  { id: 'custom_fields', manifest: manifest_21 },
  { id: 'customer_accounts', manifest: manifest_22 },
  { id: 'customers', manifest: manifest_23 },
  { id: 'delivery_methods', manifest: manifest_24 },
  { id: 'dictionaries', manifest: manifest_25 },
  { id: 'email', manifest: manifest_26 },
  { id: 'google_analytics', manifest: manifest_27 },
  { id: 'health_checks', manifest: manifest_28 },
  { id: 'import_export', manifest: manifest_29 },
  { id: 'inventory', manifest: manifest_30 },
  { id: 'invoices', manifest: manifest_31 },
  { id: 'ksef', manifest: manifest_32 },
  { id: 'languages', manifest: manifest_33 },
  { id: 'linkedin_ads', manifest: manifest_34 },
  { id: 'megamenu', manifest: manifest_35 },
  { id: 'meta_ads', manifest: manifest_36 },
  { id: 'mfa', manifest: manifest_37 },
  { id: 'newsletter', manifest: manifest_38 },
  { id: 'orders', manifest: manifest_39 },
  { id: 'organizations', manifest: manifest_40 },
  { id: 'payment_methods', manifest: manifest_41 },
  { id: 'payments', manifest: manifest_42 },
  { id: 'price_lists', manifest: manifest_43 },
  { id: 'promotions', manifest: manifest_44 },
  { id: 'prompt_actions', manifest: manifest_45 },
  { id: 'pwa', manifest: manifest_46 },
  { id: 'quick_order', manifest: manifest_47 },
  { id: 'quote_requests', manifest: manifest_48 },
  { id: 'returns', manifest: manifest_49 },
  { id: 'sales_channels', manifest: manifest_50 },
  { id: 'search', manifest: manifest_51 },
  { id: 'seo', manifest: manifest_52 },
  { id: 'settings', manifest: manifest_53 },
  { id: 'shipments', manifest: manifest_54 },
  { id: 'shopping_lists', manifest: manifest_55 },
  { id: 'stripe', manifest: manifest_56 },
  { id: 'taxes', manifest: manifest_57 },
  { id: 'tpay', manifest: manifest_58 },
  { id: 'transactional_emails', manifest: manifest_59 },
  { id: 'webhooks', manifest: manifest_60 },
];
