// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// The manifest registry — the **only** file that imports a **core** module's
// manifest. Every core module that ships a lifecycle-shape `manifest.ts` is
// here, with the lifecycle exports it declares — its install hooks and its
// lifecycle participant.
//
// Bare core under every value of `DEPLOYMENT` (D-104). A deployment's overlay
// manifests are discovered at runtime and merged on top of this index by
// `resolvedManifestEntries()`, because which deployment a build is depends on
// the process rather than on the tree this file was generated from.
//
// It used to have a twin (`registered-manifests.ts`) importing the same
// manifests behind a second command, which is a drift waiting to happen; that
// file now derives its entries from this array instead.
//
// Order is alphabetical and no consumer depends on it:
// `collectRegisteredSettingsManifests()` re-imposes its own (settings first,
// because every other module's settings fall back to its `general` group), and
// everything else topo-sorts or set-ifies.

import type { ModuleManifest, ModuleManifestExports } from '@b2b/contracts';

import { manifest as manifest0, lifecycleParticipant as lifecycleParticipant0 } from '../_i18n/manifest.js';
import { manifest as manifest1 } from '../_lifecycle/manifest.js';
import { manifest as manifest2 } from '../addresses/manifest.js';
import { manifest as manifest3, lifecycleParticipant as lifecycleParticipant3 } from '../admin_actions/manifest.js';
import { manifest as manifest4 } from '../admin_notifications/manifest.js';
import { manifest as manifest5 } from '../admin_roles/manifest.js';
import { manifest as manifest6 } from '../admin_users/manifest.js';
import { manifest as manifest7 } from '../analytics/manifest.js';
import { manifest as manifest8 } from '../api_keys/manifest.js';
import { manifest as manifest9 } from '../assets_library/manifest.js';
import { manifest as manifest10 } from '../audit_logs/manifest.js';
import { manifest as manifest11 } from '../auth/manifest.js';
import { manifest as manifest12 } from '../autopay/manifest.js';
import { manifest as manifest13 } from '../blog/manifest.js';
import { manifest as manifest14 } from '../carts/manifest.js';
import { manifest as manifest15 } from '../catalog/manifest.js';
import { manifest as manifest16 } from '../cms/manifest.js';
import { manifest as manifest17 } from '../comparisons/manifest.js';
import { manifest as manifest18 } from '../credentials/manifest.js';
import { manifest as manifest19 } from '../credit_limits/manifest.js';
import { manifest as manifest20 } from '../currencies/manifest.js';
import { manifest as manifest21, uninstallHook as uninstallHook21 } from '../custom_fields/manifest.js';
import { manifest as manifest22 } from '../customer_accounts/manifest.js';
import { manifest as manifest23 } from '../customers/manifest.js';
import { manifest as manifest24 } from '../delivery_methods/manifest.js';
import { manifest as manifest25 } from '../dictionaries/manifest.js';
import { manifest as manifest26 } from '../email/manifest.js';
import { manifest as manifest27 } from '../google_analytics/manifest.js';
import { manifest as manifest28 } from '../google_tag_manager/manifest.js';
import { manifest as manifest29 } from '../health_checks/manifest.js';
import { manifest as manifest30 } from '../import_export/manifest.js';
import { manifest as manifest31 } from '../inventory/manifest.js';
import { manifest as manifest32 } from '../invoices/manifest.js';
import { manifest as manifest33 } from '../ksef/manifest.js';
import { manifest as manifest34 } from '../languages/manifest.js';
import { manifest as manifest35 } from '../linkedin_ads/manifest.js';
import { manifest as manifest36 } from '../megamenu/manifest.js';
import { manifest as manifest37 } from '../meta_ads/manifest.js';
import { manifest as manifest38 } from '../mfa/manifest.js';
import { manifest as manifest39 } from '../newsletter/manifest.js';
import { manifest as manifest40 } from '../orders/manifest.js';
import { manifest as manifest41 } from '../organizations/manifest.js';
import { manifest as manifest42 } from '../payment_methods/manifest.js';
import { manifest as manifest43 } from '../payments/manifest.js';
import { manifest as manifest44 } from '../paypal/manifest.js';
import { manifest as manifest45 } from '../payu/manifest.js';
import { manifest as manifest46 } from '../pim_ergonode/manifest.js';
import { manifest as manifest47 } from '../price_lists/manifest.js';
import { manifest as manifest48 } from '../product_feeds/manifest.js';
import { manifest as manifest49 } from '../promotions/manifest.js';
import { manifest as manifest50 } from '../prompt_actions/manifest.js';
import { manifest as manifest51 } from '../pwa/manifest.js';
import { manifest as manifest52 } from '../quick_order/manifest.js';
import { manifest as manifest53 } from '../quote_requests/manifest.js';
import { manifest as manifest54 } from '../returns/manifest.js';
import { manifest as manifest55 } from '../sales_channels/manifest.js';
import { manifest as manifest56 } from '../search/manifest.js';
import { manifest as manifest57 } from '../seo/manifest.js';
import { manifest as manifest58 } from '../settings/manifest.js';
import { manifest as manifest59 } from '../shipments/manifest.js';
import { manifest as manifest60 } from '../shopping_lists/manifest.js';
import { manifest as manifest61 } from '../stripe/manifest.js';
import { manifest as manifest62 } from '../taxes/manifest.js';
import { manifest as manifest63 } from '../tpay/manifest.js';
import { manifest as manifest64 } from '../transactional_emails/manifest.js';
import { manifest as manifest65 } from '../webhooks/manifest.js';

export interface DiscoveredManifestEntry {
  id: string;
  manifest: ModuleManifest;
  installHook?: ModuleManifestExports['installHook'];
  uninstallHook?: ModuleManifestExports['uninstallHook'];
  lifecycleParticipant?: ModuleManifestExports['lifecycleParticipant'];
}

export const DISCOVERED_MANIFESTS: ReadonlyArray<DiscoveredManifestEntry> = [
  { id: '_i18n', manifest: manifest0, lifecycleParticipant: lifecycleParticipant0 },
  { id: '_lifecycle', manifest: manifest1 },
  { id: 'addresses', manifest: manifest2 },
  { id: 'admin_actions', manifest: manifest3, lifecycleParticipant: lifecycleParticipant3 },
  { id: 'admin_notifications', manifest: manifest4 },
  { id: 'admin_roles', manifest: manifest5 },
  { id: 'admin_users', manifest: manifest6 },
  { id: 'analytics', manifest: manifest7 },
  { id: 'api_keys', manifest: manifest8 },
  { id: 'assets_library', manifest: manifest9 },
  { id: 'audit_logs', manifest: manifest10 },
  { id: 'auth', manifest: manifest11 },
  { id: 'autopay', manifest: manifest12 },
  { id: 'blog', manifest: manifest13 },
  { id: 'carts', manifest: manifest14 },
  { id: 'catalog', manifest: manifest15 },
  { id: 'cms', manifest: manifest16 },
  { id: 'comparisons', manifest: manifest17 },
  { id: 'credentials', manifest: manifest18 },
  { id: 'credit_limits', manifest: manifest19 },
  { id: 'currencies', manifest: manifest20 },
  { id: 'custom_fields', manifest: manifest21, uninstallHook: uninstallHook21 },
  { id: 'customer_accounts', manifest: manifest22 },
  { id: 'customers', manifest: manifest23 },
  { id: 'delivery_methods', manifest: manifest24 },
  { id: 'dictionaries', manifest: manifest25 },
  { id: 'email', manifest: manifest26 },
  { id: 'google_analytics', manifest: manifest27 },
  { id: 'google_tag_manager', manifest: manifest28 },
  { id: 'health_checks', manifest: manifest29 },
  { id: 'import_export', manifest: manifest30 },
  { id: 'inventory', manifest: manifest31 },
  { id: 'invoices', manifest: manifest32 },
  { id: 'ksef', manifest: manifest33 },
  { id: 'languages', manifest: manifest34 },
  { id: 'linkedin_ads', manifest: manifest35 },
  { id: 'megamenu', manifest: manifest36 },
  { id: 'meta_ads', manifest: manifest37 },
  { id: 'mfa', manifest: manifest38 },
  { id: 'newsletter', manifest: manifest39 },
  { id: 'orders', manifest: manifest40 },
  { id: 'organizations', manifest: manifest41 },
  { id: 'payment_methods', manifest: manifest42 },
  { id: 'payments', manifest: manifest43 },
  { id: 'paypal', manifest: manifest44 },
  { id: 'payu', manifest: manifest45 },
  { id: 'pim_ergonode', manifest: manifest46 },
  { id: 'price_lists', manifest: manifest47 },
  { id: 'product_feeds', manifest: manifest48 },
  { id: 'promotions', manifest: manifest49 },
  { id: 'prompt_actions', manifest: manifest50 },
  { id: 'pwa', manifest: manifest51 },
  { id: 'quick_order', manifest: manifest52 },
  { id: 'quote_requests', manifest: manifest53 },
  { id: 'returns', manifest: manifest54 },
  { id: 'sales_channels', manifest: manifest55 },
  { id: 'search', manifest: manifest56 },
  { id: 'seo', manifest: manifest57 },
  { id: 'settings', manifest: manifest58 },
  { id: 'shipments', manifest: manifest59 },
  { id: 'shopping_lists', manifest: manifest60 },
  { id: 'stripe', manifest: manifest61 },
  { id: 'taxes', manifest: manifest62 },
  { id: 'tpay', manifest: manifest63 },
  { id: 'transactional_emails', manifest: manifest64 },
  { id: 'webhooks', manifest: manifest65 },
];
