// AUTO-GENERATED by scripts/generate-composer.ts — DO NOT EDIT.
// Run `pnpm --filter backend run composer:generate` (or rebuild the backend)
// to refresh. Editing this file by hand is undone by the next build, and
// `pnpm --filter backend run overlay:check` fails on the drift.
//
// The manifest registry: every core module that ships a lifecycle-shape
// `manifest.ts`. It used to be a hand-maintained array, so a module could ship
// a manifest and still contribute no permissions, no i18n bundle and no palette
// action because nobody remembered the third edit.
//
// Order is alphabetical and no consumer depends on it:
// `collectRegisteredSettingsManifests()` re-imposes its own (settings first,
// because every other module's settings fall back to its `general` group), and
// everything else topo-sorts or set-ifies.

import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { ModuleManifest, ModuleManifestExports } from '@b2b/contracts';
import { DISCOVERED_MANIFESTS } from './manifest-index.generated.js';
import { overlayModulesRootFor, selectedDeployment } from '../../overlay/overlay-roots.js';

import { manifest as manifest0 } from '../_i18n/manifest.js';
import { manifest as manifest1 } from '../_lifecycle/manifest.js';
import { manifest as manifest2 } from '../addresses/manifest.js';
import { manifest as manifest3 } from '../admin_actions/manifest.js';
import { manifest as manifest4 } from '../admin_notifications/manifest.js';
import { manifest as manifest5 } from '../admin_roles/manifest.js';
import { manifest as manifest6 } from '../admin_users/manifest.js';
import { manifest as manifest7 } from '../analytics/manifest.js';
import { manifest as manifest8 } from '../api_keys/manifest.js';
import { manifest as manifest9 } from '../assets_library/manifest.js';
import { manifest as manifest10 } from '../audit_logs/manifest.js';
import { manifest as manifest11 } from '../auth/manifest.js';
import { manifest as manifest12 } from '../autopay/manifest.js';
import { manifest as manifest13 } from '../blog/manifest.js';
import { manifest as manifest14 } from '../carts/manifest.js';
import { manifest as manifest15 } from '../catalog/manifest.js';
import { manifest as manifest16 } from '../cms/manifest.js';
import { manifest as manifest17 } from '../comparisons/manifest.js';
import { manifest as manifest18 } from '../credentials/manifest.js';
import { manifest as manifest19 } from '../credit_limits/manifest.js';
import { manifest as manifest20 } from '../currencies/manifest.js';
import { manifest as manifest21, uninstallHook as uninstallHook21 } from '../custom_fields/manifest.js';
import { manifest as manifest22 } from '../customer_accounts/manifest.js';
import { manifest as manifest23 } from '../customers/manifest.js';
import { manifest as manifest24 } from '../delivery_methods/manifest.js';
import { manifest as manifest25 } from '../dictionaries/manifest.js';
import { manifest as manifest26 } from '../email/manifest.js';
import { manifest as manifest27 } from '../google_analytics/manifest.js';
import { manifest as manifest28 } from '../google_tag_manager/manifest.js';
import { manifest as manifest29 } from '../health_checks/manifest.js';
import { manifest as manifest30 } from '../import_export/manifest.js';
import { manifest as manifest31 } from '../inventory/manifest.js';
import { manifest as manifest32 } from '../invoices/manifest.js';
import { manifest as manifest33 } from '../ksef/manifest.js';
import { manifest as manifest34 } from '../languages/manifest.js';
import { manifest as manifest35 } from '../linkedin_ads/manifest.js';
import { manifest as manifest36 } from '../megamenu/manifest.js';
import { manifest as manifest37 } from '../meta_ads/manifest.js';
import { manifest as manifest38 } from '../mfa/manifest.js';
import { manifest as manifest39 } from '../newsletter/manifest.js';
import { manifest as manifest40 } from '../orders/manifest.js';
import { manifest as manifest41 } from '../organizations/manifest.js';
import { manifest as manifest42 } from '../payment_methods/manifest.js';
import { manifest as manifest43 } from '../payments/manifest.js';
import { manifest as manifest44 } from '../payu/manifest.js';
import { manifest as manifest45 } from '../pim_ergonode/manifest.js';
import { manifest as manifest46 } from '../price_lists/manifest.js';
import { manifest as manifest47 } from '../product_feeds/manifest.js';
import { manifest as manifest48 } from '../promotions/manifest.js';
import { manifest as manifest49 } from '../prompt_actions/manifest.js';
import { manifest as manifest50 } from '../pwa/manifest.js';
import { manifest as manifest51 } from '../quick_order/manifest.js';
import { manifest as manifest52 } from '../quote_requests/manifest.js';
import { manifest as manifest53 } from '../returns/manifest.js';
import { manifest as manifest54 } from '../sales_channels/manifest.js';
import { manifest as manifest55 } from '../search/manifest.js';
import { manifest as manifest56 } from '../seo/manifest.js';
import { manifest as manifest57 } from '../settings/manifest.js';
import { manifest as manifest58 } from '../shipments/manifest.js';
import { manifest as manifest59 } from '../shopping_lists/manifest.js';
import { manifest as manifest60 } from '../stripe/manifest.js';
import { manifest as manifest61 } from '../taxes/manifest.js';
import { manifest as manifest62 } from '../tpay/manifest.js';
import { manifest as manifest63 } from '../transactional_emails/manifest.js';
import { manifest as manifest64 } from '../webhooks/manifest.js';

/**
 * Each entry carries a real `filePath` so downstream reconcilers can locate the
 * module's directory on disk — notably the i18n bundle loader
 * (`_i18n/plugin.ts`) does `dirname(entry.filePath)` and joins `bundlesDir` to
 * find each module's `i18n/<lang>.json` files. Without a real path,
 * `dirname('<static>')` resolves to `.`, no bundle ever loads, and every action
 * label renders as its raw i18n key.
 */
export interface RegisteredManifestEntry {
  manifest: ModuleManifest;
  filePath: string;
  installHook?: ModuleManifestExports['installHook'];
  uninstallHook?: ModuleManifestExports['uninstallHook'];
}

/**
 * Convention: every module lives at `backend/src/modules/<id>/manifest.ts`.
 * `import.meta.url` points at this `_lifecycle/registered-manifests.ts`, so
 * `dirname(dirname(...))` lands on the modules root.
 */
const MODULES_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const pathFor = (id: string): string => join(MODULES_ROOT, id, 'manifest.ts');

export const REGISTERED_MANIFESTS: ReadonlyArray<RegisteredManifestEntry> = [
  { manifest: manifest0, filePath: pathFor('_i18n') },
  { manifest: manifest1, filePath: pathFor('_lifecycle') },
  { manifest: manifest2, filePath: pathFor('addresses') },
  { manifest: manifest3, filePath: pathFor('admin_actions') },
  { manifest: manifest4, filePath: pathFor('admin_notifications') },
  { manifest: manifest5, filePath: pathFor('admin_roles') },
  { manifest: manifest6, filePath: pathFor('admin_users') },
  { manifest: manifest7, filePath: pathFor('analytics') },
  { manifest: manifest8, filePath: pathFor('api_keys') },
  { manifest: manifest9, filePath: pathFor('assets_library') },
  { manifest: manifest10, filePath: pathFor('audit_logs') },
  { manifest: manifest11, filePath: pathFor('auth') },
  { manifest: manifest12, filePath: pathFor('autopay') },
  { manifest: manifest13, filePath: pathFor('blog') },
  { manifest: manifest14, filePath: pathFor('carts') },
  { manifest: manifest15, filePath: pathFor('catalog') },
  { manifest: manifest16, filePath: pathFor('cms') },
  { manifest: manifest17, filePath: pathFor('comparisons') },
  { manifest: manifest18, filePath: pathFor('credentials') },
  { manifest: manifest19, filePath: pathFor('credit_limits') },
  { manifest: manifest20, filePath: pathFor('currencies') },
  { manifest: manifest21, filePath: pathFor('custom_fields'), uninstallHook: uninstallHook21 },
  { manifest: manifest22, filePath: pathFor('customer_accounts') },
  { manifest: manifest23, filePath: pathFor('customers') },
  { manifest: manifest24, filePath: pathFor('delivery_methods') },
  { manifest: manifest25, filePath: pathFor('dictionaries') },
  { manifest: manifest26, filePath: pathFor('email') },
  { manifest: manifest27, filePath: pathFor('google_analytics') },
  { manifest: manifest28, filePath: pathFor('google_tag_manager') },
  { manifest: manifest29, filePath: pathFor('health_checks') },
  { manifest: manifest30, filePath: pathFor('import_export') },
  { manifest: manifest31, filePath: pathFor('inventory') },
  { manifest: manifest32, filePath: pathFor('invoices') },
  { manifest: manifest33, filePath: pathFor('ksef') },
  { manifest: manifest34, filePath: pathFor('languages') },
  { manifest: manifest35, filePath: pathFor('linkedin_ads') },
  { manifest: manifest36, filePath: pathFor('megamenu') },
  { manifest: manifest37, filePath: pathFor('meta_ads') },
  { manifest: manifest38, filePath: pathFor('mfa') },
  { manifest: manifest39, filePath: pathFor('newsletter') },
  { manifest: manifest40, filePath: pathFor('orders') },
  { manifest: manifest41, filePath: pathFor('organizations') },
  { manifest: manifest42, filePath: pathFor('payment_methods') },
  { manifest: manifest43, filePath: pathFor('payments') },
  { manifest: manifest44, filePath: pathFor('payu') },
  { manifest: manifest45, filePath: pathFor('pim_ergonode') },
  { manifest: manifest46, filePath: pathFor('price_lists') },
  { manifest: manifest47, filePath: pathFor('product_feeds') },
  { manifest: manifest48, filePath: pathFor('promotions') },
  { manifest: manifest49, filePath: pathFor('prompt_actions') },
  { manifest: manifest50, filePath: pathFor('pwa') },
  { manifest: manifest51, filePath: pathFor('quick_order') },
  { manifest: manifest52, filePath: pathFor('quote_requests') },
  { manifest: manifest53, filePath: pathFor('returns') },
  { manifest: manifest54, filePath: pathFor('sales_channels') },
  { manifest: manifest55, filePath: pathFor('search') },
  { manifest: manifest56, filePath: pathFor('seo') },
  { manifest: manifest57, filePath: pathFor('settings') },
  { manifest: manifest58, filePath: pathFor('shipments') },
  { manifest: manifest59, filePath: pathFor('shopping_lists') },
  { manifest: manifest60, filePath: pathFor('stripe') },
  { manifest: manifest61, filePath: pathFor('taxes') },
  { manifest: manifest62, filePath: pathFor('tpay') },
  { manifest: manifest63, filePath: pathFor('transactional_emails') },
  { manifest: manifest64, filePath: pathFor('webhooks') },
];

/**
 * The **deployment-resolved** manifest set = the generated core array PLUS any
 * overlay-only module discovered for the active deployment (feature 057).
 *
 * This stays a runtime merge on purpose: an overlay-only module's `filePath`
 * resolves against the deployment root, behind an `existsSync` guard, and the
 * answer depends on which deployment the process runs as — not on which tree it
 * was generated from. For a bare-core build (`DEPLOYMENT` unset) the generated
 * index contains only core modules, so this returns `REGISTERED_MANIFESTS`
 * unchanged (FR-008).
 */
export function resolvedManifestEntries(): RegisteredManifestEntry[] {
  const byId = new Map<string, RegisteredManifestEntry>(
    REGISTERED_MANIFESTS.map((e) => [e.manifest.id, e]),
  );
  const deployment = selectedDeployment();
  for (const discovered of DISCOVERED_MANIFESTS) {
    if (byId.has(discovered.id)) continue; // core module already registered
    // An overlay-only module: prefer a real core path if one somehow exists,
    // else resolve under the deployment's overlay tree.
    const corePath = pathFor(discovered.id);
    const filePath =
      existsSync(corePath) || deployment === null
        ? corePath
        : join(overlayModulesRootFor(deployment), discovered.id, 'manifest.ts');
    byId.set(discovered.id, { manifest: discovered.manifest, filePath });
  }
  return [...byId.values()];
}
