#!/usr/bin/env node
/**
 * `themes:generate` — this instance discovers the themes it has.
 *
 * Two sources, one walk (`contracts/instance-theme-registry.md` §§1–2):
 *
 *   1. every installed package whose own `package.json` declares
 *      `endora: { themes: [...] }`, and
 *   2. every `:root[data-theme='<code>']` block this instance's own
 *      `app/globals.css` declares.
 *
 * Two artefacts come out of that one walk — the code registry and the CSS
 * aggregate — so a discovered theme is *declared* and *imported* by the same
 * act and the two cannot drift. That is what makes installing a theme
 * `npm install` and nothing else: no line for anyone to add to a file they
 * edit, and so no half-installed theme and no merge conflict on upgrade.
 *
 * It runs at build time (`predev`, `prebuild`) and never on a request path. The
 * answer cannot change between deploys, and a rendering server may have no
 * `node_modules` tree to walk (`output: 'standalone'`, a container, an edge
 * runtime).
 *
 * Neither source is a list this file carries.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { analysePackages, discoverThemePackages, parseThemeBlocks } from './theme-discovery.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const GLOBALS_CSS = join(root, 'app', 'globals.css');
const REGISTRY_TS = join(root, 'lib', 'theme', 'themes.generated.ts');
const AGGREGATE_CSS = join(root, 'app', 'themes.generated.css');
const NODE_MODULES = join(root, 'node_modules');

const BANNER = [
  '/*',
  ' * GENERATED by `pnpm --filter storefront run themes:generate`.',
  ' * Never edit this file; run the generator.',
  ' */',
].join('\n');

function main() {
  const { packages } = discoverThemePackages(NODE_MODULES);

  const refusals = analysePackages(packages);
  if (refusals.length > 0) {
    for (const refusal of refusals) {
      process.stderr.write(`[themes:generate] ${refusal.finding}: ${refusal.message}\n`);
    }
    process.stderr.write(
      `[themes:generate] refused: ${refusals.length} package declaration(s) cannot be rendered.\n`,
    );
    process.exit(1);
  }

  const ownBlocks = parseThemeBlocks(readFileSync(GLOBALS_CSS, 'utf8'));
  const ownCodes = [...new Set(ownBlocks.map((block) => block.code))];
  const packageCodes = packages.flatMap((pkg) => pkg.codes);
  const codes = [...new Set([...ownCodes, ...packageCodes])].sort();

  const imports = packages
    .filter((pkg) => pkg.specifier !== null)
    .map((pkg) => `@import '${pkg.specifier}';`);

  writeFileSync(
    REGISTRY_TS,
    [
      '/**',
      ' * GENERATED by `pnpm --filter storefront run themes:generate`.',
      ' * Never edit this file; run the generator.',
      ' *',
      " * The theme codes this storefront instance provides — the union of its own",
      " * `:root[data-theme='…']` blocks and the `endora.themes` declarations of the",
      ' * theme packages it has installed. `lib/theme/instance-themes.ts` is what',
      ' * asks it; nothing else should.',
      ' */',
      `export const INSTANCE_THEME_CODES = [${codes.map((code) => `'${code}'`).join(', ')}] as const;`,
      '',
    ].join('\n'),
    'utf8',
  );

  writeFileSync(
    AGGREGATE_CSS,
    [
      BANNER,
      '/*',
      ' * One `@import` per installed theme package. This instance\'s own themes are',
      ' * already in `globals.css` and are not re-imported here.',
      ' *',
      " * `globals.css` imports this file once, above `:root.is-dark`. That position",
      ' * is load-bearing: both selectors have specificity (0,2,0), so document order',
      ' * decides, and an import below the dark scope silently disables dark mode for',
      ' * every themed channel. `check:themes` refuses it as `dark-scope-shadowed`.',
      ' */',
      ...(imports.length === 0 ? ['/* No theme package is installed. */'] : imports),
      '',
    ].join('\n'),
    'utf8',
  );

  process.stdout.write(
    `[themes:generate] wrote: themes=${codes.length} packages=${packages.length} ` +
      `imports=${imports.length} codes=${codes.join(',') || '(none)'}\n`,
  );
}

main();
