import type { EntityManager } from '@mikro-orm/postgresql';

/**
 * The one co-transactional seam this module publishes (D-178, under D-78
 * point 2).
 *
 * It is declared here rather than in `@endora-commerce/contracts` for the same
 * reason `credit_limits`' `CreditLimitPort` and `promotions`'
 * `PromotionUsageFinalizer` are: its signature carries the caller's MikroORM
 * `EntityManager`, and FR-034 keeps a MikroORM type out of that package. A
 * branded stand-in would publish the coupling instead of removing it, which
 * D-78 refuses in writing.
 *
 * **What holds it co-transactional is a foreign key, not a convention.**
 * `customer_accounts_organization_fk` (`on delete restrict`) points
 * `customer_accounts.organization_id` at `organizations.id`, and since D-178
 * that column is `NOT NULL`. So the account row cannot be inserted before the
 * organisation exists, and a second transaction cannot satisfy a foreign key
 * against a row it cannot see. The two writes are one unit of work or the
 * invariant has a window in it — which is precisely the window D-178 was taken
 * to close: `createStandalone` used to commit the account with a null
 * organisation and provision the organisation afterwards, and nothing retried
 * the second half.
 *
 * `customer_accounts` is the caller and it already declares `organizations` in
 * its manifest `dependencies` — the tenancy direction feature 051 established —
 * so the edge this seam needs is the one the foreign key already required.
 */
export interface PersonalOrganizationProvisionInput {
  /**
   * The id the account **will** carry. It is generated by the caller before the
   * account row exists, because the personal organisation's `taxId` is derived
   * from it and that derivation is what makes the provisioning re-runnable.
   */
  readonly customerAccountId: string;
  readonly email: string;
  readonly firstName?: string | null;
  readonly lastName?: string | null;
}

export interface PersonalOrganizationProvisionApi {
  /**
   * Find-or-create the personal organisation for an account that is about to be
   * written, on the caller's `EntityManager` and inside the caller's
   * transaction. Writes nothing on `customer_accounts`: the membership column is
   * the caller's own, and it sets it on the row it is inserting.
   *
   * Idempotent by `taxId`, so a retry after a rolled-back attempt re-finds
   * rather than duplicating.
   */
  provisionFor(
    em: EntityManager,
    input: PersonalOrganizationProvisionInput,
  ): Promise<{ id: string }>;
}
