import {
  Activity,
  AlarmClock,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Compass,
  Copy,
  CreditCard,
  Database,
  Download,
  Droplets,
  ExternalLink,
  Eye,
  Factory,
  FileCheck,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  HardHat,
  Heart,
  HeartHandshake,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Newspaper,
  Package,
  Paintbrush,
  Paperclip,
  PenLine,
  Percent,
  Phone,
  PieChart,
  Pin,
  Plane,
  Play,
  Plug,
  Plus,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Receipt,
  RefreshCw,
  Rocket,
  Scale,
  ScanLine,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Sun,
  Target,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Curated Lucide allowlist for CMS Icons / Feature list (not the full catalog). */
export const CMS_ICON_CATALOG = {
  activity: Activity,
  alarmClock: AlarmClock,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  atSign: AtSign,
  award: Award,
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  barChart3: BarChart3,
  bell: Bell,
  bookOpen: BookOpen,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  building2: Building2,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  chartPie: ChartPie,
  check: Check,
  checkCircle2: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circleHelp: CircleHelp,
  clipboardList: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  code2: Code2,
  compass: Compass,
  copy: Copy,
  creditCard: CreditCard,
  database: Database,
  download: Download,
  droplets: Droplets,
  externalLink: ExternalLink,
  eye: Eye,
  factory: Factory,
  fileCheck: FileCheck,
  fileText: FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  gift: Gift,
  globe: Globe,
  graduationCap: GraduationCap,
  handshake: Handshake,
  hardHat: HardHat,
  heart: Heart,
  heartHandshake: HeartHandshake,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  keyRound: KeyRound,
  landmark: Landmark,
  layers: Layers,
  layoutDashboard: LayoutDashboard,
  leaf: Leaf,
  lifeBuoy: LifeBuoy,
  lightbulb: Lightbulb,
  link2: Link2,
  listChecks: ListChecks,
  lock: Lock,
  mail: Mail,
  map: MapIcon,
  mapPin: MapPin,
  medal: Medal,
  megaphone: Megaphone,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  newspaper: Newspaper,
  package: Package,
  paintbrush: Paintbrush,
  paperclip: Paperclip,
  penLine: PenLine,
  percent: Percent,
  phone: Phone,
  pieChart: PieChart,
  pin: Pin,
  plane: Plane,
  play: Play,
  plug: Plug,
  plus: Plus,
  printer: Printer,
  puzzle: Puzzle,
  qrCode: QrCode,
  quote: Quote,
  receipt: Receipt,
  refreshCw: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  scanLine: ScanLine,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  target: Target,
  thumbsUp: ThumbsUp,
  timer: Timer,
  trash2: Trash2,
  trendingUp: TrendingUp,
  truck: Truck,
  upload: Upload,
  user: User,
  userCheck: UserCheck,
  users: Users,
  video: Video,
  wallet: Wallet,
  warehouse: Warehouse,
  wrench: Wrench,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type CmsIconName = keyof typeof CMS_ICON_CATALOG;

export const CMS_ICON_OPTIONS = (Object.keys(CMS_ICON_CATALOG) as CmsIconName[]).map((name) => ({
  label: name,
  value: name,
}));

export function resolveCmsIcon(name: string | undefined): LucideIcon | null {
  if (!name || !(name in CMS_ICON_CATALOG)) return null;
  return CMS_ICON_CATALOG[name as CmsIconName];
}

export function humanizeIconName(name: string): string {
  return name
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .replace(/([a-z])([0-9])/g, '$1 $2')
    .trim();
}
