/**
 * The two files npm force-includes into every tarball — `LICENSE` and
 * `README.md` — rendered for every publishable workspace member
 * (`specs/123-oss-install-experience/`, T6-B and T6-C; FR-020 and FR-021).
 *
 * ## Why they are generated and not written
 *
 * `LICENSE-COMMERCIAL.md` states the rule these exist for: *"npm force-includes
 * a file called `LICENSE` in the published tarball exactly as it does
 * `README.md`, whatever `files` says — so the text has to be **in the package
 * directory**, not only at the repository root. The root `LICENSE` is the
 * canonical copy those are rendered from."* Measured on `origin/master`
 * 2026-09-15: **0** of the 82 publishable members shipped a `LICENSE` and
 * **14** shipped a `README.md`, so 68 package pages would have rendered empty
 * on the first public publish and none of the 82 tarballs would have carried a
 * licence a lawyer could read.
 *
 * Eighty-two hand-kept copies of one licence is D-100's shape exactly — a
 * derived fact written down once per package and drifting thereafter — so the
 * text is rendered from the root `LICENSE`, the same way `license: MIT` is
 * already rendered from the root manifest by {@link rootLicense}. The field and
 * the file are two halves of one statement, which is the reason
 * `generate-module-manifests.ts` writes `tailwind.css` beside the subpath that
 * names it, and it is why this renderer joins that command rather than becoming
 * a second one: one gate, one `read:` line, one `--check`.
 *
 * ## The population is every publishable member, not every module package
 *
 * `renderModulePackageManifests` walks module packages — that is what every
 * floor and coverage number on its arrays is a statement about. These two files
 * are owed by `@endora-commerce/contracts` and `@endora-commerce/cli` exactly as
 * much as by `@endora-commerce/mod-blog`, so the population here is
 * {@link classifyWorkspaceMembers}' *family* members that are not `private` —
 * the same predicate `check:release-intent` calls versionable, and deliberately
 * the same function rather than a second answer to one question (D-100).
 * `backend`, `admin`, `storefront` and `docs` arrive from literal workspace
 * entries, are nobody's dependency and are excluded by that predicate.
 *
 * ## A hand-written README is never overwritten
 *
 * A generated `README.md` carries {@link GENERATED_README_MARKER} on its first
 * line. A file without it is a human's — `packages/platform/README.md` and the
 * thirteen others are — and this renderer neither rewrites it nor reports it as
 * drifted; it is simply not among the artefacts. That is the same shape
 * `descriptionFor` gives the `description` field, and the marker is what makes
 * it a *decision* rather than a race: without it, "the file exists" would freeze
 * the first render forever, and every later subpath or dependency would go
 * silently missing from a page that looks maintained.
 *
 * A `LICENSE` has no such override, and must not: a package whose licence is its
 * own declares it as `packageLicense` (see {@link modulePackageLicenseOf}) in
 * the `SEE LICENSE IN <file>` form, ships the file that names, and is skipped
 * here — `check:release-intent`'s `unresolvable-license-file` is what holds it
 * to that. Copying the root's permissive text under any other declaration is the
 * unauthorised grant that file's docstring refuses.
 */
import { join } from 'node:path';

import { classifyWorkspaceMembers } from '@endora-commerce/cli/lib/workspace-packages.js';

import type { ManifestFs } from './module-package-manifest.js';

/** Thrown for a tree this renderer will not guess its way through. */
export class PackageIdentityError extends Error {
  override readonly name = 'PackageIdentityError';
}

/** The first line of every generated `README.md`, and the whole override rule. */
export const GENERATED_README_MARKER =
  '<!-- Generated by `pnpm --filter backend run manifests:generate`. Delete this line to ' +
  'take the file over; a README without it is never regenerated. -->';

/** One rendered `LICENSE` or `README.md`. */
export interface RenderedPackageFile {
  readonly packageName: string;
  /** Absolute path of the file this content belongs at. */
  readonly outputPath: string;
  readonly content: string;
}

/** What one identity-file run rendered, and what it read to do it. */
export interface PackageIdentityRun {
  readonly licenses: readonly RenderedPackageFile[];
  readonly readmes: readonly RenderedPackageFile[];
  /**
   * Members whose `README.md` a human owns: present on disk without
   * {@link GENERATED_README_MARKER}. Reported so a run cannot be read as
   * covering them.
   */
  readonly handWrittenReadmes: readonly string[];
  /**
   * Members skipped by the licence half because they declare their own
   * `SEE LICENSE IN <file>` licence.
   */
  readonly ownLicenceMembers: readonly string[];
  /** Publishable members this walk found, by npm name — the reconciled population. */
  readonly memberNames: readonly string[];
  /** Files opened: the root `LICENSE`, each member manifest, each existing README. */
  readonly filesRead: number;
}

/**
 * npm's `SEE LICENSE IN <file>` form — the SPDX spelling for a proprietary licence —
 * capturing the file it names.
 */
const SEE_LICENSE_IN = /^SEE LICENSE IN\s+(\S.*)$/;

/**
 * What each published subpath of a **module package** holds.
 *
 * Every entry is the layout contract's own vocabulary
 * (`specs/084-small-f4-package-layout/contracts/module-package-layout.md` §1
 * and §2.1), not a sentence invented here — a module package's `exports` key set
 * is closed, so this map is total over it and a key it does not know is a
 * refusal rather than a blank cell.
 */
const MODULE_SUBPATH_MEANINGS: ReadonlyMap<string, string> = new Map([
  ['.', 'the module manifest — its id, version, dependencies, settings and activation'],
  [
    './backend',
    'the composition root the platform calls, with the entities, services, routes and workers it registers',
  ],
  ['./migrations', 'the module’s own schema migrations, in the order the platform runs them'],
  [
    './contracts',
    'the module’s own vendor contract module: the Zod schemas and inferred types for the API it integrates',
  ],
  ['./ports', 'type-only — the port interfaces other modules resolve this one through'],
  [
    './install',
    'the install surface: factories another module’s `installHook` constructs over its own `EntityManager`',
  ],
  ['./admin', 'the Admin UI contribution: the screens, navigation and palette actions it adds'],
  ['./admin-ui', 'React components this module publishes for another module’s admin screens'],
  ['./tailwind.css', 'the Tailwind source declaration for the admin code above'],
  [
    './test-support',
    'development-only — the test doubles, fixtures and volatile tables this module’s own tests need',
  ],
]);

/** What each entry of a `files` list carries into the tarball. */
const FILES_MEANINGS: ReadonlyMap<string, string> = new Map([
  ['dist', 'the compiled JavaScript and its type declarations'],
  ['docs', 'the package’s own pages in the Endora Commerce documentation site'],
  ['tailwind.css', 'the Tailwind source declaration'],
  ['theme.css', 'the host design system every admin renderer resolves against'],
]);

function manifestString(
  manifest: Readonly<Record<string, unknown>>,
  key: string,
): string | null {
  const value = manifest[key];
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function manifestObject(
  manifest: Readonly<Record<string, unknown>>,
  key: string,
): Readonly<Record<string, unknown>> {
  const value = manifest[key];
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}

/** The `endora.id` a member declares about itself, or `null` when it is not a module. */
function moduleIdOf(manifest: Readonly<Record<string, unknown>>): string | null {
  const endora = manifestObject(manifest, 'endora');
  if (endora['type'] !== 'module') return null;
  const id = endora['id'];
  return typeof id === 'string' && id.length > 0 ? id : null;
}

/** Sorted `exports` keys a consumer may import — `./package.json` is plumbing, not an entry point. */
function entryPoints(manifest: Readonly<Record<string, unknown>>): readonly string[] {
  return Object.keys(manifestObject(manifest, 'exports'))
    .filter((key) => key !== './package.json')
    .sort();
}

/** `{ name: range }` of a dependency block, sorted by name. */
function dependencyEntries(
  manifest: Readonly<Record<string, unknown>>,
  key: string,
): ReadonlyArray<readonly [string, string]> {
  return Object.entries(manifestObject(manifest, key))
    .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
    .sort((left, right) => (left[0] < right[0] ? -1 : left[0] > right[0] ? 1 : 0));
}

function isOptionalPeer(
  manifest: Readonly<Record<string, unknown>>,
  name: string,
): boolean {
  const meta = manifestObject(manifest, 'peerDependenciesMeta');
  return manifestObject(meta, name)['optional'] === true;
}

/** `` `@endora-commerce/mod-blog` `` — one code-spanned name, with its range where it has one. */
function nameWithRange(name: string, range: string): string {
  // A `workspace:*` range is this repository's own link protocol and means
  // nothing to a reader of the published package; the range npm resolves is
  // rewritten at publish time. Printing it would be printing a build artefact.
  return range.startsWith('workspace:') ? `\`${name}\`` : `\`${name}\` ${range}`;
}

function bulletList(items: readonly string[]): string {
  return items.map((item) => `- ${item}`).join('\n');
}

/**
 * The locales a package's `i18n/` directory carries — `en`, `pl` — or `[]`.
 *
 * Read from the directory rather than from any declaration, because the
 * bundles are shipped verbatim and nothing else in the tree states which
 * languages one holds.
 */
function localesOf(dir: string, listFiles: (path: string) => readonly string[]): readonly string[] {
  return [...listFiles(join(dir, 'i18n'))]
    .filter((name) => name.endsWith('.json'))
    .map((name) => name.slice(0, -'.json'.length))
    .sort();
}

interface ReadmeInput {
  readonly dir: string;
  readonly name: string;
  readonly manifest: Readonly<Record<string, unknown>>;
  readonly listFiles: (path: string) => readonly string[];
}

/** The README of one publishable member, rendered from what its manifest declares. */
export function renderPackageReadme(input: ReadmeInput): string {
  const { name, manifest } = input;
  const description = manifestString(manifest, 'description');
  if (description === null) {
    throw new PackageIdentityError(
      `${name} declares no \`description\`, so its README would open with nothing but its own ` +
        `name — which is worse than no README at all. It is the one sentence a human writes ` +
        `(module-package-layout.md §2, HAND-WRITTEN); this renderer will not invent it.`,
    );
  }
  const moduleId = moduleIdOf(manifest);
  /** The executables this package puts on the path — `endora`, or none. */
  const executables = Object.keys(manifestObject(manifest, 'bin')).sort();
  const sections: string[] = [
    GENERATED_README_MARKER,
    '',
    `# ${name}`,
    '',
    description,
    '',
    '## What this is',
    '',
  ];

  if (moduleId !== null) {
    sections.push(
      `An **Endora Commerce module package**. Its module id is \`${moduleId}\` — the identity ` +
        `of record in the platform's registries, in its migrations and in its setting, ` +
        `permission and translation codes.`,
      '',
      'A module is not imported by application code. The platform discovers the extension ' +
        'packages an instance has installed, reads the manifest on the root subpath and ' +
        'composes the module from it, so installing this package and starting the instance is ' +
        'the whole integration.',
      '',
    );
  } else {
    sections.push(
      executables.length > 0
        ? `A command-line package of **Endora Commerce**, the modular B2B/B2C commerce ` +
            `platform. Installing it puts ${executables
              .map((executable) => `\`${executable}\``)
              .join(', ')} on the path.`
        : 'A shared library package of **Endora Commerce**, the modular B2B/B2C commerce ' +
          'platform. It declares no module manifest, so the platform composes nothing from ' +
          'it: what is published here is what the platform and the modules built on it ' +
          'compile against.',
      '',
    );
  }

  const entries = entryPoints(manifest);
  if (entries.length > 0) {
    sections.push('## Entry points', '');
    if (moduleId !== null) {
      sections.push('| Import | Contents |', '| --- | --- |');
      for (const subpath of entries) {
        const meaning = MODULE_SUBPATH_MEANINGS.get(subpath);
        if (meaning === undefined) {
          throw new PackageIdentityError(
            `${name} publishes the subpath '${subpath}', which this renderer has no meaning ` +
              `for. A module package's \`exports\` key set is closed ` +
              `(module-package-layout.md §2.2); add the key to MODULE_SUBPATH_MEANINGS in the ` +
              `same merge request that adds it to LAYER_SUBPATHS, rather than letting a ` +
              `published entry point render as a blank cell.`,
          );
        }
        const specifier = subpath === '.' ? name : `${name}${subpath.slice(1)}`;
        sections.push(`| \`${specifier}\` | ${meaning} |`);
      }
    } else {
      sections.push(
        bulletList(
          entries.map((subpath) =>
            subpath === '.' ? `\`${name}\`` : `\`${name}${subpath.slice(1)}\``,
          ),
        ),
      );
    }
    sections.push('');
  }

  const peers = dependencyEntries(manifest, 'peerDependencies');
  const runtime = dependencyEntries(manifest, 'dependencies');
  if (peers.length > 0 || runtime.length > 0) {
    sections.push('## Depends on', '');
    if (peers.length > 0) {
      const endoraPeers = peers.filter(([peer]) => peer.startsWith('@endora-commerce/'));
      const otherPeers = peers.filter(([peer]) => !peer.startsWith('@endora-commerce/'));
      sections.push(
        'Everything below is a **peer** dependency, so the application resolves exactly one ' +
          'copy of each — two copies of a host or of React are a runtime failure rather than a ' +
          'type error. An entry marked *optional* is needed only by the layers that use it.',
        '',
      );
      for (const [heading, group] of [
        ['Endora packages', endoraPeers],
        ['Third-party', otherPeers],
      ] as const) {
        if (group.length === 0) continue;
        sections.push(
          `**${heading}**`,
          '',
          bulletList(
            group.map(
              ([peer, range]) =>
                `${nameWithRange(peer, range)}${isOptionalPeer(manifest, peer) ? ' — *optional*' : ''}`,
            ),
          ),
          '',
        );
      }
    }
    if (runtime.length > 0) {
      sections.push(
        '**Bundled dependencies**',
        '',
        bulletList(runtime.map(([dep, range]) => nameWithRange(dep, range))),
        '',
      );
    }
  }

  const files = manifest['files'];
  const shipped = Array.isArray(files) ? files.filter((f): f is string => typeof f === 'string') : [];
  if (shipped.length > 0) {
    const locales = localesOf(input.dir, input.listFiles);
    const lines = shipped.map((entry) => {
      if (entry === 'i18n') {
        const carried =
          locales.length > 0
            ? ` (${locales.map((locale) => `\`${locale}\``).join(', ')})`
            : '';
        return `\`i18n/\` — the translation bundles this package ships${carried}, loaded by the platform`;
      }
      // A `files` entry naming a directory is written with its slash, as
      // `i18n/` above is: `dist` and `dist.js` are two different claims and
      // only one of them is true of any entry here.
      const shown = entry.includes('.') ? entry : `${entry}/`;
      const meaning = FILES_MEANINGS.get(entry);
      return meaning === undefined ? `\`${shown}\`` : `\`${shown}\` — ${meaning}`;
    });
    sections.push('## What the tarball carries', '', bulletList(lines), '');
  }

  sections.push(
    '## Install',
    '',
    '```bash',
    `pnpm add ${executables.length > 0 ? '-D ' : ''}${name}`,
    '```',
    '',
    '## Licence',
    '',
    licenceSentence(manifestString(manifest, 'license') ?? 'MIT'),
    '',
  );

  return `${sections.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

/**
 * The README's one line about the package's terms. A package taking the
 * workspace default ships the rendered `LICENSE`; one declaring
 * `SEE LICENSE IN <file>` ships that file and no `LICENSE` at all — the renderer
 * writes none beside it — so pointing its reader at `LICENSE` would point them
 * at nothing.
 */
function licenceSentence(declared: string): string {
  const own = SEE_LICENSE_IN.exec(declared);
  if (own !== null) return `The terms are in \`${own[1]!.trim()}\`, beside this file.`;
  return `${declared} — the text is in \`LICENSE\`, beside this file.`;
}

/**
 * Every publishable member's `LICENSE` and `README.md`.
 *
 * `renderedManifests` lets the caller pass the manifests **this run is about to
 * write**, keyed by absolute package directory. Without it a README would be
 * derived from the `package.json` on disk while the same command replaced that
 * file, so one regeneration would leave the two artefacts a generation apart and
 * the idempotence the manifest test asserts would need a second pass to hold.
 */
export function renderPackageIdentityFiles(
  repoRoot: string,
  fs: ManifestFs,
  renderedManifests: ReadonlyMap<string, string> = new Map(),
): PackageIdentityRun {
  let filesRead = 0;
  const licenseText = fs.readText(join(repoRoot, 'LICENSE'));
  if (licenseText === null || licenseText.trim().length === 0) {
    throw new PackageIdentityError(
      `${join(repoRoot, 'LICENSE')} could not be read, so the text every published package ` +
        `ships has no source. It is the canonical copy every MIT package's LICENSE is rendered from; a generator ` +
        `that wrote a licence without one would be granting rights on nobody's authority.`,
    );
  }
  filesRead += 1;

  const { members } = classifyWorkspaceMembers(repoRoot, fs);
  const publishable = members
    .filter((member) => member.family && member.manifest['private'] !== true)
    .sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));
  if (publishable.length === 0) {
    throw new PackageIdentityError(
      `${repoRoot}: the workspace globs matched no publishable package, so this run would ` +
        `render nothing and report success — the vacuous pass a generator must not print ` +
        `(issue #113).`,
    );
  }
  // Each member's manifest was opened by `classifyWorkspaceMembers` to get here.
  filesRead += members.length;

  const licenses: RenderedPackageFile[] = [];
  const readmes: RenderedPackageFile[] = [];
  const handWritten: string[] = [];
  const ownLicence: string[] = [];

  for (const member of publishable) {
    const rendered = renderedManifests.get(member.dir);
    const manifest =
      rendered === undefined
        ? member.manifest
        : (JSON.parse(rendered) as Record<string, unknown>);

    const declared = manifestString(manifest, 'license');
    if (declared === null) {
      throw new PackageIdentityError(
        `${member.name} declares no \`license\`, so there is no statement for a \`LICENSE\` ` +
          `file to carry. Declare the estate's default once at the workspace root and let the ` +
          `manifest generator render the field.`,
      );
    }
    if (SEE_LICENSE_IN.test(declared)) {
      // The package's licence is its own (`packageLicense`), and the file it
      // names is `check:release-intent`'s `unresolvable-license-file`. Writing
      // the root's permissive text beside a proprietary declaration would be
      // two licences in one directory.
      ownLicence.push(member.name);
    } else {
      licenses.push({
        packageName: member.name,
        outputPath: join(member.dir, 'LICENSE'),
        content: licenseText,
      });
    }

    const existing = fs.readText(join(member.dir, 'README.md'));
    if (existing !== null) filesRead += 1;
    if (existing !== null && !existing.startsWith(GENERATED_README_MARKER)) {
      handWritten.push(member.name);
      continue;
    }
    readmes.push({
      packageName: member.name,
      outputPath: join(member.dir, 'README.md'),
      content: renderPackageReadme({
        dir: member.dir,
        name: member.name,
        manifest,
        listFiles: fs.listFiles,
      }),
    });
  }

  return {
    licenses,
    readmes,
    handWrittenReadmes: handWritten,
    ownLicenceMembers: ownLicence,
    memberNames: publishable.map((member) => member.name),
    filesRead,
  };
}
